from typing import Protocol

class IOAuthTokenProvider(Protocol):
    async def get_access_token(self) -> str: ...

class OAuthTokenProvider(IOAuthTokenProvider):
    def __init__(self, domain: str, client_id: str, client_secret: str, audience: str, scope: str) -> None: ...
    async def get_access_token(self) -> str: ...
