from typing import Any

class TokenVerificationError(Exception): ...

class OAuth2TokenVerifier:
    def __init__(self, domain: str, audience: str, algorithms: list[str], issuer: str) -> None: ...
    async def get_jwks(self) -> dict[str, Any]: ...
    async def verify_token(self, token: str) -> dict[str, Any]: ...
    def verify_scopes(self, payload: dict[str, Any], required_scopes: list[str]) -> bool: ...
