from _typeshed import Incomplete
from minjiang_client.group import Group as Group
from minjiang_client.languages import lang as lang
from minjiang_client.plugin.plugin_register import plugin_register as plugin_register, reg_to_hook as reg_to_hook
from minjiang_client.utils import parse_type as parse_type

def scan_exp(start, end, steps, b: int = 0): ...
def scan_log(start, end, steps, b: int = 0): ...
def scan_sin(start, end, steps, b: int = 0): ...
def scan_cos(start, end, steps, b: int = 0): ...
def scan_sqrt(start, end, steps, b: int = 0): ...

class Public: ...

class ScriptEvaluator:
    functions: Incomplete
    function_description: Incomplete
    group: Group | None
    variables: Incomplete
    def __init__(self, group: Group = None) -> None: ...
    def get_space_parameter(self, key: str): ...
    def get_device_parameter(self, key: str): ...
    def register_function(self, func_name, func) -> None: ...
    def evaluate(self, expression: str): ...
