from _typeshed import Incomplete
from minjiang_client.languages import lang as lang
from minjiang_client.utils.local import get_cache_dir as get_cache_dir

class SpaceCache:
    group_name: Incomplete
    space_id: Incomplete
    conn: Incomplete
    def __init__(self, group_name: str, space_id: int) -> None: ...
    @property
    def db_filename(self) -> str: ...
    def create_cache_dir(self): ...
    def create_connection(self): ...
    def create_tables(self) -> None: ...
    def get_cache_info(self): ...
    def remove_key(self, key: str, timestamp): ...
    def update_cache(self, keys, values, dtypes, create_uids, descriptions, timestamp) -> None: ...
    def read_all(self, return_desc: bool = False): ...
    def read_by_keys(self, keys: list[str], return_desc: bool = False): ...
    def fuzzy_query(self, search_query: str) -> list[str]: ...
