# Consts related to Invoice amounts
AMOUNT_PRECISION = 5
AMOUNT_RATIO = pow(10, AMOUNT_PRECISION)
# 5€ => 500000 in db format
PAYMENT_EPSILON = 5 * 10**AMOUNT_PRECISION
PAYMENT_SUM_EPSILON = 0.1 * 10**AMOUNT_PRECISION
PAGINATION_DEFAULT_PAGE = 1
PAGINATION_DEFAULT_PER_PAGE = 50
