from minjiang_client.qc.cliffords import TwoQubitClifford as TwoQubitClifford, clifford_gates as clifford_gates

def matrix_distance_ignore_global_phase(A, B): ...
def matrix_distance_ignore_global_phase_simple(A, B): ...
def generate_rb_sequence_1q(length): ...
def generate_rb_sequence_2q(length: int): ...
def fit_rb_curve(lengths, fidelities): ...
