from minjiang_client.com.minio import get_minio_client as get_minio_client
from minjiang_client.experiment.experiment import Experiment as Experiment
from minjiang_client.experiment.fitter import Fitter as Fitter
from minjiang_client.experiment.result import Result as Result
from minjiang_client.group.cloud_group import CloudGroup as CloudGroup
from minjiang_client.utils.json_database import Column as Column, JSONDatatable as JSONDatatable
from minjiang_client.utils.local import get_fit_cache_dir as get_fit_cache_dir
from typing import Any, Callable
from urllib.parse import quote as quote

def show_realtime_plot(result: Result, finished: bool, exp_detail: dict, select_fields: list[str] | str | None = None): ...
def show_progress(result: Result, finished: bool, exp_detail: dict, device_group_name: str = None, space_id: int = None, enable_plot: bool = False, select_fields: list[str] | str | None = None): ...

class NGroup(CloudGroup):
    def __init__(self, group_name: str, space_name: str, space_version: int = None, space_parameters: dict[str, Any] = None, temporary_parameters: dict[str, Any] = None) -> None: ...
    def submit_exp(self, exp: Experiment, space_timestamp: int = None, template_name: str = None, source: str = 'SDK', attachment: dict[str, int] = None, exp_folder_id: int = None, exp_folder_path: str = None, priority: str = None): ...
    def fit_png(self, exp_detail: dict): ...
    def fit_tbl(self, exp_detail: dict, data: dict = None): ...
    def print_space_update(self) -> None: ...
    def submit_fit(self, exp_id: int, fit_png: str, fit_tbl: str, space_parameters: dict = None): ...
    def pull_result(self, exp_id: int, waiting_for_finished: bool = True, update_callback: Callable = None, enable_realtime_plot: bool = False, select_fields: list[str] | str | None = None) -> Result: ...
