from minjiang_client.utils.config_manager import ConfigManager as ConfigManager

class SpaceInitializer:
    title: str
    desc: str
    config_manager: ConfigManager
    def __init__(self, title: str, desc: str) -> None: ...
    @property
    def cm(self) -> ConfigManager: ...
    def get_initializer_setup(self) -> dict: ...
    def set_initializer_setup(self) -> None: ...
    @staticmethod
    def get_initializer_description() -> dict: ...
    def make_parameters(self, **kwargs) -> None: ...
    def input_settings(self, **kwargs) -> None: ...
