"""Employee Tables API domain."""

from pybob_sdk.employee_tables.api import EmployeeTablesAPI
from pybob_sdk.employee_tables.models import (
    BankAccount,
    BankAccountCreateRequest,
    BankAccountUpdateRequest,
    EmploymentEntry,
    EmploymentEntryCreateRequest,
    EmploymentEntryUpdateRequest,
    EquityGrant,
    EquityGrantCreateRequest,
    EquityGrantUpdateRequest,
    LifecycleEntry,
    PayrollEntry,
    SalaryEntry,
    SalaryEntryCreateRequest,
    TrainingRecord,
    TrainingRecordCreateRequest,
    VariablePayment,
    VariablePaymentCreateRequest,
    WorkEntry,
    WorkEntryCreateRequest,
    WorkEntryUpdateRequest,
)

__all__ = [
    "BankAccount",
    "BankAccountCreateRequest",
    "BankAccountUpdateRequest",
    "EmployeeTablesAPI",
    "EmploymentEntry",
    "EmploymentEntryCreateRequest",
    "EmploymentEntryUpdateRequest",
    "EquityGrant",
    "EquityGrantCreateRequest",
    "EquityGrantUpdateRequest",
    "LifecycleEntry",
    "PayrollEntry",
    "SalaryEntry",
    "SalaryEntryCreateRequest",
    "TrainingRecord",
    "TrainingRecordCreateRequest",
    "VariablePayment",
    "VariablePaymentCreateRequest",
    "WorkEntry",
    "WorkEntryCreateRequest",
    "WorkEntryUpdateRequest",
]
