class CmfClientException(Exception): # noqa: N818
    """Base exception for CMF client errors."""
class EmptyPath(CmfClientException): ...
class BadStatus(CmfClientException): ...
class EmptyApiKey(CmfClientException): ...
class InvalidPath(CmfClientException): ...
class ConnectError(CmfClientException): ...


class PpuException(Exception): # noqa: N818
    """Base exception for PPU verification errors."""
class UnknownFormat(PpuException): ...
class InvalidLength(PpuException): ...
class UnknownLetter(PpuException): ...
class EmptyLetters(PpuException): ...
class UnknownDigraph(PpuException): ...
class EmptyDigraph(PpuException): ...


class VerifierException(Exception): # noqa: N818
    """Base exception for verifier errors."""
class EmptyDigits(VerifierException): ...
class EmptyVerifier(VerifierException): ...
class InvalidDigits(VerifierException): ...
class InvalidVerifier(VerifierException): ...
class UnexpectedComputation(VerifierException): ...


class GenerateException(Exception): # noqa: N818
    """Base exception for generation errors."""
class InvalidRange(GenerateException): ...
class InvalidInput(GenerateException): ...
class InsufficientRange(GenerateException): ...
class UnexpectedGeneration(GenerateException): ...