from minjiang_client.com.request import request as request
from minjiang_client.com.user import add_user as add_user

def create_organization(name: str, admin_ids: list[int], user_ids: list[int]): ...
def get_org_info(org_id: int): ...
def get_org_list(): ...
def get_admin_org_list(): ...
def get_all_org_users(): ...
def get_org_users(organization_id: int): ...
def get_org_devices(organization_id: int): ...
def add_org_user(organization_id: int, user_name: str, org_role: str = 'ORG_MEMBER'): ...
def delete_org_user(organization_id: int, user_id: int): ...
def modify_org_user_role(organization_id: int, user_id: int, org_role: str): ...
def modify_user_device_group_permission(organization_id: int, user_id: int, device_group_id: int, permission: str): ...
def batch_modify_permission_by_user(organization_id: int, user_id: int, permission: str): ...
def batch_modify_permission_by_device(organization_id: int, device_group_id: int, permission: str): ...
def get_device_list_by_user(organization_id: int, user_id: int): ...
def get_user_list_by_device(organization_id: int, device_group_id: int): ...
def is_org_user(organization_id: int, org_role: str = 'ORG_MEMBER'): ...
def add_user_to_org(user_name: str, org_id: int, org_role: str): ...
