# -*- coding: utf-8 -*-
"""Templates module for AtendentePro library."""

from .manager import (
    TemplateManager,
    ClientTemplate,
    configure_client,
    configure_template_manager,
    get_template_folder,
    get_template_manager,
    load_flow_config,
    load_interview_config,
    load_triage_config,
    load_knowledge_config,
    load_confirmation_config,
    load_onboarding_config,
    load_style_config,
    load_single_reply_config,
    load_access_config,
    FlowConfig,
    InterviewConfig,
    TriageConfig,
    KnowledgeConfig,
    ConfirmationConfig,
    OnboardingConfig,
    StyleConfig,
    AgentStyleConfig,
    SingleReplyConfig,
    AccessConfig,
    AccessFilterConfig,
    ConditionalPromptConfig,
    DataSourceConfig,
    DataSourceColumn,
    DocumentConfig,
)

__all__ = [
    "TemplateManager",
    "ClientTemplate",
    "configure_client",
    "configure_template_manager",
    "get_template_folder",
    "get_template_manager",
    "load_flow_config",
    "load_interview_config",
    "load_triage_config",
    "load_knowledge_config",
    "load_confirmation_config",
    "load_onboarding_config",
    "load_style_config",
    "load_single_reply_config",
    "load_access_config",
    "FlowConfig",
    "InterviewConfig",
    "TriageConfig",
    "KnowledgeConfig",
    "ConfirmationConfig",
    "OnboardingConfig",
    "StyleConfig",
    "AgentStyleConfig",
    "SingleReplyConfig",
    "AccessConfig",
    "AccessFilterConfig",
    "ConditionalPromptConfig",
    "DataSourceConfig",
    "DataSourceColumn",
    "DocumentConfig",
]

