from pathlib import Path
import tempfile
import os

YWH_API = "https://api.yeswehack.com"

NAME_LENGTH = 40
SCOPE_COUNT_THRESHOLD_1 = 3
SCOPE_COUNT_THRESHOLD_2 = 8
REPORT_COUNT_PER_SCOPE_THRESHOLD_1 = 5
REPORT_COUNT_PER_SCOPE_THRESHOLD_2 = 15
TOTAL_REPORT_LAST24H_THRESHOLD_1 = 0
TOTAL_REPORT_LAST24H_THRESHOLD_2 = 5
TOTAL_REPORT_LAST7D_THRESHOLD_1 = 10
TOTAL_REPORT_LAST7D_THRESHOLD_2 = 25
TOTAL_REPORT_LAST1M_THRESHOLD_1 = 15
TOTAL_REPORT_LAST1M_THRESHOLD_2 = 40
HOF_THRESHOLD_1 = 3
HOF_THRESHOLD_2 = 15
CREATION_DATE_THRESHOLD_1 = 15
CREATION_DATE_THRESHOLD_2 = 180
UPDATE_DATE_THRESHOLD_1 = 15
UPDATE_DATE_THRESHOLD_2 = 90
LAST_HACKTIVITY_DATE_THRESHOLD_1 = 7
LAST_HACKTIVITY_DATE_THRESHOLD_2 = 45

YWH_PROGS_FILE = os.path.join(tempfile.gettempdir(), "ywh_programs.json")
YWH_LOCAL_CONFIG = Path(os.path.join(Path.home(), '.config', 'ywh_program_selector'))
YWH_LOCAL_CONFIG_CREDZ = Path(os.path.join(YWH_LOCAL_CONFIG, "credentials"))

DATASOURCE_MAX_AGE = 2
DATE_FORMAT = "%Y-%m-%d"

# Number of parallel workers for API calls
API_PARALLEL_WORKERS = 20
