"""
Shared constants for the application.
"""

from .i18n import _
class ServerPallette:
    """ Color for server"""
    COLOR = [
        "#33FF57",  # Green
        "#F333FF",  # Magenta
        "#3357FF",  # Blue
        "#FF8C33",  # Orange
        "#FF33A1",  # Pink
        "#F3FF33",  # Yellow
        "#33FF8C",  # Mint
        "#FF5733",  # Red-Orange
        "#33FFF3",  # Cyan
        "#A133FF",  # Purple
        "#FF3333",  # Bright Red
        "#33FFDA",  # Aqua
        "#FFB833",  # Amber
        "#8C33FF",  # Violet
        "#33A1FF",  # Sky Blue
        "#33FFB8",  # Spearmint
        "#FFD133",  # Golden Yellow
        "#33FFA5",  # Light Green
        "#C70039",  # Deep Red
        "#00B8FF",  # Electric Blue
    ]

class AppCacheTimeout:
    """ All Cache timeout value"""
    INFO_CACHE_TTL = 60
    XML_CACHE_TTL = 3600 # 1 hour
    DONT_DISPLAY_DISK_USAGE = 50

class AppInfo:
    """Define app data"""
    name = "virtui-manager"
    namecase = "VirtUI Manager"
    version = "1.3.0"

class VmAction:
    """Defines constants for VM action types."""
    START = "start"
    STOP = "stop"
    FORCE_OFF = "force_off"
    PAUSE = "pause"
    RESUME = "resume"
    DELETE = "delete"

class VmStatus:
    """Defines constants for VM status filters."""
    DEFAULT = "default"
    RUNNING = "running"
    PAUSED = "paused"
    PMSUSPENDED = "pmsuspended"
    BLOCKED = "blocked"
    STOPPED = "stopped"
    SELECTED = "selected"

class ButtonLabels:
    """Constants for button labels"""
    ADD = _("Add")
    SAVE = _("Save")
    SAVE_CHANGES = _("Save Changes")
    CREATE_NETWORK = _("Create Network")
    INSTALL = _("Install")
    INFO = _("Info")
    BROWSE = _("Browse")
    START = _("Start")
    SHUTDOWN = _("Shutdown")
    FORCE_OFF = _("Force Off")
    REMOVE = _("Remove")
    PAUSE = _("Pause")
    RESUME = _("Resume")
    CONFIGURE = _("Configure")
    WEB_CONSOLE = _("Web Console")
    CONNECT = _("Connect")
    SNAPSHOT = _("Snapshot")
    RESTORE_SNAPSHOT = _("Restore Snapshot")
    DELETE_SNAPSHOT = _("Del Snapshot")
    DELETE = _("Delete")
    EDIT = _("Edit")
    CUSTOM_URL = _("Custom URL")
    SSH_HELP = _("SSH Help")
    VIEW = _("View")
    HELP = _("Help")
    ADD_POOL = _("Add Pool")
    DELETE_POOL = _("Delete Pool")
    NEW_VOLUME = _("New Volume")
    ATTACH_VOL = _("Attach Vol")
    MOVE_VOLUME = _("Move Volume")
    DELETE_VOLUME = _("Delete Volume")
    EDIT_XML = _("Edit XML")
    EDIT_CPU_TUNE = _("Edit CPU Tune")
    EDIT_NUMA_TUNE = _("Edit NUMA Tune")
    SWITCH_TO_BIOS = _("Switch to BIOS")
    SWITCH_TO_UEFI = _("Switch to UEFI")
    SAVE_BOOT_ORDER = _("Save Boot Order")
    BOOT_ADD = _("<")
    BOOT_REMOVE = _(">")
    BOOT_UP = _("Up")
    BOOT_DOWN = _("Down")
    REMOVE_DISK = _("Remove Disk")
    DISABLE_DISK = _("Disable Disk")
    ENABLE_DISK = _("Enable Disk")
    ADD_DISK = _("Add Disk")
    ATTACH_EXISTING_DISK = _("Attach Existing Disk")
    EDIT_DISK = _("Edit Disk")
    DISK_HELP = _("Help")
    EDIT_INTERFACE = _("Edit Interface")
    ADD_INTERFACE = _("Add Interface")
    REMOVE_INTERFACE = _("Remove Interface")
    DELETE_VIRTIOFS = _("Delete")
    VIRTIOFS_HELP = _("Help")
    APPLY_GRAPHICS_SETTINGS = _("Apply Graphics Settings")
    APPLY_TPM_SETTINGS = _("Apply TPM Settings")
    APPLY_RNG_SETTINGS = _("Apply RNG Settings")
    ADD_PTY_CONSOLE = _("Add PTY Console")
    REMOVE_CONSOLE = _("Remove Console")
    APPLY_WATCHDOG_SETTINGS = _("Apply Watchdog Settings")
    REMOVE_WATCHDOG = _("Remove Watchdog")
    ADD_INPUT = _("Add Input")
    REMOVE_INPUT = _("Remove Input")
    ADD_USB2 = _("Add USB2")
    ADD_USB3 = _("Add USB3")
    ADD_SCSI = _("Add SCSI")
    ATTACH_ARROW = _("Attach >")
    DETACH_ARROW = _("< Detach")
    ADD_CHANNEL = _("Add Channel")
    REMOVE_CHANNEL = _("Remove Channel")
    OTHER_TABS = _("Other Tabs")
    APPLY = _("Apply")
    CLONE = _("! Clone !")
    MIGRATION = _("! Migration !")
    VIEW_XML = _("View XML")
    RENAME = _("Rename")
    SELECT_SERVER = _("[b][#FFD700]S[/][/]elect Servers")
    MANAGE_SERVERS = _("Servers [b][#FFD700]L[/][/]ist")
    SERVER_PREFERENCES = _("Server Prefs")
    FILTER_VM = _("[b][#FFD700]F[/][/]ilter VM")
    VIEW_LOG = _("Log")
    BULK_CMD = _("[b][#FFD700]B[/][/]ulk CMD")
    PATTERN_SELECT = _("[b][#FFD700]P[/][/]attern Sel")
    CONFIG = _("Config")
    PREVIOUS_PAGE = _("Previous Page")
    NEXT_PAGE = _("Next Page")
    YES = _("Yes")
    NO = _("No")
    CANCEL = _("Cancel")
    CREATE = _("Create")
    CHANGE = _("Change")
    STOP = _("Stop")
    CLOSE = _("Close")
    MOVE = _("Move")
    ATTACH = _("Attach")
    DE_ACTIVE = _("De/Active")
    AUTOSTART = _("Autostart")
    EXECUTE = _("Execute")
    DONE = _("Done")
    SEARCH_VMS = _("Search VMs")
    SELECT_MATCHING = _("Select Matching")
    REFRESH = _("Refresh")
    CLEAR_CACHES = _("Clear All Caches")
    CONFIRM = _("Confirm")
    CHECK_COMPATIBILITY = _("Check Compatibility")
    START_MIGRATION = _("Start Migration")
    CREATE_OVERLAY = _("New Overlay")
    COMMIT_DISK = _("Commit Disk")
    DISCARD_OVERLAY = _("Discard Overlay")
    SNAP_OVERLAY_HELP = _("Help")
    COMPACT_VIEW = _("Compact")
    SELECT = _("Select")
    OK = _("OK")


class BindingDescriptions:
    """Descriptions for app bindings"""
    LOG = _("Log")
    FILTER = _("Filter")
    COMPACT_VIEW = _("CompactView")
    SERVER_PREFS = _("ServerPrefs")
    CONFIG = _("Config")
    BULK_CMD = _("BulkCMD")
    SELECT_SERVERS = _("SelServers")
    MANAGE_SERVERS = _("ServList")
    PATTERN_SELECT = _("PatternSel")
    SELECT_ALL = _("Sel/Des All")
    UNSELECT_ALL = _("Unselect All")
    PREVIOUS_PAGE = _("Previous Page")
    NEXT_PAGE = _("Next Page")
    RUNNING_VMS = _("Running VMs")
    ALL_VMS = _("All VMs")
    VIRSH_SHELL = _("Virsh")
    HOST_CAPABILITIES = _("Host Caps")
    INSTALL_VM = _("InstallVM")
    TOGGLE_STATS = _("Log Stats")
    CACHE_STATS = _("Show cache Stats")
    QUIT = _("Quit")
    HOST_DASHBOARD = _("Host Dashboard")


class TabTitles:
    """Constants for tab titles"""
    MANAGE = _("Manage")
    OTHER = _("Other")
    SNAPSHOT = _("Snapshot")
    SNAPSHOTS = _("Snapshots")
    OVERLAY = _("Overlay")
    SNAP_OVER_UPDATE = _("Updating Data...")
    ACTIVE_ALLOCATION = _("Active Allocation")
    TOTAL_ALLOCATION = _("Total Allocation")

class StatusText:
    """Constants for status text"""
    STOPPED = _("Stopped")
    RUNNING = _("Running")
    PAUSED = _("Paused")
    PMSUSPENDED = _("PMSuspended")
    BLOCKED = _("Blocked")
    LOADING = _("Loading")
    UNKNOWN = _("Unknown")


class StaticText:
    """Constants for static text in modals"""
    CACHE_PERFORMANCE_STATISTICS = _("Cache Performance Statistics")
    EDITING_CONFIG_PATH = _("(Editing: {get_user_config_path})")
    CUSTOM_MIGRATION_PLAN = _("[bold]Custom Migration Plan[/bold]")
    DISK_VOLUME_NAME = _("Disk: [b]{volume_name}[/b]")
    SOURCE_POOL = _("  Source Pool: {source_pool}")
    NO_DESTINATION_POOLS = _("  No destination pools available.")
    DISK_PATH = _("Disk: [b]{disk_path}[/b]")
    ACTION_MESSAGE = _("  Action: {message}")
    FROM_POOL = _("From Pool: {source_pool_name}")
    SELECT_DESTINATION_SERVER = _("Select destination server:")
    MIGRATION_OPTIONS = _("Migration Options:")
    COMPATIBILITY_CHECK_RESULTS = _("Compatibility Check Results / Migration Log:")
    VMS_READY_FOR_MIGRATION = _("[b]VMs [green]Ready[/] for Migration[/b]")
    VMS_NOT_READY_FOR_MIGRATION = _("[b]VMs [red]Not[/] Ready for Migration[/b]")
    DELETE_ASSOCIATED_STORAGE = _("Delete associated storage")
    CREATE_NEW_DISK_IMAGE = _("Create new disk image")
    CD_ROM = _("CD-ROM")
    COPY_STORAGE_ALL = _("Copy storage all")
    UNSAFE_MIGRATION = _("Unsafe migration")
    PERSISTENT_MIGRATION = _("Persistent migration")
    COMPRESS_DATA = _("Compress data")
    TUNNELLED_MIGRATION = _("Tunnelled migration")
    CUSTOM_MIGRATION = _("Custom migration")
    ENABLE_REMOTE_WEBCONSOLE = _("Enable remote web console")
    ENABLE_DHCPV4 = _("Enable DHCPv4")
    VALIDATE_CHECKSUM = _("Validate Checksum")
    UEFI = _("UEFI")
    CONFIGURE_BEFORE_INSTALL = _("Configure before install")
    INSTALL_OPENSUSE_VM = _("Install OpenSUSE VM on {uri}")
    VM_NAME = _("VM Name:")
    VM_TYPE = _("VM Type:")
    DISTRIBUTION = _("Distribution:")
    ISO_IMAGE_REPO = _("ISO Image (Repo):")
    ISOS_DOWNLOAD_PATH = _("ISOs will be downloaded to: {iso_path}")
    CUSTOM_ISO_LOCAL_PATH = _("Custom ISO (Local Path):")
    SELECT_STORAGE_POOL = _("Select Storage Pool:")
    SELECT_ISO_VOLUME = _("Select ISO Volume:")
    STORAGE_POOL = _("Storage Pool:")
    MEMORY_GB_LABEL = _(" Memory (GB)")
    CPUS_LABEL = _(" CPUs")
    DISK_SIZE_GB_LABEL = _(" Disk Size(GB)")
    DISK_FORMAT_LABEL = _(" Disk Format")
    FIRMWARE_LABEL = _(" Firmware")
    DELETE_STORAGE_VOLUMES = _("Delete storage volumes")
    QUIESCE_GUEST = _("Quiesce guest (requires agent)")
    SELECT_INTERFACE_AND_NETWORK = _("Select interface and new network")
    ENTER_BASE_NAME = _("Enter base name for new VM(s)")
    SUFFIX_FOR_CLONE_NAMES = _("Suffix for clone names (e.g., _C)")
    NUMBER_OF_CLONES_TO_CREATE = _("Number of clones to create")
    DO_NOT_CLONE_STORAGE = _("Do Not Clone storage")
    CURRENT_NAME = _("Current name: {current_name}")
    ENTER_NEW_VM_NAME = _("Enter new VM name")
    CURRENT_TIME = _("Current time: {now}")
    ENTER_SNAPSHOT_NAME = _("Enter snapshot name")
    DESCRIPTION_OPTIONAL = _("Description (optional)")
    WEB_CONSOLE_CONFIGURATION = _("Web Console Configuration")
    REMOTE = _("Remote")
    ENTER_QEMU_CONNECTION_URI = _("Enter QEMU Connection URI:")
    ADD_NEW_SERVER = _("Add New Server")
    AUTOCONNECT_AT_STARTUP = _("Autoconnect at startup")
    EDIT_SERVER = _("Edit Server")
    SERVER_LIST_MANAGEMENT = _("Server List Management")
    SELECT_SERVERS_TO_DISPLAY = _("Select Servers to Display")
    ENTER_NEW_VCPU_COUNT = _("Enter new VCPU count")
    ENTER_NEW_MEMORY_SIZE = _("Enter new memory size (MB)")
    SELECT_MACHINE_TYPE = _("Select Machine Type:")
    CPU_PINNING_FORMAT = _("Format: 0:0-3; 1:4-7")
    NUMA_MEMORY_MODE = _("NUMA Memory Mode")
    NODESET = _("Nodeset")
    ENTER_CPU_PINNING = _("Enter CPU Pinning (max vcpu: {max_vcpus})")
    SELECT_VMS_BY_PATTERN = _("Select VMs by Pattern (ctrl+u to unselect All VMS)")
    REGEX = _("Regex")
    MATCHING_VMS = _("Matching VMs:")
    FILTER_BY_NAME = _("Filter by Name")
    ALL = _("All")
    RUNNING = _("Running")
    PAUSED = _("Paused")
    PMSUSPENDED = _("PMSuspended")
    BLOCKED = _("Blocked")
    STOPPED = _("Stopped")
    MANUALLY_SELECTED = _("Manually Selected")
    CREATE_NEW_VM = _("Create New VM")
    START_VMS = _("Start VMs")
    STOP_VMS_GRACEFUL = _("Stop VMs (Graceful Shutdown)")
    FORCE_OFF_VMS = _("Force Off VMs")
    PAUSE_VMS = _("Pause VMs")
    DELETE_VMS = _("Delete VMs")
    EDIT_CONFIGURATION = _("Edit Configuration")
    HYPERVISOR_DEFAULT = _("Hypervisor default")
    LOCALHOST_ONLY = _("Localhost only")
    ALL_INTERFACES = _("All interfaces")
    NAT_NETWORK = _("NAT Network")
    ROUTED_NETWORK = _("Routed Network")
    IPV4_NETWORK_EXAMPLE = _("e.g., 192.168.1.0/24")
    DHCP_START_EXAMPLE = _("e.g., 192.168.1.10")
    DHCP_END_EXAMPLE = _("e.g., 192.168.1.200")
    SELECT_NETWORK_AND_MODEL = _("Select Network and Model")
    USE_CUSTOM_DNS_DOMAIN = _("Use Custom DNS Domain")
    USE_NETWORK_NAME_FOR_DNS = _("Use Network Name for DNS")
    CUSTOM_DNS_DOMAIN = _("Custom DNS Domain")
    NETWORK_DETAILS = _("Network Details")
    UNDEFINE_SOURCE_VM = _("Undefine source VM")
    EDIT_DISK_TITLE = _("Edit Disk: {path}")
    MOVE_VOLUME_TITLE = _("Move Volume: {volume_name}")
    MIGRATE_VMS_TITLE = _("[{migration_type}] Migrate VMs: [b]{vm_names}[/b]")
    EMPTY_LABEL = ""
    SERVER_PREFERENCES = _("Server Preferences")
    SELECT_DIRECTORY = _("Select a Directory")
    SELECT_FILE = _("Select a File")
    SELECT_DISK_TO_REMOVE = _("Select Disk to Remove")
    ADD_NEW_DISK = _("Add New Disk")
    ADD_NEW_STORAGE_POOL = _("Add New Storage Pool")
    TARGET_PATH_VOLUMES = _("Target Path (for volumes)")
    TARGET_PATH_HOST = _("Target Path (on this host)")
    SOURCE_HOSTNAME = _("Source Hostname")
    SOURCE_PATH_REMOTE = _("Source Path (on remote host)")
    CREATE_NEW_STORAGE_VOLUME = _("Create New Storage Volume")
    DEVICE_TYPE = _("Device Type:")
    BUS_TYPE = _("Bus Type:")
    CACHE_MODE = _("Cache Mode:")
    DISCARD_MODE = _("Discard Mode:")
    VM_MUST_BE_STOPPED_EDIT_DISK = _("VM must be stopped to edit disk settings.")
    DESTINATION_POOL = _("Destination Pool:")
    NEW_VOLUME_NAME = _("New Volume Name:")
    ATTACH_EXISTING_DISK_AS_VOLUME = _("Attach Existing Disk as Volume")
    BOOT_ORDER = _("Boot Order")
    AVAILABLE_DEVICES = _("Available Devices")
    TYPE_LABEL = _("Type:")
    LISTEN_TYPE = _("Listen Type:")
    ADDRESS_LABEL = _("Address:")
    TPM_MODEL = _("TPM Model:")
    TPM_TYPE = _("TPM Type:")
    DEVICE_PATH_PASSTHROUGH = _("Device Path (for passthrough):")
    BACKEND_TYPE_PASSTHROUGH = _("Backend Type (for passthrough):")
    BACKEND_PATH_PASSTHROUGH = _("Backend Path (for passthrough):")
    HOST_DEVICE = _("Host device")
    WATCHDOG_MODEL = _("Watchdog Model:")
    ACTION_LABEL = _("Action:")
    AVAILABLE_HOST_USB = _("Available Host USB Devices")
    ATTACHED_TO_VM = _("Attached to VM")
    AVAILABLE_HOST_PCI = _("Available Host PCI Devices")
    VIRSH_SHELL_TITLE = _("Virsh Interactive Shell (esc to quit)")
    VIRSH_SHELL_NOTE = _("Note: This shell starts a new `virsh` process, which may require re-authentication for remote connections. Using SSH keys is recommended.")
    INPUT_DEVICE = _("Input Device")
    ADD_CHANNEL_DEVICE = _("Add Channel Device")
    STANDARD_TARGET_NAMES = _("Standard Target Names:")
    TARGET_NAME = _("Target Name:")
    SELECTED_VMS_BULK = _("Selected VMs for Bulk Action")
    CHOOSE_ACTION = _("Choose Action:")
    PERFORMANCE = _("Performance")
    STATS_INTERVAL = _("Stats Interval (seconds):")
    LOG_FILE_PATH = _("Log File Path:")
    LOGGING_LEVEL = _("Logging Level:")
    REMOTE_VIEWER = _("Remote Viewer")
    NO_REMOTE_VIEWERS_FOUND = _("No remote viewers found (virt-viewer or virtui-remote-viewer)")
    WEBSOCKIFY_PATH = _("Websockify Path:")
    NOVNC_PATH = _("noVNC Path:")
    WEBSOCKIFY_PORT_RANGE = _("Websockify Port Range:")
    VNC_QUALITY = _("VNC Quality (0-9):")
    VNC_COMPRESSION = _("VNC Compression (0-9):")
    HOST_CAPABILITIES = _("Host Capabilities")
    CAPABILITIES_TREE_LABEL = _("Capabilities")
    SELECT_A_DIRECTORY = _("Select a Directory")
    SELECT_A_FILE = _("Select a File")
    EXPORT_READONLY_MOUNT = _("Export filesystem as readonly mount")
    WEBCONSOLE_LOCAL_RUN = _("Web console will run locally.")
    ENABLE_BOOT_MENU = _("Enable boot menu")
    WEB_CONSOLE_NOVNC = _("Web Console (novnc)")
    HOST_RESOURCE_DASHBOARD = _("Host Resource Dashboard")
    HOST_DETAILS = _("Host Details")
    VM_ALLOCATION = _("VM Allocation")
    CPU_USAGE = _("CPU Usage")
    MEMORY_USAGE = _("Memory Usage")
    ALLOCATED_VCPUS = _("Allocated VCPUs")
    ALLOCATED_MEMORY = _("Allocated Memory")
    ACTIVE_ALLOCATION = _("Active Allocation")
    TOTAL_ALLOCATION = _("Total Allocation")
    MODEL = _("Model:")
    TOPOLOGY = _("Topology:")
    WAITING_TO_START_COLLECTION = _("Waiting to start collection...")
    COLLECTING_VM_INFO = _("Collecting VM info: {current}/{total}")

class SparklineLabels:
    """Constants for sparkline labels"""
    DISK_RW = _("Disk R/W {read:.2f}/{write:.2f} MB/s")
    NET_RX_TX = _("Net Rx/Tx {rx:.2f}/{tx:.2f} MB/s")
    VCPU = _("{cpu} VCPU")
    MEMORY_GB = _("{mem} Gb")

class ErrorMessages:
    """Constants for error messages"""
    R_VIEWER_NOT_FOUND = _("Remote viewer command not found. Please ensure it is installed.")
    CANNOT_OPEN_DISPLAY = _("Could not open display. Ensure you are in a graphical session.")
    HARD_STOP_WARNING = _("This is a hard stop, like unplugging the power cord.")
    MIGRATION_LOCALHOST_NOT_SUPPORTED = _("Migration from localhost (qemu:///system) is not supported.\nA full remote URI (e.g., qemu+ssh://user@host/system) is required.")
    NO_DESTINATION_SERVERS = _("No destination servers available.")
    DIFFERENT_SOURCE_HOSTS = _("Cannot migrate VMs from different source hosts at the same time.")
    MIXED_VM_STATES = _("Cannot migrate running/paused and stopped VMs at the same time.")
    WEBSOCKIFY_NOT_FOUND = _("websockify is not installed. 'Web Console' button will be disabled.")
    NOVNC_NOT_FOUND = _("novnc is not installed. 'Web Console' button will be disabled.")
    FAILED_TO_OPEN_CONNECTION = _("Failed to open connection to [b]{uri}[/b]")
    NOT_CONNECTED_TO_ANY_SERVER = _("Not connected to any server.")
    COULD_NOT_CONNECT_TO_SERVER = _("Could not connect to {uri}")
    NO_ACTION_TYPE_BULK_MODAL = _("No action type received from bulk action modal.")
    VM_NOT_FOUND_FOR_EDITING = _("Could not find any of the selected VMs for editing.")
    VMS_MUST_BE_STOPPED_FOR_BULK_EDITING = _("All VMs must be stopped for bulk editing. Running VMs: {running_vms}")
    COULD_NOT_LOAD_DETAILS_FOR_REFERENCE_VM = _("Could not load details for reference VM.")
    SERVER_DISCONNECTED_AUTOCONNECT_DISABLED = _("Server(s) {names} disconnected and autoconnect disabled due to connection failures.")
    NO_ACTIVE_SERVERS = _("No active servers.")
    NO_VMS_IN_CACHE = _("No VMs found in cache. Try refreshing first.")
    NO_VMS_SELECTED = _("No VMs selected.")
    ERROR_FETCHING_VM_DATA = _("Error fetching VM data: {error}")
    ERROR_DURING_INITIAL_CACHE_LOADING = _("Error during initial cache loading: {error}")
    ERROR_ON_VM_DURING_ACTION = _("Error on VM [b]{vm_name}[/b] during '{action}': {error}")
    FATAL_ERROR_BULK_ACTION = _("A fatal error occurred during bulk action: {error}")
    VM_INFO_ERROR = _("Error getting info for VM '{vm_name}': {error}")
    VM_NOT_FOUND_BY_ID = _("Could not find VM with ID [b]{vm_id}[/b]")
    BULK_EDIT_PREP_ERROR = _("Error preparing bulk edit: {error}")
    SERVER_CONNECTION_ERROR = _("Server [b]{server_name}[/b]: {error_msg}")
    SERVER_FAILED_TO_CONNECT = _("Failed to connect to [b]{server_name}[/b]: {error_msg}")
    BULK_ACTION_FAILED_TEMPLATE = _("Bulk action [b]{action_type}[/b] failed for {count} VMs.")
    PREFERENCES_LAUNCH_ERROR = _("Error launching preferences: {error}")
    BULK_ACTION_VM_NAMES_RETRIEVAL_FAILED = _("Could not retrieve names for selected VMs.")
    VM_CLONE_FAILED_TEMPLATE = _("Failed to clone to: {vm_names}")
    NO_SUITABLE_DISKS_FOR_OVERLAY = _("No suitable disks found for overlay.")
    OVERLAY_NAME_EMPTY_AFTER_SANITIZATION = _("Overlay volume name cannot be empty after sanitization.")
    ERROR_CREATING_OVERLAY_TEMPLATE = _("Error creating overlay: {error}")
    ERROR_PREPARING_OVERLAY_CREATION_TEMPLATE = _("Error preparing overlay creation: {error}")
    NO_OVERLAY_DISKS_FOUND = _("No overlay disks found.")
    ERROR_DISCARDING_OVERLAY_TEMPLATE = _("Error discarding overlay: {error}")
    ERROR_PREPARING_DISCARD_OVERLAY_TEMPLATE = _("Error preparing discard overlay: {error}")
    NO_DISKS_FOUND_TO_COMMIT = _("No disks found to commit.")
    ERROR_COMMITTING_DISK_TEMPLATE = _("Error committing disk: {error}")
    ERROR_PREPARING_COMMIT_TEMPLATE = _("Error preparing commit: {error}")
    INVALID_XML_TEMPLATE = _("Invalid XML for '[b]{vm_name}[/b]': {error}. Your changes have been discarded.")
    ERROR_GETTING_XML_TEMPLATE = _("Error getting XML for VM [b]{vm_name}[/b]: {error}")
    UNEXPECTED_ERROR_OCCURRED_TEMPLATE = _("An unexpected error occurred: {error}")
    CONNECTION_INFO_NOT_AVAILABLE = _("Connection info not available for this VM.")
    REMOTE_VIEWER_FAILED_TO_START_TEMPLATE = _("{viewer} failed to start for {domain_name}: {error}")
    ERROR_GETTING_VM_DETAILS_TEMPLATE = _("Error getting VM details for [b]{vm_name}[/b]: {error}")
    UNEXPECTED_ERROR_CONNECTING = _("An unexpected error occurred while trying to connect.")
    ERROR_CHECKING_WEB_CONSOLE_STATUS_TEMPLATE = _("Error checking web console status for [b]{vm_name}[/b]: {error}")
    SNAPSHOT_ERROR_TEMPLATE = _("Snapshot error for [b]{vm_name}[/b]: {error}")
    NO_SNAPSHOTS_TO_RESTORE = _("No snapshots to restore.")
    ERROR_FETCHING_SNAPSHOTS_TEMPLATE = _("Error fetching snapshots: {error}")
    NO_SNAPSHOTS_TO_DELETE = _("No snapshots to delete.")
    ERROR_DELETING_VM_TEMPLATE = _("Error deleting VM '{vm_name}': {error}")
    VM_NAME_EMPTY_AFTER_SANITIZATION = _("VM name cannot be empty after sanitization.")
    ERROR_RENAMING_VM_TEMPLATE = _("Error renaming VM [b]{vm_name}[/b]: {error}")
    VM_NOT_FOUND_ON_ACTIVE_SERVER_TEMPLATE = _("VM [b]{vm_name}[/b] with internal ID [b]{uuid}[/b] not found on any active server.")
    ERROR_GETTING_ID_TEMPLATE = _("Error getting ID for [b]{vm_name}[/b]: {error}")
    SELECT_AT_LEAST_TWO_SERVERS_FOR_MIGRATION = _("Please select at least two servers in 'Select Servers' to enable migration.")
    SELECTED_VM_NOT_FOUND_ON_ACTIVE_SERVER_TEMPLATE = _("Selected VM with ID [b]{uuid}[/b] not found on any active server.")
    ERROR_GETTING_EXISTING_VM_NAMES_TEMPLATE = _("Error getting existing VM names: {error}")
    WEBCONSOLE_VNC_ONLY = _("Web console only supports VNC graphics.")
    COULD_NOT_DETERMINE_VNC_PORT = _("Could not determine VNC port for the VM.")
    FAILED_TO_START_WEBCONSOLE_TEMPLATE = _("Failed to start web console: {error}")
    NO_FREE_WEBCONSOLE_PORT = _("Could not find a free port for the web console (all ports in range used by other sessions).")
    REMOTE_KEY_GENERATION_FAILED = _("Remote key generation failed. Falling back to insecure ws connection.")
    FAILED_TO_START_REMOTE_WEBSOCKIFY_TEMPLATE = _("Failed to start remote websockify for [b]{vm_name}[/b]. Check logs.")
    REMOTE_WEBCONSOLE_CRASHED_TEMPLATE = _("Remote web console process for [b]{vm_name}[/b] failed to start or crashed. Check remote logs.")
    NO_FREE_LOCAL_PORT_FOR_SSH_TUNNEL = _("Could not find a free local port for SSH tunnel.")
    FAILED_TO_CREATE_SSH_TUNNEL_TEMPLATE = _("Failed to create SSH tunnel: {error}")
    SSH_COMMAND_NOT_FOUND = _("SSH command not found. Cannot create tunnel.")
    FAILED_TO_CREATE_SSH_TUNNEL_GENERIC = _("Failed to create SSH tunnel...")
    PLEASE_SELECT_ACTION = _("Please select an action.")
    ERROR_SAVING_CONFIGURATION_TEMPLATE = _("Error saving configuration: {e}")
    VALIDATION_ERROR_TEMPLATE = _("Validation error: {error}")
    INVALID_FORMAT_TEMPLATE = _("Invalid format: {error}")
    INVALID_NODESET_SYNTAX_TEMPLATE = _("Invalid nodeset syntax: {nodeset}")
    CREATE_DISK_REQUIRED_FIELDS = _("Pool, Volume Name, and Size are required to create a new disk.")
    DISK_IMAGE_PATH_REQUIRED = _("Path to disk image is required.")
    POOL_NAME_REQUIRED = _("Pool name is required.")
    TARGET_PATH_REQUIRED_FOR_DIR = _("Target Path is required for `dir` type.")
    NETFS_FIELDS_REQUIRED = _("For `netfs`, all fields are required.")
    NAME_AND_SIZE_REQUIRED = _("Name and size are required.")
    SIZE_MUST_BE_INTEGER = _("Size must be an integer.")
    DEST_POOL_AND_NAME_REQUIRED = _("Destination pool and new name are required.")
    NAME_PATH_FORMAT_REQUIRED = _("Name, path, and format are required. Ensure a file is selected.")
    ERROR_CREATING_STORAGE_POOL_TEMPLATE = _("Error creating storage pool: {error}")
    SELECT_DESTINATION_SERVER = _("Please select a destination server.")
    RUN_COMPATIBILITY_CHECK_FIRST = _("Please run compatibility check first.")
    MIGRATION_COMPATIBILITY_ERRORS = _("Cannot start migration due to compatibility errors.")
    NETWORK_NOT_FOUND_TEMPLATE = _("Network '{network}' not found. Please select an available network.")
    SELECT_NETWORK = _("Please select a network.")
    FORWARD_DEVICE_NOT_FOUND_TEMPLATE = _("Forward device '{device}' not found on host.")
    ERROR_GETTING_HOST_INTERFACES_TEMPLATE = _("Error getting host interfaces: {error}")
    INVALID_NETWORK_NAME_TEMPLATE = _("Invalid Network Name: {error}")
    INVALID_CUSTOM_DNS_DOMAIN_TEMPLATE = _("Invalid Custom DNS Domain: {error}")
    NETWORK_NAME_REQUIRED = _("Network Name cannot be empty.")
    DHCP_IPS_NOT_IN_NETWORK_TEMPLATE = _("DHCP IPs are not in the network {network}")
    DHCP_START_BEFORE_END = _("DHCP start IP must be before the end IP.")
    INVALID_IP_OR_NETWORK_TEMPLATE = _("Invalid IP address or network: {error}")
    DHCP_REQUIRES_IP = _("DHCP cannot be enabled without an IP network.")
    SUBNET_OVERLAPS_TEMPLATE = _("Subnet {subnet} overlaps with an existing network.")
    ERROR_CREATING_NETWORK_TEMPLATE = _("Error creating network: {error}")
    ERROR_UPDATING_NETWORK_TEMPLATE = _("Error updating network: {error}")
    NETWORK_NOT_FOUND_TEMPLATE_2 = _("Network '{network}' not found. Please select an available network.")
    VM_NAME_ALREADY_EXISTS_TEMPLATE = _("A VM with the name '{vm_name}' already exists. Please choose a different name.")
    ERROR_CHECKING_VM_NAME_TEMPLATE = _("Error checking VM name: {error}")
    PLEASE_SELECT_VALID_STORAGE_POOL = _("Please select a valid storage pool.")
    ISO_VOLUME_NOT_FOUND_TEMPLATE = _("Selected ISO volume does not exist: {iso_url}")
    SELECT_VALID_ISO_VOLUME = _("Please select a valid ISO volume from the storage pool.")
    INVALID_EXPERT_SETTINGS = _("Invalid input for expert settings. Using defaults.")
    MEMORY_RANGE_ERROR = _("Memory must be between 1 and 8192 GB.")
    CPU_RANGE_ERROR = _("CPU count must be between 1 and 768.")
    DISK_SIZE_RANGE_ERROR = _("Disk size must be between 1 and 10000 GB.")
    STORAGE_POOL_NOT_ACTIVE_TEMPLATE = _("Storage pool '{pool_name}' is not active. Please activate it first.")
    ERROR_ACCESSING_STORAGE_POOL_TEMPLATE = _("Error accessing storage pool '{pool_name}': {error}")
    CUSTOM_ISO_PATH_NOT_EXIST_TEMPLATE = _("Custom ISO path does not exist: {path}")
    CUSTOM_ISO_NOT_FILE_TEMPLATE = _("Custom ISO path is not a file: {path}")
    CHECKSUM_MISSING = _("Checksum validation enabled but no checksum provided")
    CHECKSUM_VALIDATION_FAILED = _("Checksum validation failed!")
    NO_ISO_URL_SPECIFIED = _("No ISO URL specified for provisioning")
    COULD_NOT_GET_VM_DETAILS_TEMPLATE = _("Could not get details for {vm_name}")
    FAILED_TO_START_VM_OR_VIEWER_TEMPLATE = _("Failed to start VM or viewer: {error}")
    PROVISIONING_FAILED_TEMPLATE = _("Provisioning failed: {error}")
    FAILED_TO_FETCH_ISO_VOLUMES_TEMPLATE = _("Failed to fetch ISO volumes from {pool_name}: {error}")
    FAILED_TO_FETCH_ISOS_TEMPLATE = _("Failed to fetch ISOs: {error}")
    VM_NAME_CANNOT_BE_EMPTY = _("VM name cannot be empty.")
    CONNECTING_TO_SERVER_TEMPLATE = _("Connecting to {uri}...")
    FAILED_TO_CONNECT_TO_SERVER_TEMPLATE = _("Failed to connect to {uri}")
    ERROR_DELETING_SERVER_TEMPLATE = _("Error deleting server '{server_name}': {error}")
    DELETE_SERVER_CONFIRMATION_TEMPLATE = _("Are you sure you want to delete Server;\n'{server_name}'\nfrom list?")
    NOT_CONNECTED_TO_ANY_SERVER_PREFS = _("Not connected to any server.")
    MULTIPLE_SERVERS_ACTIVE_NONE_SELECTED = _("Multiple servers active but none selected for preferences.")
    FAILED_TO_GET_CONNECTION_PREFS_TEMPLATE = _("Failed to get connection for server preferences on {uri}.")
    COULD_NOT_FIND_OBJECT_XML = _("Could not find object to display XML for.")
    ERROR_GETTING_XML_FOR_TYPE_TEMPLATE = _("Error getting XML for {obj_type}: {error}")
    COULD_NOT_FIND_POOL_EDIT = _("Could not find pool object to edit.")
    POOL_MUST_BE_INACTIVE_FOR_XML_EDIT = _("Pool must be inactive to edit its XML definition.")
    ERROR_GETTING_XML_FOR_POOL_TEMPLATE = _("Error getting XML for pool: {error}")
    STORAGE_POOL_UPDATED_SUCCESSFULLY_TEMPLATE = _("Storage pool '{pool_name}' updated successfully.")
    ERROR_UPDATING_POOL_XML_TEMPLATE = _("Error updating pool XML: {error}")
    UNEXPECTED_ERROR_OCCURRED_TEMPLATE_XML = _("An unexpected error occurred: {error}")
    EDIT_POOL_XML_WARNING = _("Editing a pool's XML definition is an advanced operation.\n"
                             "An invalid configuration may make its volumes inaccessible to VMs.\n\n"
                             "Are you sure you want to proceed?")
    ERROR_TOGGLE_POOL_ACTIVE_TEMPLATE = _("Error toggling pool active state: {error}")
    ERROR_TOGGLE_POOL_AUTOSTART_TEMPLATE = _("Error toggling pool autostart state: {error}")
    VOLUME_CREATED_SUCCESSFULLY_TEMPLATE = _("Volume [b]{name} {size_gb}Gb {format}[/b] created successfully.")
    INVALID_OR_NON_EXISTENT_PATH_TEMPLATE = _("Invalid or non-existent path: {path}")
    ERROR_REFRESHING_POOL_TEMPLATE = _("Error refreshing pool: {error}")
    POOL_ALREADY_MANAGES_DIRECTORY_TEMPLATE = _("A pool named '{pool_name}' already manages this directory.\n"
                                               "Refreshed pool to include the new volume.")
    NO_POOL_FOR_DIRECTORY_CONFIRM_TEMPLATE = _("No storage pool exists for the directory:\n'{directory}'.\n\n"
                                              "Create a new pool named '{pool_name}'?")
    ERROR_CREATING_STORAGE_POOL_FOR_DIR_TEMPLATE = _("Error creating storage pool: {error}")
    COULD_NOT_DETERMINE_SOURCE_POOL = _("Could not determine the source pool.")
    VOLUME_MOVED_SUCCESSFULLY_TEMPLATE = _("Volume '{volume_name}' moved to pool '{dest_pool_name}'.")
    UPDATED_VM_CONFIGURATIONS_TEMPLATE = _("Updated VM configurations for: {vm_list}")
    MOVE_OPERATION_FAILED_TEMPLATE = _("Move operation failed: {error}")
    ERROR_GETTING_NETWORK_XML_TEMPLATE = _("Error getting network XML: {error}")
    COULD_NOT_RETRIEVE_NETWORK_INFO_TEMPLATE = _("Could not retrieve info for network '{network_name}'.")
    NETWORK_DELETED_SUCCESSFULLY_TEMPLATE = _("Network '{network_name}' deleted successfully.")
    ERROR_DELETING_NETWORK_TEMPLATE = _("Error deleting network '{network_name}': {error}")
    DELETE_NETWORK_CONFIRM_TEMPLATE = _("Are you sure you want to delete network:\n'{network_name}'")
    NETWORK_IN_USE_WARNING_TEMPLATE = _("\nThis network is currently in use by the following VMs:\n{vm_list}.")
    NOT_CONNECTED_TO_LIBVIRT = _("Not connected to libvirt.")
    POOL_IS_NOT_ACTIVE = _("Pool is not active")
    STORAGE_POOL_DELETED_SUCCESSFULLY_TEMPLATE = _("Storage pool '{pool_name}' deleted successfully.")
    DELETE_STORAGE_POOL_CONFIRMATION_TEMPLATE = _("Are you sure you want to delete storage pool:\n' {pool_name}'\nThis will delete the pool definition but not the data on it.")
    VOLUME_DELETED_SUCCESSFULLY_TEMPLATE = _("Volume '{volume_name}' deleted successfully.")
    DELETE_VOLUME_CONFIRMATION_TEMPLATE = _("Are you sure you want to delete volume:\n'{vol_name}'")
    VIRTIOFS_PATH_EMPTY = _("Source Path and Target Path cannot be empty.")
    SANITIZATION_ERROR_TEMPLATE = _("{error}")
    PLEASE_SELECT_INTERFACE_AND_NETWORK = _("Please select an interface and a network.")
    BASE_NAME_EMPTY = _("Base name cannot be empty.")
    INVALID_CHARS_IN_SUFFIX = _("Invalid characters in suffix: {error}")
    CLONE_COUNT_POSITIVE_INTEGER = _("Number of clones must be a positive integer.")
    SUFFIX_MANDATORY_FOR_MULTIPLE_CLONES = _("Suffix is mandatory when creating multiple clones.")
    VM_NAME_CANNOT_BE_EMPTY_RENAME = _("VM name cannot be empty.")
    SNAPSHOT_NAME_CANNOT_BE_EMPTY = _("Snapshot name cannot be empty.")
    QEMU_GUEST_AGENT_RECOMMENDATION = _("QEMU Guest Agent not detected. It is recommended to pause the VM before taking a snapshot.")
    VM_DETAIL_COULD_NOT_LOAD_NETWORKS = _("Could not load networks: {error}")
    CANNOT_ENABLE_SECURE_BOOT_WITHOUT_UEFI = _("Cannot enable secure boot without a UEFI file selected.")
    ERROR_UPDATING_NETWORK_TEMPLATE_SHORT = _("Error updating network: {error}")
    GRAPHICS_VM_MUST_BE_STOPPED = _("VM must be stopped to apply graphics settings.")
    RNG_VM_MUST_BE_STOPPED = _("VM must be stopped to apply RNG settings.")
    RNG_DEVICE_PATH_EMPTY = _("RNG device path cannot be empty.")
    TPM_VM_MUST_BE_STOPPED = _("VM must be stopped to apply TPM settings.")
    DEVICE_PATH_REQUIRED_FOR_PASSTHROUGH_TPM = _("Device path is required for passthrough TPM.")
    PCI_PASSTHROUGH_NOT_IMPLEMENTED = _("PCI passthrough not implemented yet.")
    ADD_CHANNEL_NO_TARGET_NAME = _("Selected channel has no target name.")
    ERROR_ADDING_CHANNEL_TEMPLATE = _("Error adding channel: {error}")
    ERROR_REMOVING_CHANNEL_TEMPLATE = _("Error removing channel: {error}")
    VM_NOT_FOUND_FOR_DETAILS_TEMPLATE = _("VM '{vm_name}' not found for details.")
    COULD_NOT_GET_VM_XML_TEMPLATE = _("Could not get XML for VM '{vm_name}': {error}")
    CPU_MUST_BE_STOPPED_TO_EDIT = _("VM must be stopped to edit CPU settings.")
    MEMORY_MUST_BE_STOPPED_TO_EDIT = _("VM must be stopped to edit memory settings.")
    MACHINE_TYPE_MUST_BE_STOPPED_TO_EDIT = _("VM must be stopped to change machine type.")
    SHARED_MEMORY_MUST_BE_STOPPED_TO_EDIT = _("VM must be stopped to change shared memory settings.")
    FIRMWARE_VM_MUST_BE_STOPPED_TO_EDIT = _("VM must be stopped to change firmware settings.")
    BOOT_ORDER_VM_MUST_BE_STOPPED_TO_EDIT = _("VM must be stopped to edit boot order.")
    DISK_VM_MUST_BE_STOPPED_TO_EDIT = _("VM must be stopped to edit disk settings.")
    NETWORK_VM_MUST_BE_STOPPED_TO_EDIT = _("VM must be stopped to edit network settings.")
    VIRTIOFS_VM_MUST_BE_STOPPED_TO_EDIT = _("VM must be stopped to edit VirtIO-FS settings.")
    VIDEO_VM_MUST_BE_STOPPED_TO_EDIT = _("VM must be stopped to edit video settings.")
    SOUND_VM_MUST_BE_STOPPED_TO_EDIT = _("VM must be stopped to edit sound settings.")
    GRAPHICS_VM_MUST_BE_STOPPED_TO_EDIT = _("VM must be stopped to edit graphics settings.")
    TPM_VM_MUST_BE_STOPPED_TO_EDIT = _("VM must be stopped to edit TPM settings.")
    RNG_VM_MUST_BE_STOPPED_TO_EDIT = _("VM must be stopped to edit RNG settings.")
    SERIAL_VM_MUST_BE_STOPPED_TO_EDIT = _("VM must be stopped to edit serial settings.")
    WATCHDOG_VM_MUST_BE_STOPPED_TO_EDIT = _("VM must be stopped to edit watchdog settings.")
    PCI_VM_MUST_BE_STOPPED_TO_EDIT = _("VM must be stopped to edit PCI settings.")
    USB_VM_MUST_BE_STOPPED_TO_EDIT = _("VM must be stopped to edit USB settings.")
    CONTROLLER_VM_MUST_BE_STOPPED_TO_EDIT = _("VM must be stopped to edit controller settings.")
    CHANNEL_VM_MUST_BE_STOPPED_TO_EDIT = _("VM must be stopped to edit channel settings.")
    INPUT_VM_MUST_BE_STOPPED_TO_EDIT = _("VM must be stopped to edit input settings.")
    ERROR_TOGGLE_DISK_TEMPLATE = _("Error toggling disk state: {error}")
    ERROR_REMOVING_DISK_TEMPLATE = _("Error removing disk: {error}")
    ERROR_ADDING_DISK_TEMPLATE = _("Error adding disk: {error}")
    ERROR_ATTACHING_DISK_TEMPLATE = _("Error attaching existing disk: {error}")
    ERROR_EDITING_DISK_TEMPLATE = _("Error editing disk: {error}")
    ERROR_SETTING_VM_VIDEO_MODEL_TEMPLATE = _("Error setting VM video model: {error}")
    ERROR_SETTING_CPU_MODEL_TEMPLATE = _("Error setting CPU model: {error}")
    ERROR_SETTING_UEFI_FILE_TEMPLATE = _("Error setting UEFI file: {error}")
    ERROR_SETTING_SHARED_MEMORY_TEMPLATE = _("Error setting shared memory: {error}")
    ERROR_SETTING_VM_GRAPHICS_TEMPLATE = _("Error setting VM graphics: {error}")
    ERROR_SETTING_VM_SOUND_MODEL_TEMPLATE = _("Error setting VM sound model: {error}")
    ERROR_SETTING_VM_RNG_TEMPLATE = _("Error setting VM RNG: {error}")
    ERROR_SETTING_VM_TPM_TEMPLATE = _("Error setting VM TPM: {error}")
    ERROR_ATTACHING_USB_DEVICE_TEMPLATE = _("Error attaching USB device: {error}")
    ERROR_DETACHING_USB_DEVICE_TEMPLATE = _("Error detaching USB device: {error}")
    ERROR_ADDING_SERIAL_CONSOLE_TEMPLATE = _("Error adding serial console: {error}")
    ERROR_REMOVING_SERIAL_CONSOLE_TEMPLATE = _("Error removing serial console: {error}")
    ERROR_ADDING_INPUT_DEVICE_TEMPLATE = _("Error adding input device: {error}")
    ERROR_REMOVING_INPUT_DEVICE_TEMPLATE = _("Error removing input device: {error}")
    ERROR_SETTING_VM_WATCHDOG_TEMPLATE = _("Error setting VM watchdog: {error}")
    ERROR_REMOVING_VM_WATCHDOG_TEMPLATE = _("Error removing VM watchdog: {error}")
    ERROR_ADDING_USB_DEVICE_TEMPLATE = _("Error adding USB device: {error}")
    ERROR_REMOVING_USB_DEVICE_TEMPLATE = _("Error removing USB device: {error}")
    ERROR_ADDING_SCSI_CONTROLLER_TEMPLATE = _("Error adding SCSI controller: {error}")
    ERROR_REMOVING_SCSI_CONTROLLER_TEMPLATE = _("Error removing SCSI controller: {error}")
    ERROR_MIGRATING_VM_MACHINE_TYPE_TEMPLATE = _("Error migrating VM machine type: {error}")
    ERROR_SETTING_VM_NUMATUNE_TEMPLATE = _("Error setting VM NUMA tune: {error}")
    ERROR_SETTING_VM_CPUTUNE_TEMPLATE = _("Error setting VM CPU tune: {error}")
    ERROR_REMOVING_VIRTIOFS_TEMPLATE = _("Error removing VirtIO-FS: {error}")
    ERROR_ADDING_VIRTIOFS_TEMPLATE = _("Error adding VirtIO-FS: {error}")
    ERROR_CHECKING_FOR_SPICE_DEVICES_TEMPLATE = _("Error checking for other SPICE devices: {error}")
    ERROR_REMOVING_SPICE_DEVICES_TEMPLATE = _("Error removing SPICE devices: {error}")
    SPICE_REMOVAL_CONFIRMATION_SINGLE = _("This VM has other SPICE-related devices (e.g., channels, QXL video).\\nDo you want to remove them for a clean switch to VNC?")
    SPICE_REMOVAL_CONFIRMATION_BULK = _("Some selected VMs have other SPICE-related devices.\\nDo you want to remove them from ALL selected VMs for a clean switch to VNC?")
    COULD_NOT_DETERMINE_SOURCE_POOL = _("Could not determine the source pool.")
    ERROR_SAVING_BOOT_ORDER_TEMPLATE = _("Error saving boot order: {error}")


class DialogMessages:
    """Constants for dialog messages"""
    DELETE_VM_CONFIRMATION = _("Are you sure you want to delete '{name}'?")
    DELETE_SNAPSHOT_CONFIRMATION = _("Are you sure you want to delete snapshot '{name}'?")
    DELETE_SNAPSHOTS_AND_RENAME = _("VM has {count} snapshot(s). To rename, they must be deleted.\nDelete snapshots and continue?")
    EXPERIMENTAL = _("Experimental Feature! Still contains bugs, fix in progress. You have been informed")
    CONFIRM_REMOVE_CHANNEL_TEMPLATE = _("Are you sure you want to remove channel '{target_name}'?")
    CONFIRM_REMOVE_INPUT_DEVICE_TEMPLATE = _("Are you sure you want to remove input device '{device_type}'?")
    CONFIRM_REMOVE_SERIAL_CONSOLE_TEMPLATE = _("Are you sure you want to remove serial console '{port}'?")
    CONFIRM_REMOVE_USB_DEVICE_TEMPLATE = _("Are you sure you want to remove USB device '{description}'?")
    CONFIRM_REMOVE_SCSI_CONTROLLER_TEMPLATE = _("Are you sure you want to remove SCSI controller '{model}' at index '{index}'?")
    CONFIRM_REMOVE_VIRTIOFS_TEMPLATE = _("Are you sure you want to remove VirtIO-FS mount '{target_path}'?")


class QuickMessages:
    """Constants for quick messages"""
    REMOTE_VIEWER_SELECTED = _("The remove viewer {viewer} has been selected.")
    VM_DATA_LOADED = _("VM data loaded. Displaying VMs...")
    FILTER_RUNNING_VMS = _("Filter: Running VMs")
    FILTER_ALL_VMS = _("Filter: All VMs")
    ALL_VMS_UNSELECTED = _("All VMs unselected.")
    CACHING_VM_STATE = _("Caching VM state for: {vms_list}")


class WarningMessages:
    """Constants for warning messages"""
    COMPACT_VIEW_LOCKED = _("Compact view is locked during bulk operations.")
    VMS_PER_PAGE_PERFORMANCE_WARNING = _("Displaying [b]{vms_per_page}[/b] VMs per page. CPU usage may increase; 9 is recommended for optimal performance.")
    VM_NOT_PAUSABLE = _("VM '{vm_name}' is not in a pausable state.")
    LIBVIRT_XML_NO_EFFECTIVE_CHANGE = _("VM [b]{vm_name}[/b]: Libvirt accepted the XML but the configuration remains unchanged. Your changes may have been ignored or normalized away.")
    NO_REMOTE_VIEWER_SELECTED = _("No remote viewer selected. Auto-detection will be used.")
    RUNNING_NETWORK_USAGE_SCAN_WARNING = _("Running network usage scan, this can freeze the UI for larger numbers of VMs.")
    TOO_MANY_VMS_DISK_USAGE_WARNING_TEMPLATE = _("More than {count} VMs detected on this server.\nSkipping disk usage scan to prevent UI freeze.")
    RUNNING_DISK_USAGE_SCAN_WARNING = _("Running disk usage scan, this can freeze the UI for larger numbers of VMs and disks.")
    VIRTIOFS_SHARED_MEM_WARNING = _("! Shared Memory is Mandatory to use VirtIO-FS.\\n! Enable it in Mem tab.")


class SuccessMessages:
    """Constants for success messages"""
    REMOTE_VIEWER_SELECTED = _("The remove viewer {viewer} has been selected.")
    CONNECTED_TO_SERVER = _("Connected to [b]{uri}[/b]")
    STATS_LOGGING_DISABLED = _("Statistics logging and monitoring disabled.")
    STATS_LOGGING_ENABLED = _("Statistics logging and monitoring enabled (every 10s).")
    CONFIG_UPDATED = _("Configuration updated.")
    VMS_SELECTED_BY_PATTERN = _("Selected {count} VMs matching pattern.")
    TERMINAL_COPY_HINT = _("In some Terminal use [b]Shift[/b] key while selecting text with the mouse to copy it.")
    NO_SERVERS_CONFIGURED = _("No servers configured. Please add one via 'Servers List'.")
    LOG_LEVEL_CHANGED = _("Log level changed to {level}")
    BULK_ACTION_SUCCESS_TEMPLATE = _("Bulk action [b]{action_type}[/b] successful for {count} VMs.")
    SERVER_CONNECTED = _("Connected to [b]{name}[/b]")
    INPUT_SANITIZED = _("Input sanitized: '{original_input}' changed to '{sanitized_input}'")
    OVERLAY_CREATED = _("Overlay [b]{overlay_name}[/b] created and attached.")
    OVERLAY_DISCARDED = _("Overlay for [b]{target_disk}[/b] discarded and reverted to base image.")
    DISK_COMMITTED = _("Disk changes committed successfully.")
    VM_CONFIG_UPDATED = _("VM [b]{vm_name}[/b] configuration updated successfully.")
    NO_XML_CHANGES = _("No changes made to the XML configuration.")
    SNAPSHOT_CREATED = _("Snapshot [b]{snapshot_name}[/b] created successfully.")
    SNAPSHOT_RESTORED = _("Restored to snapshot [b]{snapshot_name}[/b] successfully.")
    SNAPSHOT_DELETED = _("Snapshot [b]{snapshot_name}[/b] deleted successfully.")
    VM_DELETED = _("VM '{vm_name}' deleted successfully.")
    VM_RENAMED = _("VM '{old_name}' renamed to '{new_name}' successfully.")
    VM_RENAME_CANCELLED = _("VM rename cancelled.")
    VM_RENAME_NO_CHANGE = _("New VM name is the same as the old name. No rename performed.")
    VM_CLONED = _("Successfully cloned to: {vm_names}")
    WEBCONSOLE_STOPPED = _("Web console stopped.")
    REMOTE_USER_CERT_FOUND = _("Remote user cert/key found, using secure wss connection.")
    REMOTE_SYSTEM_CERT_FOUND = _("Remote system cert/key found, using secure wss connection.")
    NO_REMOTE_CERT_FOUND_GENERATING = _("No remote cert/key found. Attempting to generate in system directory...")
    NO_REMOTE_CERT_CHECK_INSECURE = _("Could not check for remote cert/key, using insecure ws connection.")
    REMOTE_CONNECTION_SSH_TUNNEL_SETUP = _("Remote connection detected. Setting up SSH tunnel...")
    LOCAL_CERT_FOUND = _("Found cert/key, using secure wss connection.")
    ALL_CACHES_CLEARED = _("All caches cleared")
    CONFIGURATION_SAVED = _("Configuration saved successfully.")
    STORAGE_POOL_CREATED_TEMPLATE = _("Storage pool '{name}' created and started.")
    NETWORK_CREATED_TEMPLATE = _("Network {name} created successfully.")
    NETWORK_UPDATED_TEMPLATE = _("Network {name} updated successfully.")
    VM_NAME_SANITIZED_TEMPLATE = _("VM name sanitized: '{original}' -> '{sanitized}'")
    VM_STARTED_TEMPLATE = _("VM '{vm_name}' started.")
    REMOTE_VIEWER_STARTED_TEMPLATE = _("Remote viewer {viewer} started for {vm_name}")
    VM_DEFINED_CONFIGURE_TEMPLATE = _("VM '{vm_name}' defined. Please configure and start it.")
    VM_CREATED_SUCCESSFULLY_TEMPLATE = _("VM '{vm_name}' created successfully!")
    SERVER_DELETED_TEMPLATE = _("Server '{server_name}' deleted successfully.")
    POOL_ACTIVATION_CHANGE_TEMPLATE = _("Pool '{pool_name}' is now {status}.")
    POOL_AUTOSTART_CHANGE_TEMPLATE = _("Autostart for pool '{pool_name}' is now {status}.")
    POOL_MANAGED_BY_EXISTING_POOL_TEMPLATE = _("A pool named '{pool_name}' already manages this directory.\nRefreshed pool to include the new volume.")
    NETWORK_ACTIVATION_CHANGE_TEMPLATE = _("Network '{net_name}' is now {status}.")
    NETWORK_AUTOSTART_CHANGE_TEMPLATE = _("Autostart for network '{net_name}' is now {status}.")
    BASE_NAME_SANITIZED_TEMPLATE = _("Base name sanitized: [b]{original}[/b] changed to [b]{sanitized}[/b]")
    SUFFIX_SANITIZED_TEMPLATE = _("Suffix sanitized: [b]{original}[/b] changed to [b]{sanitized}[/b]")
    INPUT_SANITIZED_TEMPLATE = _("Input sanitized: [b]{original}[/b] changed to [b]{sanitized}[/b]")
    BOOT_ORDER_SAVED_SUCCESSFULLY = _("Boot order saved successfully.")
    GRAPHICS_SETTINGS_APPLIED_SUCCESSFULLY = _("Graphics settings applied successfully")
    RNG_SETTINGS_APPLIED_SUCCESSFULLY = _("RNG settings applied successfully. Device: {rng_device}")
    TPM_SETTINGS_APPLIED_SUCCESSFULLY = _("TPM settings applied successfully")
    USB_DEVICE_ATTACHED_TEMPLATE = _("Attached USB device: {description}")
    USB_DEVICE_DETACHED_TEMPLATE = _("Detached USB device: {description}")
    CHANNEL_ADDED_SUCCESSFULLY = _("Channel added successfully.")
    CHANNEL_REMOVED_SUCCESSFULLY_TEMPLATE = _("Channel '{target_name}' removed successfully.")
    ADD_INPUT_DEVICE_SUCCESS = _("Input device '{device_type}' added successfully.")
    REMOVE_INPUT_DEVICE_SUCCESS = _("Input device '{device_type}' removed successfully.")
    SERIAL_CONSOLE_ADDED_SUCCESS = _("Serial console added successfully.")
    SERIAL_CONSOLE_REMOVED_SUCCESS = _("Serial console removed successfully.")
    WATCHDOG_APPLIED_SUCCESS = _("Watchdog settings applied successfully.")
    WATCHDOG_REMOVED_SUCCESS = _("Watchdog removed successfully.")
    USB_DEVICE_ATTACHED_SUCCESS = _("USB device '{description}' attached successfully.")
    USB_DEVICE_REMOVED_SUCCESS = _("USB device '{description}' removed successfully.")
    SCSI_CONTROLLER_ADDED_SUCCESS = _("SCSI controller added successfully.")
    SCSI_CONTROLLER_REMOVED_SUCCESS = _("SCSI controller removed successfully.")
    VIRTIOFS_ADDED_SUCCESS = _("VirtIO-FS mount added successfully.")
    VIRTIOFS_REMOVED_SUCCESS = _("VirtIO-FS mount removed successfully.")
    SPICE_DEVICES_REMOVED_SUCCESS = _("Removed associated SPICE devices")
    VM_VIDEO_MODEL_SET_SUCCESS = _("Video model set to {new_model}")
    VM_3D_ACCELERATION_SET_SUCCESS = _("3D Acceleration {state}")
    VM_SOUND_MODEL_SET_SUCCESS = _("Sound model set to {new_model}")
    VM_SECURE_BOOT_SET_SUCCESS = _("Secure Boot {state}")
    VM_SHARED_MEMORY_SET_SUCCESS = _("Shared memory {state}")
    VM_MACHINE_TYPE_SET_SUCCESS = _("Machine type set to {new_machine_type}")
    VM_VCPU_SET_SUCCESS = _("VCPU set to {vcpu_count}")
    VM_MEMORY_SET_SUCCESS = _("Memory set to {memory_mb} MB")
    VM_CPU_MODEL_SET_SUCCESS = _("CPU model set to {new_cpu_model}")
    VM_UEFI_FILE_SET_SUCCESS = _("UEFI file set to {uefi_file_name}")
    VM_DISK_ENABLED_SUCCESS = _("Disk '{disk_path}' enabled successfully.")
    VM_DISK_DISABLED_SUCCESS = _("Disk '{disk_path}' disabled successfully.")
    VM_DISK_REMOVED_SUCCESS = _("Disk '{disk_path}' removed successfully.")
    VM_DISK_ADDED_SUCCESS = _("Disk '{disk_path}' added successfully.")
    VM_DISK_ATTACHED_SUCCESS = _("Existing disk '{disk_path}' attached successfully.")
    VM_DISK_EDITED_SUCCESS = _("Disk '{disk_path}' updated successfully.")
    VM_NETWORK_INTERFACE_ADDED_SUCCESS = _("Network interface added successfully.")
    VM_NETWORK_INTERFACE_REMOVED_SUCCESS = _("Network interface removed successfully.")
    VM_NETWORK_INTERFACE_CHANGED_TEMPLATE = _("Interface {mac_address} switched to {new_network}")
    VM_CPUTUNE_SET_SUCCESS = _("CPU pinning settings applied successfully.")
    VM_NUMATUNE_SET_SUCCESS = _("NUMA tuning settings applied successfully.")


class ProgressMessages:
    """Constants for success messages"""
    CONNECTING_TO_SERVER = _("Connecting to [b]{uri}[/b]...")
    CONFIG_UPDATED_REFRESHING_VM_LIST = _("Configuration updated. Refreshing VM list...")
    LOADING_VM_DATA_FROM_REMOTE_SERVERS = _("Loading VM data from remote server(s)...")
