# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing import Optional

from ...._models import BaseModel

__all__ = ["StepGetOutputResponse"]


class StepGetOutputResponse(BaseModel):
    """Successfully retrieved step output data."""

    output: Optional[object] = None
    """The output data generated by the specified workflow step."""
