from .. import Expr

def getitem(expr: Expr, item: str) -> Expr: ...
def select(expr: Expr, including: list[str] | None = None, excluding: list[str] | None = None) -> Expr: ...
def pack(names: list[str], children: list[str], nullable: bool) -> Expr: ...
def merge(names: list[Expr]) -> Expr: ...
