import os

FLUX_PROXY_CONTROL_PLANE_ADDR = os.getenv("FLUX_PROXY_CONTROL_PLANE_ADDR")
FLUX_PROXY_HTTP_ADDR = os.getenv("FLUX_PROXY_HTTP_ADDR")
FLUX_PROXY_HTTPS_ADDR = os.getenv("FLUX_PROXY_HTTPS_ADDR")
