from __future__ import annotations

from pathlib import Path
from typing import Callable, Optional, Protocol, Sequence

from brkraw.api.types import AffineSpace, SubjectPose, SubjectType

# NOTE: If you change any callback signature in the controller or UI,
# update the matching protocol here so type checking stays aligned.


class TaskPopup(Protocol):
    def finish(self, *, success: bool) -> None: ...


class ViewerView(Protocol):
    def set_status(self, text: str) -> None: ...
    def set_dataset_path(self, path: Optional[Path]) -> None: ...
    def set_scan_list(self, scan_ids: list[tuple[int, str]]) -> None: ...
    def set_reco_list(self, reco_ids: Sequence[tuple[int, str]] | Sequence[int]) -> None: ...
    def schedule_poll(self, callback: Callable[[], None], interval_ms: int) -> None: ...
    def open_worker_popup(self, log_queue, title: str) -> TaskPopup | None: ...
    def set_params_summary(self, summary: dict) -> None: ...
    def set_param_results(self, rows: list[dict], *, truncated: int = 0) -> None: ...
    def open_registry_window(self) -> None: ...
    def open_study_info(self, info: dict) -> None: ...
    def registry_refresh(self) -> None: ...
    def registry_set_status(self, text: str) -> None: ...
    def set_viewer_views(
        self,
        views: dict,
        *,
        indices: tuple[int, int, int] | None = None,
        res: dict[str, tuple[float, float]] | None = None,
        crosshair: dict | None = None,
        show_crosshair: bool = False,
        lock_scale: bool = True,
        allow_overflow: bool = False,
        overflow_blend: float | None = None,
        zoom_scale: float | None = None,
    ) -> None: ...
    def set_viewer_subject_enabled(self, enabled: bool) -> None: ...
    def set_viewer_status(self, text: str) -> None: ...
    def set_viewer_subject_values(self, subject_type: str, pose_primary: str, pose_secondary: str) -> None: ...
    def set_viewer_rgb_state(self, *, enabled: bool, active: bool) -> None: ...
    def set_viewer_zoom_value(self, value: float) -> None: ...
    def set_viewer_ranges(
        self,
        *,
        x: int,
        y: int,
        z: int,
        frames: int,
        slicepacks: int,
        indices: tuple[int, int, int],
        frame: int,
        slicepack: int,
        extra_dims: list[int] | None = None,
        extra_indices: list[int] | None = None,
    ) -> None: ...
    def set_viewer_value_display(self, value_text: str, *, plot_enabled: bool) -> None: ...
    def set_scan_selected(self, scan_id: Optional[int]) -> None: ...
    def set_reco_selected(self, reco_id: Optional[int]) -> None: ...
    def set_subject_summary(self, *, study_id: str, subject_id: str, study_date: str) -> None: ...
    def set_tabs_enabled(self, enabled: bool) -> None: ...
    def get_selected_tab(self) -> Optional[str]: ...
    def select_tab(self, title: str) -> None: ...
    def set_viewer_hook_state(self, hook_name: str, enabled: bool, hook_args: Optional[dict], *, allow_toggle: bool = True) -> None: ...
    def set_convert_hook_state(self, hook_name: str, enabled: bool, hook_args: Optional[dict]) -> None: ...
    def set_convert_orientation_fields(
        self,
        *,
        use_viewer: bool,
        space: str,
        subject_type: Optional[str],
        pose_primary: str,
        pose_secondary: str,
        flip: tuple[bool, bool, bool],
    ) -> None: ...
    def set_convert_layout_fields(
        self,
        *,
        rule: str,
        info_spec: str,
        metadata_spec: str,
        context_map: str,
        template: str,
        slicepack_suffix: str,
    ) -> None: ...
    def set_convert_layout_keys(self, keys: list[str]) -> None: ...
    def set_convert_preview_text(self, text: str) -> None: ...
    def set_convert_settings_text(self, text: str) -> None: ...
    def notify_task_result(self, title: str, message: str, success: bool) -> None: ...
    def refresh_addons(self) -> None: ...
    def prompt_open_folder(self) -> Optional[Path]: ...
    def prompt_open_archive(self) -> Optional[Path]: ...
    def winfo_toplevel(self) -> object: ...



class MainCallbacks(Protocol):
    def on_open_folder(self) -> None: ...
    def on_open_archive(self) -> None: ...
    def on_refresh(self) -> None: ...
    def on_close(self) -> None: ...
    def on_tab_built(self, title: str) -> None: ...
    def on_tab_detached(self, title: str) -> None: ...
    def on_open_registry(self) -> None: ...
    def get_worker_log_queue(self) -> object | None: ...
    def on_open_study_info(self) -> None: ...
    def on_select_scan(self, scan_id: int) -> None: ...
    def on_select_reco(self, reco_id: int) -> None: ...
    def attach_view(self, view: ViewerView) -> None: ...
    def on_param_search(self, scope: str, query: str) -> dict: ...
    def on_apply_addon_spec(self, category: str, spec_path: str) -> object: ...
    def on_addon_context_map_change(self, path: Optional[str]) -> None: ...
    def resolve_addon_rule_file(self, category: str) -> tuple[Optional[str], Optional[str]]: ...
    def resolve_addon_spec(self, category: str) -> Optional[str]: ...
    def on_convert_submit(
        self,
        *,
        output_dir: str,
        base_name: str,
        space: AffineSpace,
        subject_type: Optional[SubjectType],
        subject_pose: Optional[SubjectPose],
        flip: tuple[bool, bool, bool],
        hook_enabled: bool,
        hook_name: str,
        hook_args: Optional[dict],
        sidecar_enabled: bool,
        sidecar_format: str,
        use_viewer_orientation: bool = False,
    ) -> None: ...
    def on_convert_preview(
        self,
        *,
        output_dir: str,
        layout_source: str,
        layout_auto: bool,
        layout_template: str,
        slicepack_suffix: str,
        sidecar_enabled: bool,
        sidecar_format: str,
    ) -> None: ...
    def on_convert_layout_change(self, layout_source: str, layout_auto: bool, layout_template: str) -> None: ...
    def on_convert_output_dir_change(self, output_dir: str) -> None: ...
    def on_convert_hook_toggle(self, enabled: bool) -> None: ...
    def on_convert_hook_options_apply(self, hook_name: str, hook_args: Optional[dict]) -> None: ...
    def on_convert_use_viewer_orientation_change(self, use_viewer: bool) -> None: ...
    def on_viewer_axis_change(self, axis: str, value: int) -> None: ...
    def on_viewer_frame_change(self, value: int) -> None: ...
    def on_viewer_hook_toggle(self, enabled: bool, hook_name: Optional[str]) -> None: ...
    def on_viewer_flip_change(self, axis: str, enabled: bool) -> None: ...
    def on_viewer_slicepack_change(self, value: int) -> None: ...
    def on_viewer_crosshair_toggle(self, enabled: bool) -> None: ...
    def on_viewer_hook_lock(self, locked: bool) -> None: ...
    def on_viewer_rgb_toggle(self, enabled: bool) -> None: ...
    def on_viewer_zoom_change(self, value: float) -> None: ...
    def on_viewer_zoom_step(self, delta: float, plane: str | None = None, rc: tuple[int, int] | None = None) -> None: ...
    def on_viewer_space_change(self, value: str) -> None: ...
    def register_viewer_space_listener(self, cb: Callable[[str], None]) -> None: ...
    def on_viewer_subject_reset(self) -> None: ...
    def on_viewer_subject_change(self, subject_type: str, pose_primary: str, pose_secondary: str) -> None: ...
    def on_viewer_hook_args_change(self, hook_args: Optional[dict]) -> None: ...
    def on_hook_options_apply(self, hook_name: str, hook_args: Optional[dict]) -> None: ...
    def on_viewer_extra_dim_change(self, index: int, value: int) -> None: ...
    def on_viewer_jump(self, x: int, y: int, z: int) -> None: ...
    def on_viewer_capture(self, plane: str, indices: tuple[int, int, int]) -> Optional[str]: ...
    def on_viewer_resize(self) -> None: ...
    def on_viewer_timecourse_toggle(self) -> None: ...
    def registry_list(self) -> list[dict]: ...
    def registry_add_paths(self, paths: list[Path]) -> tuple[int, int]: ...
    def registry_remove_paths(self, paths: list[Path]) -> int: ...
    def registry_scan_paths(self, paths: list[Path]) -> tuple[int, int]: ...
    def registry_open_path(self, path: Path) -> None: ...
    def registry_current_path(self) -> Optional[Path]: ...
    def get_study_info(self) -> dict: ...
