import threading
import types
from _typeshed import Incomplete
from minjiang_client.experiment.experiment import Experiment
from minjiang_client.group.cloud_group import CloudGroup
from minjiang_client.waveform import WavePackage as WavePackage
from minjiang_host_client.base.channel import Channel as Channel
from minjiang_host_client.base.worker import Worker as Worker
from minjiang_host_client.base.worker_monitors import CompilerMonitor as CompilerMonitor
from minjiang_host_client.utils.request import request as request
from minjiang_host_client.utils.terminate import check_terminate_signal as check_terminate_signal, upload_cancel_status as upload_cancel_status, write_terminate_signal as write_terminate_signal
from typing import Any

class P0Lock:
    name: Incomplete
    timeout: Incomplete
    def __init__(self, name: str | None = None, timeout: float | None = None) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: types.TracebackType | None): ...
    def acquire(self, blocking: bool = True, timeout: float | None = None) -> bool: ...
    def release(self) -> None: ...
    def locked(self) -> bool: ...
    def get_owner(self) -> str | None: ...
    def get_hold_time(self) -> float: ...

class CompilerWorker(Worker):
    space_name: str | None
    local_space_timestamp: int | None
    exp_json: dict | None
    priority_queues: Incomplete
    queue_lock: threading.RLock | None
    processing_lock_p1p2p3: P0Lock | None
    processing_lock_p0: P0Lock | None
    task_thread_p0: Incomplete
    p0_threads_started: bool
    task_thread_p1p2p3: Incomplete
    p1p2p3_threads_started: bool
    direct_link_server: str
    direct_link_port: int
    monitor: Incomplete
    def __init__(self, name: str, group_name: str, in_chl: Channel = None, out_chl: Channel = None, dl_server: str = 'localhost', dl_port: int = 6887) -> None: ...
    @property
    def group(self) -> CloudGroup: ...
    @group.setter
    def group(self, value: CloudGroup): ...
    def callback(self, wave_package: WavePackage, exp_obj: Experiment, pos: list, steps: int, options: dict): ...
    def add_task_to_queue(self, task_data: dict, priority: str = 'P2'): ...
    def get_queue_sizes(self) -> dict: ...
    def get_next_task_p1p2p3(self) -> dict | None: ...
    def get_next_task_p0(self) -> dict | None: ...
    def has_pending_tasks(self) -> bool: ...
    def start_task_processor_p0(self) -> None: ...
    def start_task_processor_p1p2p3(self) -> None: ...
    def task_processor_loop_p0(self) -> None: ...
    def task_processor_loop_p1p2p3(self) -> None: ...
    def compile(self, wave_package: WavePackage, exp_obj: Experiment, pos: list, steps: int, options: dict): ...
    def process_data(self, data: Any = None): ...
    def run_task(self, received) -> None: ...
