"""Unified tool registry - SSOT for CLI, MCP, and rendering."""

from .params import (
    Param,
    ParamType,
    # Common parameters
    QUERY,
    LIMIT,
    NO_CACHE,
    COUNTRY,
    PERIOD,
    TAGS,
    DEVICE,
    DOMAIN,
    REGION,
    NUM_RESULTS,
    SUBREDDITS,
    SORT,
    REDDIT_PERIOD,
    CHANNEL,
    CATEGORY,
    GEO,
    TIME_RANGE,
    DATA_TYPE,
    TIME_PERIOD,
    SORT_BY,
    AD_PLATFORM,
    AD_FORMAT,
    AD_TIME_PERIOD,
    LOCATION,
    LANGUAGE,
    KEYWORDS,
    COMPETITOR,
    ENGINES,
)

from .sections import (
    ColumnStyle,
    Column,
    TableSection,
    ListSection,
    MarkdownSection,
    KeyValueSection,
    StatsSection,
    OutputDefinition,
    # Column templates
    position_column,
    title_column,
    author_column,
    domain_column,
    count_column,
    date_column,
    tags_column,
    link_column,
    score_column,
    comments_column,
)

from .tool import (
    ServiceConfig,
    ToolDefinition,
)

from .renderer import render

from .factory import (
    get_cache,
    create_service,
    register_mcp_tool,
    register_all_mcp_tools,
    create_cli_group,
    build_cli_command,
    register_tools_to_cli,
)

__all__ = [
    # Params
    "Param",
    "ParamType",
    "QUERY",
    "LIMIT",
    "NO_CACHE",
    "COUNTRY",
    "PERIOD",
    "TAGS",
    "DEVICE",
    "DOMAIN",
    "REGION",
    "NUM_RESULTS",
    "SUBREDDITS",
    "SORT",
    "REDDIT_PERIOD",
    "CHANNEL",
    "CATEGORY",
    "GEO",
    "TIME_RANGE",
    "DATA_TYPE",
    "TIME_PERIOD",
    "SORT_BY",
    "AD_PLATFORM",
    "AD_FORMAT",
    "AD_TIME_PERIOD",
    "LOCATION",
    "LANGUAGE",
    "KEYWORDS",
    "COMPETITOR",
    "ENGINES",
    # Sections
    "ColumnStyle",
    "Column",
    "TableSection",
    "ListSection",
    "MarkdownSection",
    "KeyValueSection",
    "StatsSection",
    "OutputDefinition",
    "position_column",
    "title_column",
    "author_column",
    "domain_column",
    "count_column",
    "date_column",
    "tags_column",
    "link_column",
    "score_column",
    "comments_column",
    # Tool
    "ServiceConfig",
    "ToolDefinition",
    # Renderer
    "render",
    # Factory
    "get_cache",
    "create_service",
    "register_mcp_tool",
    "register_all_mcp_tools",
    "create_cli_group",
    "build_cli_command",
    "register_tools_to_cli",
]
