from __future__ import annotations

from modssc.preprocess.types import StepSpec

BUILTIN_STEPS: tuple[StepSpec, ...] = (
    # Core
    StepSpec(
        step_id="core.ensure_2d",
        import_path="modssc.preprocess.steps.core.ensure_2d:Ensure2DStep",
        kind="transform",
        description="Ensure numeric arrays are 2D (n_samples, n_features) and store as features.X.",
        required_extra=None,
        modalities=(),
        consumes=("raw.X",),
        produces=("features.X",),
    ),
    StepSpec(
        step_id="core.copy_raw",
        import_path="modssc.preprocess.steps.core.copy_raw:CopyRawStep",
        kind="transform",
        description="Copy raw.X into features.X without changing layout.",
        required_extra=None,
        modalities=(),
        consumes=("raw.X",),
        produces=("features.X",),
    ),
    StepSpec(
        step_id="core.to_numpy",
        import_path="modssc.preprocess.steps.core.to_numpy:ToNumpyStep",
        kind="transform",
        description="Convert features.X to a numpy array (no copy unless needed).",
        required_extra=None,
        modalities=(),
        consumes=("features.X",),
        produces=("features.X",),
    ),
    StepSpec(
        step_id="core.to_torch",
        import_path="modssc.preprocess.steps.core.to_torch:ToTorchStep",
        kind="transform",
        description="Convert features.X to a torch tensor on a target device/dtype.",
        required_extra="inductive-torch",
        modalities=(),
        consumes=("features.X",),
        produces=("features.X",),
    ),
    StepSpec(
        step_id="core.cast_dtype",
        import_path="modssc.preprocess.steps.core.cast_dtype:CastDtypeStep",
        kind="transform",
        description="Cast features.X to a target dtype (default float32).",
        required_extra=None,
        modalities=(),
        consumes=("features.X",),
        produces=("features.X",),
    ),
    StepSpec(
        step_id="core.cast_fp16",
        import_path="modssc.preprocess.steps.core.cast_fp16:CastFp16Step",
        kind="transform",
        description="Cast features.X to float16 (FP16).",
        required_extra=None,
        modalities=(),
        consumes=("features.X",),
        produces=("features.X",),
    ),
    StepSpec(
        step_id="core.pca",
        import_path="modssc.preprocess.steps.core.pca:PcaStep",
        kind="fittable",
        description="Fit PCA on a fit scope and transform features.X.",
        required_extra=None,
        modalities=(),
        consumes=("features.X",),
        produces=("features.X",),
    ),
    StepSpec(
        step_id="core.random_projection",
        import_path="modssc.preprocess.steps.core.random_projection:RandomProjectionStep",
        kind="fittable",
        description="Deterministic Gaussian random projection fit on train and applied to features.X.",
        required_extra=None,
        modalities=(),
        consumes=("features.X",),
        produces=("features.X",),
    ),
    # Embeddings
    StepSpec(
        step_id="embeddings.auto",
        import_path="modssc.preprocess.steps.embeddings.auto:AutoEmbeddingStep",
        kind="featurizer",
        description="Pick a default encoder by modality and write embeddings to features.X.",
        required_extra=None,
        modalities=(),
        consumes=("raw.X",),
        produces=("features.X",),
    ),
    # Tabular
    StepSpec(
        step_id="tabular.one_hot",
        import_path="modssc.preprocess.steps.tabular.one_hot:TabularOneHotStep",
        kind="fittable",
        description="One-hot encode categorical columns and pass through numeric columns.",
        required_extra="preprocess-sklearn",
        modalities=("tabular",),
        consumes=("raw.X",),
        produces=("features.X",),
    ),
    StepSpec(
        step_id="tabular.standard_scaler",
        import_path="modssc.preprocess.steps.tabular.standard_scaler:TabularStandardScalerStep",
        kind="fittable",
        description="Standardize features by removing the mean and scaling to unit variance.",
        required_extra="preprocess-sklearn",
        modalities=("tabular",),
        consumes=("features.X",),
        produces=("features.X",),
    ),
    StepSpec(
        step_id="tabular.impute",
        import_path="modssc.preprocess.steps.tabular.impute:TabularImputeStep",
        kind="fittable",
        description="Impute missing values using mean/median/etc.",
        required_extra="preprocess-sklearn",
        modalities=("tabular",),
        consumes=("features.X",),
        produces=("features.X",),
    ),
    # Text
    StepSpec(
        step_id="text.ensure_strings",
        import_path="modssc.preprocess.steps.text.ensure_strings:EnsureStringsStep",
        kind="transform",
        description="Ensure raw.X is a sequence of strings.",
        required_extra=None,
        modalities=("text",),
        consumes=("raw.X",),
        produces=("raw.X",),
    ),
    StepSpec(
        step_id="text.hash_tokenizer",
        import_path="modssc.preprocess.steps.text.hash_tokenizer:HashTokenizerStep",
        kind="transform",
        description="Deterministic hashed tokenizer producing tokens.input_ids and tokens.attention_mask.",
        required_extra=None,
        modalities=("text",),
        consumes=("raw.X",),
        produces=("tokens.input_ids", "tokens.attention_mask"),
    ),
    StepSpec(
        step_id="text.vocab_tokenizer",
        import_path="modssc.preprocess.steps.text.vocab_tokenizer:VocabTokenizerStep",
        kind="fittable",
        description="Fit a vocabulary and tokenize text into integer sequences (Tabula Rasa).",
        required_extra=None,
        modalities=("text",),
        consumes=("raw.X",),
        produces=("features.X", "tokens.input_ids", "tokens.attention_mask"),
    ),
    StepSpec(
        step_id="text.tfidf",
        import_path="modssc.preprocess.steps.text.tfidf:TfidfStep",
        kind="fittable",
        description="Fit a TF-IDF vectorizer and write sparse features.X.",
        required_extra="preprocess-sklearn",
        modalities=("text",),
        consumes=("raw.X",),
        produces=("features.X",),
    ),
    StepSpec(
        step_id="text.sentence_transformer",
        import_path="modssc.preprocess.steps.text.sentence_transformer:SentenceTransformerStep",
        kind="featurizer",
        description="Encode texts with a SentenceTransformer model into dense features.X.",
        required_extra="preprocess-text",
        modalities=("text",),
        consumes=("raw.X",),
        produces=("features.X",),
    ),
    # Vision
    StepSpec(
        step_id="vision.channels_order",
        import_path="modssc.preprocess.steps.vision.channels_order:ChannelsOrderStep",
        kind="transform",
        description="Convert images channel order (NHWC <-> NCHW) in raw.X.",
        required_extra=None,
        modalities=("vision",),
        consumes=("raw.X",),
        produces=("raw.X",),
    ),
    StepSpec(
        step_id="vision.ensure_num_channels",
        import_path="modssc.preprocess.steps.vision.ensure_num_channels:EnsureNumChannelsStep",
        kind="transform",
        description="Ensure images in raw.X have a fixed number of channels.",
        required_extra=None,
        modalities=("vision",),
        consumes=("raw.X",),
        produces=("raw.X",),
    ),
    StepSpec(
        step_id="vision.resize",
        import_path="modssc.preprocess.steps.vision.resize:ResizeStep",
        kind="transform",
        description="Resize images in raw.X to (height, width).",
        required_extra=None,
        modalities=("vision",),
        consumes=("raw.X",),
        produces=("raw.X",),
    ),
    StepSpec(
        step_id="vision.normalize",
        import_path="modssc.preprocess.steps.vision.normalize:NormalizeStep",
        kind="transform",
        description="Normalize images in raw.X using mean/std.",
        required_extra=None,
        modalities=("vision",),
        consumes=("raw.X",),
        produces=("raw.X",),
    ),
    StepSpec(
        step_id="vision.zca_whitening",
        import_path="modssc.preprocess.steps.vision.zca_whitening:ZcaWhiteningStep",
        kind="fittable",
        description="Fit ZCA whitening on train images and apply to raw.X.",
        required_extra=None,
        modalities=("vision",),
        consumes=("raw.X",),
        produces=("raw.X",),
    ),
    StepSpec(
        step_id="vision.squeeze",
        import_path="modssc.preprocess.steps.vision.squeeze:SqueezeStep",
        kind="transform",
        description="Squeeze raw.X dimension to handle single channel image arrays.",
        required_extra=None,
        modalities=("vision",),
        consumes=("raw.X",),
        produces=("raw.X",),
    ),
    StepSpec(
        step_id="vision.openclip",
        import_path="modssc.preprocess.steps.vision.openclip:OpenClipStep",
        kind="featurizer",
        description="Encode images with OpenCLIP into dense features.X.",
        required_extra="preprocess-vision",
        modalities=("vision",),
        consumes=("raw.X",),
        produces=("features.X",),
    ),
    # Audio
    StepSpec(
        step_id="audio.wav2vec2",
        import_path="modssc.preprocess.steps.audio.wav2vec2:Wav2Vec2Step",
        kind="featurizer",
        description="Encode audio with wav2vec2 into dense features.X.",
        required_extra="preprocess-audio",
        modalities=("audio",),
        consumes=("raw.X",),
        produces=("features.X",),
    ),
    StepSpec(
        step_id="audio.load_waveform",
        import_path="modssc.preprocess.steps.audio.load_waveform:LoadWaveformStep",
        kind="transform",
        description="Load audio waveforms from file paths into dense features.X.",
        required_extra="preprocess-audio",
        modalities=("audio",),
        consumes=("raw.X",),
        produces=("features.X",),
    ),
    StepSpec(
        step_id="audio.log_mel_spectrogram",
        import_path="modssc.preprocess.steps.audio.spectrogram:LogMelSpectrogramStep",
        kind="transform",
        description="Convert waveforms (features.X) to Log-Mel Spectrograms.",
        required_extra="preprocess-audio",
        modalities=("audio",),
        consumes=("features.X",),
        produces=("features.X",),
    ),
    # Graph
    StepSpec(
        step_id="graph.attach_edge_weight",
        import_path="modssc.preprocess.steps.graph.attach_edge_weight:AttachEdgeWeightStep",
        kind="transform",
        description="Create uniform edge weights if missing.",
        required_extra=None,
        modalities=("graph",),
        consumes=("graph.edge_index",),
        produces=("graph.edge_weight",),
    ),
    StepSpec(
        step_id="graph.edge_sparsify",
        import_path="modssc.preprocess.steps.graph.edge_sparsify:EdgeSparsifyStep",
        kind="transform",
        description="Sparsify edges by keeping a fraction (deterministic with seed).",
        required_extra=None,
        modalities=("graph",),
        consumes=("graph.edge_index", "graph.edge_weight"),
        produces=("graph.edge_index", "graph.edge_weight"),
    ),
    StepSpec(
        step_id="graph.node2vec",
        import_path="modssc.preprocess.steps.graph.node2vec:GraphNode2VecStep",
        kind="featurizer",
        description="Learn node2vec embeddings from graph edges and write features.X.",
        required_extra="transductive-torch",
        modalities=("graph",),
        consumes=("graph.edge_index",),
        produces=("features.X",),
    ),
    StepSpec(
        step_id="graph.sparse_adjacency",
        import_path="modssc.preprocess.steps.graph.sparse_adjacency:SparseAdjacencyStep",
        kind="transform",
        description="Pack X and edge_index into a dict for Inductive GNNs.",
        required_extra=None,
        modalities=("graph",),
        consumes=("graph.edge_index", "features.X"),
        produces=("features.X",),
    ),
    StepSpec(
        step_id="graph.dgi",
        import_path="modssc.preprocess.steps.graph.dgi:GraphDGIStep",
        kind="featurizer",
        description="Learn DGI embeddings from graph edges and write features.X.",
        required_extra="transductive-torch",
        modalities=("graph",),
        consumes=("graph.edge_index", "features.X", "raw.X"),
        produces=("features.X",),
    ),
    # Labels
    StepSpec(
        step_id="labels.encode",
        import_path="modssc.preprocess.steps.labels.encode:EncodeLabelsStep",
        kind="transform",
        description="Encode raw.y to contiguous int64 labels (labels.y) and store classes.",
        required_extra=None,
        modalities=(),
        consumes=("raw.y",),
        produces=("labels.y", "labels.classes"),
    ),
    StepSpec(
        step_id="labels.ensure_onehot",
        import_path="modssc.preprocess.steps.labels.ensure_onehot:EnsureOneHotLabelsStep",
        kind="transform",
        description="Convert integer labels to one-hot (labels.y_onehot) and label mask.",
        required_extra=None,
        modalities=(),
        consumes=("raw.y",),
        produces=("labels.y_onehot", "labels.is_labeled"),
    ),
    StepSpec(
        step_id="labels.to_numpy",
        import_path="modssc.preprocess.steps.labels.to_numpy:LabelsToNumpyStep",
        kind="transform",
        description="Convert raw.y to numpy and store as labels.y.",
        required_extra=None,
        modalities=(),
        consumes=("raw.y",),
        produces=("labels.y",),
    ),
    StepSpec(
        step_id="labels.to_torch",
        import_path="modssc.preprocess.steps.labels.to_torch:LabelsToTorchStep",
        kind="transform",
        description="Convert raw.y to a torch tensor and store as labels.y.",
        required_extra="inductive-torch",
        modalities=(),
        consumes=("raw.y",),
        produces=("labels.y",),
    ),
)
