from typing import Any, List, Optional

class Policy:
    @classmethod
    def from_file(cls, path: str) -> "Policy": ...

class CoverageAnalyzer:
    def __init__(self, policy: Policy) -> None: ...
    def analyze(self, traces: List[Any], min_coverage: float) -> str: ...

class AssayClient:
    def __init__(self, trace_file: Optional[str] = None) -> None: ...
    def record_trace(self, trace: Any) -> None: ...

class TraceExplainer:
    def __init__(self, policy: Policy) -> None: ...
    def explain(self, traces: List[Any]) -> str: ...
