from amsdal_utils.errors import AmsdalError


class AmsdalRuntimeError(AmsdalError): ...


class TransactionNotFoundError(AmsdalError): ...


class AmsdalAuthenticationError(AmsdalRuntimeError): ...


class AmsdalDeployError(AmsdalRuntimeError): ...


class AmsdalCloudError(AmsdalRuntimeError): ...


class AmsdalCloudAlreadyDeployedError(AmsdalCloudError): ...


class AmsdalCloudCredentialsError(AmsdalCloudError): ...


class AmsdalMissingCredentialsError(AmsdalAuthenticationError): ...


class AmsdalAuthConnectionError(AmsdalAuthenticationError): ...


class AmsdalSignupError(AmsdalAuthenticationError): ...
