import enum


class UserAssignmentStatus(enum.StrEnum):
    NO_ASSIGNMENT = "NONE"
    UNSECURED = "HEARSAY"
    TRUSTED = "TRUSTED"
    VERIFIED = "VERIFIED"
    CERTIFIED = "CERTIFIED"
    SECURE = "SECURE"
    UID_MISMATCH = "MISMATCH"
    CERT_INCORRECT = "INVALID"
    CERT_EXPIRED = "OUTDATED"
    CERT_UNVERIFIED = "UNKNOWN"


class IdentificationFlagRFID(enum.StrEnum):
    NO_ASSIGNMENT_VIA_RFID = "RFID_NONE"
    ASSIGNMENT_VIA_EXTERNAL_RFID_CARD_READER = "RFID_PLAIN"
    ASSIGNMENT_VIA_PROTECTED_RFID_CARD_READER = "RFID_RELATED"
    PREVIOUSLY_KNOWN_SHARED_KEY = "RFID_PSK"


class IdentificationFlagOCPP(enum.StrEnum):
    NO_USER_ASSIGNMENT_BY_OCPP = "OCPP_NONE"
    ASSIGNMENT_BY_OCPP_REMOTESTART_METHOD = "OCPP_RS"
    ASSIGNMENT_BY_OCPP_AUTHORIZE_METHOD = "OCPP_AUTH"
    ASSIGNMENT_BY_OCPP_REMOTESTART_METHOD_TLS = "OCPP_RS_TLS"
    ASSIGNMENT_BY_OCPP_AUTHORIZE_METHOD_TLS = "OCPP_AUTH_TLS"
    ASSIGNMENT_BY_AUTHORIZATION_CACHE_OF_OCPP = "OCPP_CACHE"
    ASSIGNMENT_BY_WHITELIST_FROM_OCPP = "OCPP_WHITELIST"
    CERTIFICATE_OF_BACKEND_USED = "OCPP_CERTIFIED"


class IdentificationFlagIso15118(enum.StrEnum):
    NO_USER_ASSIGNMENT_BY_ISO_15118 = "ISO15118_NONE"
    PLUG_AND_CHARGE_WAS_USED = "ISO15118_PNC"


class IdentificationFlagPLMN(enum.StrEnum):
    NO_USER_ASSIGNMENT = "PLMN_NONE"
    CALL = "PLMN_RING"
    SHORT_MESSAGE = "PLMN_SMS"


class IdentificationType(enum.StrEnum):
    NONE = "NONE"
    DENIED = "DENIED"
    UNDEFINED = "UNDEFINED"
    ISO14443 = "ISO14443"
    ISO15693 = "ISO15693"
    EMAID = "EMAID"
    EVCCID = "EVCCID"
    EVCOID = "EVCOID"
    ISO7812 = "ISO7812"
    CARD_TXN_NR = "CARD_TXN_NR"
    CENTRAL = "CENTRAL"
    CENTRAL_1 = "CENTRAL_1"
    CENTRAL_2 = "CENTRAL_2"
    LOCAL = "LOCAL"
    LOCAL_1 = "LOCAL_1"
    LOCAL_2 = "LOCAL_2"
    PHONE_NUMBER = "PHONE_NUMBER"
    KEY_CODE = "KEY_CODE"


class ChargePointIdentificationType(enum.StrEnum):
    EVSEID = "EVSEID"
    CBIDC = "CBIDC"


IdentificationFlag = (
    IdentificationFlagRFID
    | IdentificationFlagOCPP
    | IdentificationFlagIso15118
    | IdentificationFlagPLMN
)
