# coding: utf-8

"""
    FlowHunt

    FlowHunt API

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flowhunt.models.per_day_feedback import PerDayFeedback

class TestPerDayFeedback(unittest.TestCase):
    """PerDayFeedback unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PerDayFeedback:
        """Test PerDayFeedback
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PerDayFeedback`
        """
        model = PerDayFeedback()
        if include_optional:
            return PerDayFeedback(
                var_date = '',
                positive = 56,
                negative = 56,
                session_count = 56,
                human_message_count = 56,
                tool_calling_count = 56
            )
        else:
            return PerDayFeedback(
                var_date = '',
        )
        """

    def testPerDayFeedback(self):
        """Test PerDayFeedback"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
