# coding: utf-8

"""
    FlowHunt

    FlowHunt API

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flowhunt.models.schedule_create_request import ScheduleCreateRequest

class TestScheduleCreateRequest(unittest.TestCase):
    """ScheduleCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ScheduleCreateRequest:
        """Test ScheduleCreateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ScheduleCreateRequest`
        """
        model = ScheduleCreateRequest()
        if include_optional:
            return ScheduleCreateRequest(
                url = flowhunt.models.app_url.AppUrl(
                    parsed_url = [
                        null
                        ], 
                    url = '', ),
                frequency = 'D',
                schedule_type = 'U',
                with_screenshot = Y,
                with_browser = Y,
                follow_links = Y,
                with_proxy_rotation = 'Y',
                disallow_urls = '/documents/',
                filter_urls = '/documents/',
                custom_headers = 'User-Agent=Mozilla/5.0
Accept-Language=en-US,en;q=0.5',
                urls_extra_config = '{"urls": ["https://example.com/page1", "https://example.com/page2"]}'
            )
        else:
            return ScheduleCreateRequest(
                url = flowhunt.models.app_url.AppUrl(
                    parsed_url = [
                        null
                        ], 
                    url = '', ),
                frequency = 'D',
                schedule_type = 'U',
        )
        """

    def testScheduleCreateRequest(self):
        """Test ScheduleCreateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
