"""
BrainCo ECAP SDK - Python bindings for EEG Cap device control and data processing
"""

# Import all classes, enums, and functions from the Rust extension module
from ._bc_ecap_sdk import (
    # Classes
    BLEDeviceInfo,
    BandPassFilter,
    BandStopFilter,
    ECapClient,
    HighPassFilter,
    LowPassFilter,
    LslConfig,
    MdnsScanResult,
    MessageParser,
    NotchFilter,
    PyTcpClient,
    PyTcpStream,
    ScanResult,
    SosFilter,

    # Enums
    CentralAdapterState,
    ConnectionState,
    EegSampleRate,
    EegSignalGain,
    EegSignalSource,
    ImuSampleRate,
    LeadOffChip,
    LeadOffCurrent,
    LeadOffFreq,
    LogLevel,
    MsgType,
    NoiseTypes,
    WiFiSecurity,

    # Functions
    apply_bandpass_filter,
    apply_bandstop_filter,
    apply_eeg_filter,
    apply_eeg_sosfiltfilt,
    apply_highpass_filter,
    apply_impendance_filter,
    apply_impendance_sosfiltfilt,
    apply_lowpass_filter,
    calculate_fft_data,
    clear_eeg_buffer,
    clear_imu_buffer,
    clear_imp_eeg_buffers,
    ble_connect,
    ble_disconnect,
    get_ble_device_info,
    get_eeg_buffer,
    get_imu_buffer,
    get_wifi_config,
    get_wifi_status,
    init_adapter,
    parse_eeg_data,
    remove_env_noise,
    remove_env_noise_notch,
    remove_env_noise_sosfiltfilt,
    set_adapter_state_callback,
    set_battery_level_callback,
    set_ble_device_info,
    set_cfg,
    set_connection_state_callback,
    set_device_discovered_callback,
    set_device_info_callback,
    set_eeg_data_callback,
    set_eeg_data_callback_v2,
    set_env_noise_cfg,
    set_imp_data_callback,
    set_imu_data_callback,
    set_msg_resp_callback,
    set_received_data_callback,
    set_scan_result_callback,
    set_wifi_config,
    ble_start_scan,
    ble_stop_scan,
    mdns_start_scan,
    mdns_stop_scan,

    # EDF Recording functions
    start_edf_recording,
    stop_edf_recording,
    is_edf_recording,
    add_edf_annotation,
)

# BLE submodule is no longer used, functions are exported directly
__all__ = []

# Add all exported symbols to __all__
__all__ += [
    # Classes
    'BLEDeviceInfo',
    'BandPassFilter',
    'BandStopFilter',
    'ECapClient',
    'HighPassFilter',
    'LowPassFilter',
    'LslConfig',
    'MdnsScanResult',
    'MessageParser',
    'NotchFilter',
    'PyTcpClient',
    'PyTcpStream',
    'ScanResult',
    'SosFilter',

    # Enums
    'CentralAdapterState',
    'ConnectionState',
    'EegSampleRate',
    'EegSignalGain',
    'EegSignalSource',
    'ImuSampleRate',
    'LeadOffChip',
    'LeadOffCurrent',
    'LeadOffFreq',
    'LogLevel',
    'MsgType',
    'NoiseTypes',
    'WiFiSecurity',

    # Functions
    'apply_bandpass_filter',
    'apply_bandstop_filter',
    'apply_eeg_filter',
    'apply_eeg_sosfiltfilt',
    'apply_highpass_filter',
    'apply_impendance_filter',
    'apply_impendance_sosfiltfilt',
    'apply_lowpass_filter',
    'calculate_fft_data',
    'clear_eeg_buffer',
    'clear_imu_buffer',
    'clear_imp_eeg_buffers',
    'ble_connect',
    'ble_disconnect',
    'get_ble_device_info',
    'get_eeg_buffer',
    'get_imu_buffer',
    'get_wifi_config',
    'get_wifi_status',
    'init_adapter',
    'parse_eeg_data',
    'remove_env_noise',
    'remove_env_noise_notch',
    'remove_env_noise_sosfiltfilt',
    'set_adapter_state_callback',
    'set_battery_level_callback',
    'set_ble_device_info',
    'set_cfg',
    'set_connection_state_callback',
    'set_device_discovered_callback',
    'set_device_info_callback',
    'set_eeg_data_callback',
    'set_eeg_data_callback_v2',
    'set_env_noise_cfg',
    'set_imp_data_callback',
    'set_imu_data_callback',
    'set_msg_resp_callback',
    'set_received_data_callback',
    'set_scan_result_callback',
    'set_wifi_config',
    'ble_start_scan',
    'ble_stop_scan',
    'mdns_start_scan',
    'mdns_stop_scan',

    # EDF Recording functions
    'start_edf_recording',
    'stop_edf_recording',
    'is_edf_recording',
    'add_edf_annotation',
]

__version__ = "0.4.0"  # This will be updated by maturin
