
class TokenFuzzer:
    def __init__(self, data: list[str], num_hashes: int = 128, method: str = "naive", min_token_length: int = 0, max_token_length: int = 8) -> None: ...
    def match_closest(self, query: str) -> str: ...
    def match_closest_batch(self, queries: list[str]) -> list[str]: ...