# coding: utf-8

"""
 Shaped API

 Welcome to Shaped's API reference docs. These provide a  detailed view of the endpoints and CLI commands that Shaped provides and brief  explanations of how they should be used.  The Shaped API has four main endpoints:  **Tables** - Provision and manage batch and real-time data connectors.   **Views** - Configure SQL transformations and AI enrichment on your input data. Use SQL to combine multiple data sources or use an LLM to add new categories, extract specific attributes from descriptions, etc.  **Engines** - Deploy and manage your relevance engines. The Engine API exposes configuration for indexing logic, input datasets, externam embeddings, and more.  **Query** - Execute queries against your engines, to return data based on an input query or rerank an existing list. The Query API exposes the retrieve, filter, score, and ranking steps of the 4-stage ranking architecture.  The base URL for each endpoint is: `https://api.shaped.ai/v2`

 Generated by OpenAPI Generator (https://openapi-generator.tech)

 Do not edit the class manually.
""" # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from shaped.autogen.models.shaped_internal_recsys_policies_als_model_policy_als_model_policy_config import ShapedInternalRecsysPoliciesAlsModelPolicyALSModelPolicyConfig
from shaped.autogen.models.shaped_internal_recsys_policies_beeformer_model_policy_beeformer_model_policy_beeformer_model_policy_config import ShapedInternalRecsysPoliciesBeeformerModelPolicyBeeformerModelPolicyBeeformerModelPolicyConfig
from shaped.autogen.models.shaped_internal_recsys_policies_bert_model_policy_bert_model_policy_bert_model_policy_config import ShapedInternalRecsysPoliciesBertModelPolicyBertModelPolicyBERTModelPolicyConfig
from shaped.autogen.models.shaped_internal_recsys_policies_elsa_model_policy_elsa_model_policy_elsa_model_policy_config import ShapedInternalRecsysPoliciesElsaModelPolicyElsaModelPolicyELSAModelPolicyConfig
from shaped.autogen.models.shaped_internal_recsys_policies_gsasrec_model_policy_gsasrec_model_policy_gsas_rec_model_policy_config import ShapedInternalRecsysPoliciesGsasrecModelPolicyGsasrecModelPolicyGSASRecModelPolicyConfig
from shaped.autogen.models.shaped_internal_recsys_policies_item2vec_model_policy_item2_vec_model_policy_config import ShapedInternalRecsysPoliciesItem2vecModelPolicyItem2VecModelPolicyConfig
from shaped.autogen.models.shaped_internal_recsys_policies_lightgbm_model_policy_lightgbm_model_policy_light_gbm_model_policy_config import ShapedInternalRecsysPoliciesLightgbmModelPolicyLightgbmModelPolicyLightGBMModelPolicyConfig
from shaped.autogen.models.shaped_internal_recsys_policies_ngram_model_policy_ngram_model_policy_config import ShapedInternalRecsysPoliciesNgramModelPolicyNgramModelPolicyConfig
from shaped.autogen.models.shaped_internal_recsys_policies_rising_popular_policy_rising_popular_policy_config import ShapedInternalRecsysPoliciesRisingPopularPolicyRisingPopularPolicyConfig
from shaped.autogen.models.shaped_internal_recsys_policies_sasrec_model_policy_sasrec_model_policy_sas_rec_model_policy_config import ShapedInternalRecsysPoliciesSasrecModelPolicySasrecModelPolicySASRecModelPolicyConfig
from shaped.autogen.models.shaped_internal_recsys_policies_svd_model_policy_svd_model_policy_config import ShapedInternalRecsysPoliciesSvdModelPolicySVDModelPolicyConfig
from shaped.autogen.models.shaped_internal_recsys_policies_two_tower_model_policy_two_tower_model_policy_two_tower_model_policy_config import ShapedInternalRecsysPoliciesTwoTowerModelPolicyTwoTowerModelPolicyTwoTowerModelPolicyConfig
from shaped.autogen.models.shaped_internal_recsys_policies_widedeep_model_policy_wide_deep_model_policy_config import ShapedInternalRecsysPoliciesWidedeepModelPolicyWideDeepModelPolicyConfig
from shaped.autogen.models.shaped_internal_recsys_policies_xgboost_model_policy_xg_boost_model_policy_config import ShapedInternalRecsysPoliciesXgboostModelPolicyXGBoostModelPolicyConfig
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

MODELSINNER_ONE_OF_SCHEMAS = ["ShapedInternalRecsysPoliciesAlsModelPolicyALSModelPolicyConfig", "ShapedInternalRecsysPoliciesBeeformerModelPolicyBeeformerModelPolicyBeeformerModelPolicyConfig", "ShapedInternalRecsysPoliciesBertModelPolicyBertModelPolicyBERTModelPolicyConfig", "ShapedInternalRecsysPoliciesElsaModelPolicyElsaModelPolicyELSAModelPolicyConfig", "ShapedInternalRecsysPoliciesGsasrecModelPolicyGsasrecModelPolicyGSASRecModelPolicyConfig", "ShapedInternalRecsysPoliciesItem2vecModelPolicyItem2VecModelPolicyConfig", "ShapedInternalRecsysPoliciesLightgbmModelPolicyLightgbmModelPolicyLightGBMModelPolicyConfig", "ShapedInternalRecsysPoliciesNgramModelPolicyNgramModelPolicyConfig", "ShapedInternalRecsysPoliciesRisingPopularPolicyRisingPopularPolicyConfig", "ShapedInternalRecsysPoliciesSasrecModelPolicySasrecModelPolicySASRecModelPolicyConfig", "ShapedInternalRecsysPoliciesSvdModelPolicySVDModelPolicyConfig", "ShapedInternalRecsysPoliciesTwoTowerModelPolicyTwoTowerModelPolicyTwoTowerModelPolicyConfig", "ShapedInternalRecsysPoliciesWidedeepModelPolicyWideDeepModelPolicyConfig", "ShapedInternalRecsysPoliciesXgboostModelPolicyXGBoostModelPolicyConfig"]

class ModelsInner(BaseModel):
    """
    ModelsInner
    """
    # data type: ShapedInternalRecsysPoliciesElsaModelPolicyElsaModelPolicyELSAModelPolicyConfig
    oneof_schema_1_validator: Optional[ShapedInternalRecsysPoliciesElsaModelPolicyElsaModelPolicyELSAModelPolicyConfig] = None
    # data type: ShapedInternalRecsysPoliciesLightgbmModelPolicyLightgbmModelPolicyLightGBMModelPolicyConfig
    oneof_schema_2_validator: Optional[ShapedInternalRecsysPoliciesLightgbmModelPolicyLightgbmModelPolicyLightGBMModelPolicyConfig] = None
    # data type: ShapedInternalRecsysPoliciesAlsModelPolicyALSModelPolicyConfig
    oneof_schema_3_validator: Optional[ShapedInternalRecsysPoliciesAlsModelPolicyALSModelPolicyConfig] = None
    # data type: ShapedInternalRecsysPoliciesSvdModelPolicySVDModelPolicyConfig
    oneof_schema_4_validator: Optional[ShapedInternalRecsysPoliciesSvdModelPolicySVDModelPolicyConfig] = None
    # data type: ShapedInternalRecsysPoliciesSasrecModelPolicySasrecModelPolicySASRecModelPolicyConfig
    oneof_schema_5_validator: Optional[ShapedInternalRecsysPoliciesSasrecModelPolicySasrecModelPolicySASRecModelPolicyConfig] = None
    # data type: ShapedInternalRecsysPoliciesGsasrecModelPolicyGsasrecModelPolicyGSASRecModelPolicyConfig
    oneof_schema_6_validator: Optional[ShapedInternalRecsysPoliciesGsasrecModelPolicyGsasrecModelPolicyGSASRecModelPolicyConfig] = None
    # data type: ShapedInternalRecsysPoliciesBertModelPolicyBertModelPolicyBERTModelPolicyConfig
    oneof_schema_7_validator: Optional[ShapedInternalRecsysPoliciesBertModelPolicyBertModelPolicyBERTModelPolicyConfig] = None
    # data type: ShapedInternalRecsysPoliciesTwoTowerModelPolicyTwoTowerModelPolicyTwoTowerModelPolicyConfig
    oneof_schema_8_validator: Optional[ShapedInternalRecsysPoliciesTwoTowerModelPolicyTwoTowerModelPolicyTwoTowerModelPolicyConfig] = None
    # data type: ShapedInternalRecsysPoliciesRisingPopularPolicyRisingPopularPolicyConfig
    oneof_schema_9_validator: Optional[ShapedInternalRecsysPoliciesRisingPopularPolicyRisingPopularPolicyConfig] = None
    # data type: ShapedInternalRecsysPoliciesNgramModelPolicyNgramModelPolicyConfig
    oneof_schema_10_validator: Optional[ShapedInternalRecsysPoliciesNgramModelPolicyNgramModelPolicyConfig] = None
    # data type: ShapedInternalRecsysPoliciesWidedeepModelPolicyWideDeepModelPolicyConfig
    oneof_schema_11_validator: Optional[ShapedInternalRecsysPoliciesWidedeepModelPolicyWideDeepModelPolicyConfig] = None
    # data type: ShapedInternalRecsysPoliciesItem2vecModelPolicyItem2VecModelPolicyConfig
    oneof_schema_12_validator: Optional[ShapedInternalRecsysPoliciesItem2vecModelPolicyItem2VecModelPolicyConfig] = None
    # data type: ShapedInternalRecsysPoliciesXgboostModelPolicyXGBoostModelPolicyConfig
    oneof_schema_13_validator: Optional[ShapedInternalRecsysPoliciesXgboostModelPolicyXGBoostModelPolicyConfig] = None
    # data type: ShapedInternalRecsysPoliciesBeeformerModelPolicyBeeformerModelPolicyBeeformerModelPolicyConfig
    oneof_schema_14_validator: Optional[ShapedInternalRecsysPoliciesBeeformerModelPolicyBeeformerModelPolicyBeeformerModelPolicyConfig] = None
    actual_instance: Optional[Union[ShapedInternalRecsysPoliciesAlsModelPolicyALSModelPolicyConfig, ShapedInternalRecsysPoliciesBeeformerModelPolicyBeeformerModelPolicyBeeformerModelPolicyConfig, ShapedInternalRecsysPoliciesBertModelPolicyBertModelPolicyBERTModelPolicyConfig, ShapedInternalRecsysPoliciesElsaModelPolicyElsaModelPolicyELSAModelPolicyConfig, ShapedInternalRecsysPoliciesGsasrecModelPolicyGsasrecModelPolicyGSASRecModelPolicyConfig, ShapedInternalRecsysPoliciesItem2vecModelPolicyItem2VecModelPolicyConfig, ShapedInternalRecsysPoliciesLightgbmModelPolicyLightgbmModelPolicyLightGBMModelPolicyConfig, ShapedInternalRecsysPoliciesNgramModelPolicyNgramModelPolicyConfig, ShapedInternalRecsysPoliciesRisingPopularPolicyRisingPopularPolicyConfig, ShapedInternalRecsysPoliciesSasrecModelPolicySasrecModelPolicySASRecModelPolicyConfig, ShapedInternalRecsysPoliciesSvdModelPolicySVDModelPolicyConfig, ShapedInternalRecsysPoliciesTwoTowerModelPolicyTwoTowerModelPolicyTwoTowerModelPolicyConfig, ShapedInternalRecsysPoliciesWidedeepModelPolicyWideDeepModelPolicyConfig, ShapedInternalRecsysPoliciesXgboostModelPolicyXGBoostModelPolicyConfig]] = None
    one_of_schemas: Set[str] = { "ShapedInternalRecsysPoliciesAlsModelPolicyALSModelPolicyConfig", "ShapedInternalRecsysPoliciesBeeformerModelPolicyBeeformerModelPolicyBeeformerModelPolicyConfig", "ShapedInternalRecsysPoliciesBertModelPolicyBertModelPolicyBERTModelPolicyConfig", "ShapedInternalRecsysPoliciesElsaModelPolicyElsaModelPolicyELSAModelPolicyConfig", "ShapedInternalRecsysPoliciesGsasrecModelPolicyGsasrecModelPolicyGSASRecModelPolicyConfig", "ShapedInternalRecsysPoliciesItem2vecModelPolicyItem2VecModelPolicyConfig", "ShapedInternalRecsysPoliciesLightgbmModelPolicyLightgbmModelPolicyLightGBMModelPolicyConfig", "ShapedInternalRecsysPoliciesNgramModelPolicyNgramModelPolicyConfig", "ShapedInternalRecsysPoliciesRisingPopularPolicyRisingPopularPolicyConfig", "ShapedInternalRecsysPoliciesSasrecModelPolicySasrecModelPolicySASRecModelPolicyConfig", "ShapedInternalRecsysPoliciesSvdModelPolicySVDModelPolicyConfig", "ShapedInternalRecsysPoliciesTwoTowerModelPolicyTwoTowerModelPolicyTwoTowerModelPolicyConfig", "ShapedInternalRecsysPoliciesWidedeepModelPolicyWideDeepModelPolicyConfig", "ShapedInternalRecsysPoliciesXgboostModelPolicyXGBoostModelPolicyConfig" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = ModelsInner.model_construct()
        error_messages = []
        match = 0
        # validate data type: ShapedInternalRecsysPoliciesElsaModelPolicyElsaModelPolicyELSAModelPolicyConfig
        if not isinstance(v, ShapedInternalRecsysPoliciesElsaModelPolicyElsaModelPolicyELSAModelPolicyConfig):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ShapedInternalRecsysPoliciesElsaModelPolicyElsaModelPolicyELSAModelPolicyConfig`")
        else:
            match += 1
        # validate data type: ShapedInternalRecsysPoliciesLightgbmModelPolicyLightgbmModelPolicyLightGBMModelPolicyConfig
        if not isinstance(v, ShapedInternalRecsysPoliciesLightgbmModelPolicyLightgbmModelPolicyLightGBMModelPolicyConfig):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ShapedInternalRecsysPoliciesLightgbmModelPolicyLightgbmModelPolicyLightGBMModelPolicyConfig`")
        else:
            match += 1
        # validate data type: ShapedInternalRecsysPoliciesAlsModelPolicyALSModelPolicyConfig
        if not isinstance(v, ShapedInternalRecsysPoliciesAlsModelPolicyALSModelPolicyConfig):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ShapedInternalRecsysPoliciesAlsModelPolicyALSModelPolicyConfig`")
        else:
            match += 1
        # validate data type: ShapedInternalRecsysPoliciesSvdModelPolicySVDModelPolicyConfig
        if not isinstance(v, ShapedInternalRecsysPoliciesSvdModelPolicySVDModelPolicyConfig):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ShapedInternalRecsysPoliciesSvdModelPolicySVDModelPolicyConfig`")
        else:
            match += 1
        # validate data type: ShapedInternalRecsysPoliciesSasrecModelPolicySasrecModelPolicySASRecModelPolicyConfig
        if not isinstance(v, ShapedInternalRecsysPoliciesSasrecModelPolicySasrecModelPolicySASRecModelPolicyConfig):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ShapedInternalRecsysPoliciesSasrecModelPolicySasrecModelPolicySASRecModelPolicyConfig`")
        else:
            match += 1
        # validate data type: ShapedInternalRecsysPoliciesGsasrecModelPolicyGsasrecModelPolicyGSASRecModelPolicyConfig
        if not isinstance(v, ShapedInternalRecsysPoliciesGsasrecModelPolicyGsasrecModelPolicyGSASRecModelPolicyConfig):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ShapedInternalRecsysPoliciesGsasrecModelPolicyGsasrecModelPolicyGSASRecModelPolicyConfig`")
        else:
            match += 1
        # validate data type: ShapedInternalRecsysPoliciesBertModelPolicyBertModelPolicyBERTModelPolicyConfig
        if not isinstance(v, ShapedInternalRecsysPoliciesBertModelPolicyBertModelPolicyBERTModelPolicyConfig):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ShapedInternalRecsysPoliciesBertModelPolicyBertModelPolicyBERTModelPolicyConfig`")
        else:
            match += 1
        # validate data type: ShapedInternalRecsysPoliciesTwoTowerModelPolicyTwoTowerModelPolicyTwoTowerModelPolicyConfig
        if not isinstance(v, ShapedInternalRecsysPoliciesTwoTowerModelPolicyTwoTowerModelPolicyTwoTowerModelPolicyConfig):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ShapedInternalRecsysPoliciesTwoTowerModelPolicyTwoTowerModelPolicyTwoTowerModelPolicyConfig`")
        else:
            match += 1
        # validate data type: ShapedInternalRecsysPoliciesRisingPopularPolicyRisingPopularPolicyConfig
        if not isinstance(v, ShapedInternalRecsysPoliciesRisingPopularPolicyRisingPopularPolicyConfig):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ShapedInternalRecsysPoliciesRisingPopularPolicyRisingPopularPolicyConfig`")
        else:
            match += 1
        # validate data type: ShapedInternalRecsysPoliciesNgramModelPolicyNgramModelPolicyConfig
        if not isinstance(v, ShapedInternalRecsysPoliciesNgramModelPolicyNgramModelPolicyConfig):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ShapedInternalRecsysPoliciesNgramModelPolicyNgramModelPolicyConfig`")
        else:
            match += 1
        # validate data type: ShapedInternalRecsysPoliciesWidedeepModelPolicyWideDeepModelPolicyConfig
        if not isinstance(v, ShapedInternalRecsysPoliciesWidedeepModelPolicyWideDeepModelPolicyConfig):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ShapedInternalRecsysPoliciesWidedeepModelPolicyWideDeepModelPolicyConfig`")
        else:
            match += 1
        # validate data type: ShapedInternalRecsysPoliciesItem2vecModelPolicyItem2VecModelPolicyConfig
        if not isinstance(v, ShapedInternalRecsysPoliciesItem2vecModelPolicyItem2VecModelPolicyConfig):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ShapedInternalRecsysPoliciesItem2vecModelPolicyItem2VecModelPolicyConfig`")
        else:
            match += 1
        # validate data type: ShapedInternalRecsysPoliciesXgboostModelPolicyXGBoostModelPolicyConfig
        if not isinstance(v, ShapedInternalRecsysPoliciesXgboostModelPolicyXGBoostModelPolicyConfig):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ShapedInternalRecsysPoliciesXgboostModelPolicyXGBoostModelPolicyConfig`")
        else:
            match += 1
        # validate data type: ShapedInternalRecsysPoliciesBeeformerModelPolicyBeeformerModelPolicyBeeformerModelPolicyConfig
        if not isinstance(v, ShapedInternalRecsysPoliciesBeeformerModelPolicyBeeformerModelPolicyBeeformerModelPolicyConfig):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ShapedInternalRecsysPoliciesBeeformerModelPolicyBeeformerModelPolicyBeeformerModelPolicyConfig`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in ModelsInner with oneOf schemas: ShapedInternalRecsysPoliciesAlsModelPolicyALSModelPolicyConfig, ShapedInternalRecsysPoliciesBeeformerModelPolicyBeeformerModelPolicyBeeformerModelPolicyConfig, ShapedInternalRecsysPoliciesBertModelPolicyBertModelPolicyBERTModelPolicyConfig, ShapedInternalRecsysPoliciesElsaModelPolicyElsaModelPolicyELSAModelPolicyConfig, ShapedInternalRecsysPoliciesGsasrecModelPolicyGsasrecModelPolicyGSASRecModelPolicyConfig, ShapedInternalRecsysPoliciesItem2vecModelPolicyItem2VecModelPolicyConfig, ShapedInternalRecsysPoliciesLightgbmModelPolicyLightgbmModelPolicyLightGBMModelPolicyConfig, ShapedInternalRecsysPoliciesNgramModelPolicyNgramModelPolicyConfig, ShapedInternalRecsysPoliciesRisingPopularPolicyRisingPopularPolicyConfig, ShapedInternalRecsysPoliciesSasrecModelPolicySasrecModelPolicySASRecModelPolicyConfig, ShapedInternalRecsysPoliciesSvdModelPolicySVDModelPolicyConfig, ShapedInternalRecsysPoliciesTwoTowerModelPolicyTwoTowerModelPolicyTwoTowerModelPolicyConfig, ShapedInternalRecsysPoliciesWidedeepModelPolicyWideDeepModelPolicyConfig, ShapedInternalRecsysPoliciesXgboostModelPolicyXGBoostModelPolicyConfig. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in ModelsInner with oneOf schemas: ShapedInternalRecsysPoliciesAlsModelPolicyALSModelPolicyConfig, ShapedInternalRecsysPoliciesBeeformerModelPolicyBeeformerModelPolicyBeeformerModelPolicyConfig, ShapedInternalRecsysPoliciesBertModelPolicyBertModelPolicyBERTModelPolicyConfig, ShapedInternalRecsysPoliciesElsaModelPolicyElsaModelPolicyELSAModelPolicyConfig, ShapedInternalRecsysPoliciesGsasrecModelPolicyGsasrecModelPolicyGSASRecModelPolicyConfig, ShapedInternalRecsysPoliciesItem2vecModelPolicyItem2VecModelPolicyConfig, ShapedInternalRecsysPoliciesLightgbmModelPolicyLightgbmModelPolicyLightGBMModelPolicyConfig, ShapedInternalRecsysPoliciesNgramModelPolicyNgramModelPolicyConfig, ShapedInternalRecsysPoliciesRisingPopularPolicyRisingPopularPolicyConfig, ShapedInternalRecsysPoliciesSasrecModelPolicySasrecModelPolicySASRecModelPolicyConfig, ShapedInternalRecsysPoliciesSvdModelPolicySVDModelPolicyConfig, ShapedInternalRecsysPoliciesTwoTowerModelPolicyTwoTowerModelPolicyTwoTowerModelPolicyConfig, ShapedInternalRecsysPoliciesWidedeepModelPolicyWideDeepModelPolicyConfig, ShapedInternalRecsysPoliciesXgboostModelPolicyXGBoostModelPolicyConfig. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into ShapedInternalRecsysPoliciesElsaModelPolicyElsaModelPolicyELSAModelPolicyConfig
        try:
            instance.actual_instance = ShapedInternalRecsysPoliciesElsaModelPolicyElsaModelPolicyELSAModelPolicyConfig.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ShapedInternalRecsysPoliciesLightgbmModelPolicyLightgbmModelPolicyLightGBMModelPolicyConfig
        try:
            instance.actual_instance = ShapedInternalRecsysPoliciesLightgbmModelPolicyLightgbmModelPolicyLightGBMModelPolicyConfig.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ShapedInternalRecsysPoliciesAlsModelPolicyALSModelPolicyConfig
        try:
            instance.actual_instance = ShapedInternalRecsysPoliciesAlsModelPolicyALSModelPolicyConfig.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ShapedInternalRecsysPoliciesSvdModelPolicySVDModelPolicyConfig
        try:
            instance.actual_instance = ShapedInternalRecsysPoliciesSvdModelPolicySVDModelPolicyConfig.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ShapedInternalRecsysPoliciesSasrecModelPolicySasrecModelPolicySASRecModelPolicyConfig
        try:
            instance.actual_instance = ShapedInternalRecsysPoliciesSasrecModelPolicySasrecModelPolicySASRecModelPolicyConfig.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ShapedInternalRecsysPoliciesGsasrecModelPolicyGsasrecModelPolicyGSASRecModelPolicyConfig
        try:
            instance.actual_instance = ShapedInternalRecsysPoliciesGsasrecModelPolicyGsasrecModelPolicyGSASRecModelPolicyConfig.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ShapedInternalRecsysPoliciesBertModelPolicyBertModelPolicyBERTModelPolicyConfig
        try:
            instance.actual_instance = ShapedInternalRecsysPoliciesBertModelPolicyBertModelPolicyBERTModelPolicyConfig.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ShapedInternalRecsysPoliciesTwoTowerModelPolicyTwoTowerModelPolicyTwoTowerModelPolicyConfig
        try:
            instance.actual_instance = ShapedInternalRecsysPoliciesTwoTowerModelPolicyTwoTowerModelPolicyTwoTowerModelPolicyConfig.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ShapedInternalRecsysPoliciesRisingPopularPolicyRisingPopularPolicyConfig
        try:
            instance.actual_instance = ShapedInternalRecsysPoliciesRisingPopularPolicyRisingPopularPolicyConfig.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ShapedInternalRecsysPoliciesNgramModelPolicyNgramModelPolicyConfig
        try:
            instance.actual_instance = ShapedInternalRecsysPoliciesNgramModelPolicyNgramModelPolicyConfig.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ShapedInternalRecsysPoliciesWidedeepModelPolicyWideDeepModelPolicyConfig
        try:
            instance.actual_instance = ShapedInternalRecsysPoliciesWidedeepModelPolicyWideDeepModelPolicyConfig.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ShapedInternalRecsysPoliciesItem2vecModelPolicyItem2VecModelPolicyConfig
        try:
            instance.actual_instance = ShapedInternalRecsysPoliciesItem2vecModelPolicyItem2VecModelPolicyConfig.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ShapedInternalRecsysPoliciesXgboostModelPolicyXGBoostModelPolicyConfig
        try:
            instance.actual_instance = ShapedInternalRecsysPoliciesXgboostModelPolicyXGBoostModelPolicyConfig.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ShapedInternalRecsysPoliciesBeeformerModelPolicyBeeformerModelPolicyBeeformerModelPolicyConfig
        try:
            instance.actual_instance = ShapedInternalRecsysPoliciesBeeformerModelPolicyBeeformerModelPolicyBeeformerModelPolicyConfig.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into ModelsInner with oneOf schemas: ShapedInternalRecsysPoliciesAlsModelPolicyALSModelPolicyConfig, ShapedInternalRecsysPoliciesBeeformerModelPolicyBeeformerModelPolicyBeeformerModelPolicyConfig, ShapedInternalRecsysPoliciesBertModelPolicyBertModelPolicyBERTModelPolicyConfig, ShapedInternalRecsysPoliciesElsaModelPolicyElsaModelPolicyELSAModelPolicyConfig, ShapedInternalRecsysPoliciesGsasrecModelPolicyGsasrecModelPolicyGSASRecModelPolicyConfig, ShapedInternalRecsysPoliciesItem2vecModelPolicyItem2VecModelPolicyConfig, ShapedInternalRecsysPoliciesLightgbmModelPolicyLightgbmModelPolicyLightGBMModelPolicyConfig, ShapedInternalRecsysPoliciesNgramModelPolicyNgramModelPolicyConfig, ShapedInternalRecsysPoliciesRisingPopularPolicyRisingPopularPolicyConfig, ShapedInternalRecsysPoliciesSasrecModelPolicySasrecModelPolicySASRecModelPolicyConfig, ShapedInternalRecsysPoliciesSvdModelPolicySVDModelPolicyConfig, ShapedInternalRecsysPoliciesTwoTowerModelPolicyTwoTowerModelPolicyTwoTowerModelPolicyConfig, ShapedInternalRecsysPoliciesWidedeepModelPolicyWideDeepModelPolicyConfig, ShapedInternalRecsysPoliciesXgboostModelPolicyXGBoostModelPolicyConfig. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into ModelsInner with oneOf schemas: ShapedInternalRecsysPoliciesAlsModelPolicyALSModelPolicyConfig, ShapedInternalRecsysPoliciesBeeformerModelPolicyBeeformerModelPolicyBeeformerModelPolicyConfig, ShapedInternalRecsysPoliciesBertModelPolicyBertModelPolicyBERTModelPolicyConfig, ShapedInternalRecsysPoliciesElsaModelPolicyElsaModelPolicyELSAModelPolicyConfig, ShapedInternalRecsysPoliciesGsasrecModelPolicyGsasrecModelPolicyGSASRecModelPolicyConfig, ShapedInternalRecsysPoliciesItem2vecModelPolicyItem2VecModelPolicyConfig, ShapedInternalRecsysPoliciesLightgbmModelPolicyLightgbmModelPolicyLightGBMModelPolicyConfig, ShapedInternalRecsysPoliciesNgramModelPolicyNgramModelPolicyConfig, ShapedInternalRecsysPoliciesRisingPopularPolicyRisingPopularPolicyConfig, ShapedInternalRecsysPoliciesSasrecModelPolicySasrecModelPolicySASRecModelPolicyConfig, ShapedInternalRecsysPoliciesSvdModelPolicySVDModelPolicyConfig, ShapedInternalRecsysPoliciesTwoTowerModelPolicyTwoTowerModelPolicyTwoTowerModelPolicyConfig, ShapedInternalRecsysPoliciesWidedeepModelPolicyWideDeepModelPolicyConfig, ShapedInternalRecsysPoliciesXgboostModelPolicyXGBoostModelPolicyConfig. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], ShapedInternalRecsysPoliciesAlsModelPolicyALSModelPolicyConfig, ShapedInternalRecsysPoliciesBeeformerModelPolicyBeeformerModelPolicyBeeformerModelPolicyConfig, ShapedInternalRecsysPoliciesBertModelPolicyBertModelPolicyBERTModelPolicyConfig, ShapedInternalRecsysPoliciesElsaModelPolicyElsaModelPolicyELSAModelPolicyConfig, ShapedInternalRecsysPoliciesGsasrecModelPolicyGsasrecModelPolicyGSASRecModelPolicyConfig, ShapedInternalRecsysPoliciesItem2vecModelPolicyItem2VecModelPolicyConfig, ShapedInternalRecsysPoliciesLightgbmModelPolicyLightgbmModelPolicyLightGBMModelPolicyConfig, ShapedInternalRecsysPoliciesNgramModelPolicyNgramModelPolicyConfig, ShapedInternalRecsysPoliciesRisingPopularPolicyRisingPopularPolicyConfig, ShapedInternalRecsysPoliciesSasrecModelPolicySasrecModelPolicySASRecModelPolicyConfig, ShapedInternalRecsysPoliciesSvdModelPolicySVDModelPolicyConfig, ShapedInternalRecsysPoliciesTwoTowerModelPolicyTwoTowerModelPolicyTwoTowerModelPolicyConfig, ShapedInternalRecsysPoliciesWidedeepModelPolicyWideDeepModelPolicyConfig, ShapedInternalRecsysPoliciesXgboostModelPolicyXGBoostModelPolicyConfig]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


