from minjiang_client.com.request import request as request

def create_group(device_group_name: str, description: str, organization_id: int): ...
def get_group_list(page: int = 1, per_page: int = 10, org_id: int = None, show_hidden: bool = True): ...
def get_group_detail(device_group_name: str): ...
def create_device(type: str, device_name: str, description: str): ...
def delete_device(device_id: int, delete_status: bool): ...
def get_device_types(): ...
def get_devices_by_type(type: str, show_delete: bool = False, page: int = 1, per_page: int = 10): ...
def get_device_config(device_id_list: list): ...
def get_device_group_mapping_config(device_group_name: str): ...
def upload_device_config(device_id_list: list, resource_id_list: list): ...
def upload_device_group_mapping_config(device_group_name: str, resource_id: int): ...
def set_device_hidden(device_id: int, hidden: bool): ...
