from __future__ import annotations
from typing import Protocol, runtime_checkable, Tuple, Any
import numpy as np

@runtime_checkable
class Tape(Protocol):
    @property
    def shape(self) -> Tuple[int, int]: ...
    @property
    def dtype(self) -> np.dtype: ...
    @property
    def fs(self) -> float: ...
    @property
    def dx(self) -> float: ...
    @property
    def dx_unit(self) -> str: ...
    @property
    def dims(self) -> str: ...
    @property
    def ndim(self) -> int: ...
    def __getitem__(self, key: Any) -> np.ndarray: ...
    def close(self) -> None: ...