from _typeshed import Incomplete
from dataclasses import dataclass, field
from minjiang_client.com.device import get_group_detail as get_group_detail
from minjiang_client.com.organization import get_org_list as get_org_list
from minjiang_client.plugin.plugin_register import plugin_register as plugin_register
from minjiang_client.utils.local import get_default_config_dir as get_default_config_dir, get_default_language as get_default_language, get_gui_addr as get_gui_addr
from typing import Any

@dataclass
class UtilityRegistration:
    utility_name: str
    title: str = ...
    description: str = ...
    script_path: str = ...
    default_route: str = ...
    require_group_name: bool = ...
    plugin_name: str | None = ...
    builtin: bool = ...
    access_level: str = ...
    persistent: bool = ...
    icon_path: str = ...
    extra: dict[str, Any] = field(default_factory=dict)
    @classmethod
    def from_dict(cls, data: dict[str, Any], plugin_name: str | None = None) -> UtilityRegistration: ...
    def to_dict(self) -> dict[str, Any]: ...

class UtilityServerManager:
    servers: Incomplete
    port_pool: Incomplete
    used_ports: Incomplete
    lock: Incomplete
    monitor_thread: Incomplete
    running: bool
    utility_registry: Incomplete
    state_dir: Incomplete
    def __init__(self) -> None: ...
    def refresh_utility_registry(self) -> None: ...
    def start_utility_server(self, group_name: str, utility_name: str, utility_config: dict, utility_module_path: str = None) -> dict: ...
    def stop_utility_server(self, server_id: str) -> bool: ...
    def list_utility_servers(self) -> list[dict]: ...
    def list_all_running_utilities_grouped(self) -> dict[str, Any]: ...
    def get_utilities_without_group_name(self) -> list[dict]: ...
    def get_utilities_with_group_name(self, group_name: str) -> list[dict]: ...
    def cleanup_all_servers(self) -> None: ...

utility_manager: Incomplete
