from enum import Enum


class Area(str, Enum):
    AT = "AT"
    BE = "BE"
    BG = "BG"
    CH = "CH"
    CZ = "CZ"
    DE = "DE"
    DE_50HERTZ = "DE_50HERTZ"
    DE_AMPRION = "DE_AMPRION"
    DE_TENNET = "DE_TENNET"
    DE_TRANSNETBW = "DE_TRANSNETBW"
    DK1 = "DK1"
    DK2 = "DK2"
    EE = "EE"
    ES = "ES"
    FI = "FI"
    FR = "FR"
    GR = "GR"
    HR = "HR"
    HU = "HU"
    IT_CALABRIA = "IT_CALABRIA"
    IT_CENTER_NORTH = "IT_CENTER_NORTH"
    IT_CENTER_SOUTH = "IT_CENTER_SOUTH"
    IT_NORTH = "IT_NORTH"
    IT_SARDINIA = "IT_SARDINIA"
    IT_SICILY = "IT_SICILY"
    IT_SOUTH = "IT_SOUTH"
    LT = "LT"
    LV = "LV"
    NL = "NL"
    NO1 = "NO1"
    NO2 = "NO2"
    NO3 = "NO3"
    NO4 = "NO4"
    NO5 = "NO5"
    PL = "PL"
    PT = "PT"
    RO = "RO"
    RS = "RS"
    SE1 = "SE1"
    SE2 = "SE2"
    SE3 = "SE3"
    SE4 = "SE4"
    SI = "SI"
    SK = "SK"

    def __str__(self) -> str:
        return str(self.value)
