from typing import List

def unsafe_hs_pyeggp_version() -> str: ...
def unsafe_hs_pyeggp_main() -> int: ...
def unsafe_hs_pyeggp_run(dataset: str, gen: int, nPop: int, maxSize: int, nTournament: int, pc: float, pm: float, nonterminals: str, loss: str, optIter: int, optRepeat: int, nParams: int, split: int, max_time: int, simplify: int, trace : int, generational : int, dumpTo: str, loadFrom: str, varnames: str) -> str: ...
def unsafe_hs_pyeggp_init(args: List[str]) -> None: ...
def unsafe_hs_pyeggp_exit() -> None: ...
