from pyarrow import Array, DataType, Scalar

class Expr:
    """Low level expression class."""

def aux(name: str, data_type: DataType) -> Expr: ...

# Array is correct (there is no ArrayData), see the table here:
# https://arrow.apache.org/rust/arrow_pyarrow/index.html
def scalar(array: Array[Scalar[DataType]]) -> Expr: ...
def not_(expr: Expr) -> Expr: ...
def is_null(expr: Expr) -> Expr: ...
def binary(op: str, expr: Expr, Expr: Expr) -> Expr: ...
def cast(_expr: Expr, _data_type: DataType) -> Expr: ...
def array_lit(array: Array[Scalar[DataType]]) -> Expr: ...
