"""Configuration management for MemoryLayer.ai using Pydantic Settings."""

from enum import Enum
from pathlib import Path

MEMORYLAYER_DATA_DIR = 'MEMORYLAYER_DATA_DIR'
DEFAULT_MEMORYLAYER_DATA_DIR = Path.home() / ".memorylayer" / "data"


class EmbeddingProviderType(str, Enum):
    """Available embedding provider types."""

    QWEN3_VL = "qwen3-vl"  # Qwen3-VL-Embedding-2B (default, self-hosted, multimodal)
    VLLM = "vllm"  # vLLM backend (self-hosted, high-performance, multimodal)
    COLPALI = "colpali"  # ColPali multi-vector (self-hosted, multimodal)
    OPENAI = "openai"  # OpenAI API (cloud, text-only)
    LOCAL = "local"  # sentence-transformers (self-hosted, text-only fallback)
    MOCK = "mock"  # Mock provider for testing only (deterministic hash-based)


MEMORYLAYER_EMBEDDING_PROVIDER = 'MEMORYLAYER_EMBEDDING_PROVIDER'
DEFAULT_MEMORYLAYER_EMBEDDING_PROVIDER = EmbeddingProviderType.QWEN3_VL
MEMORYLAYER_EMBEDDING_MODEL = 'MEMORYLAYER_EMBEDDING_MODEL'
MEMORYLAYER_EMBEDDING_DIMENSIONS = 'MEMORYLAYER_EMBEDDING_DIMENSIONS'

MEMORYLAYER_EMBEDDING_SERVICE = 'MEMORYLAYER_EMBEDDING_SERVICE'
DEFAULT_MEMORYLAYER_EMBEDDING_SERVICE = 'default'

MEMORYLAYER_STORAGE_BACKEND = 'MEMORYLAYER_STORAGE_BACKEND'
DEFAULT_MEMORYLAYER_STORAGE_BACKEND = 'sqlite'

# Service configuration
MEMORYLAYER_MEMORY_SERVICE = 'MEMORYLAYER_MEMORY_SERVICE'
DEFAULT_MEMORYLAYER_MEMORY_SERVICE = 'default'

MEMORYLAYER_REFLECT_SERVICE = 'MEMORYLAYER_REFLECT_SERVICE'
DEFAULT_MEMORYLAYER_REFLECT_SERVICE = 'default'

MEMORYLAYER_SESSION_SERVICE = 'MEMORYLAYER_SESSION_SERVICE'
DEFAULT_MEMORYLAYER_SESSION_SERVICE = 'default'

MEMORYLAYER_WORKSPACE_SERVICE = 'MEMORYLAYER_WORKSPACE_SERVICE'
DEFAULT_MEMORYLAYER_WORKSPACE_SERVICE = 'default'

MEMORYLAYER_ASSOCIATION_SERVICE = 'MEMORYLAYER_ASSOCIATION_SERVICE'
DEFAULT_MEMORYLAYER_ASSOCIATION_SERVICE = 'default'

MEMORYLAYER_SQLITE_STORAGE_PATH = 'MEMORYLAYER_SQLITE_STORAGE_PATH'
DEFAULT_MEMORYLAYER_SQLITE_STORAGE_PATH = "memorylayer.db"

MEMORYLAYER_SERVER_HOST = 'MEMORYLAYER_SERVER_HOST'
DEFAULT_MEMORYLAYER_SERVER_HOST = '0.0.0.0'
MEMORYLAYER_SERVER_PORT = 'MEMORYLAYER_SERVER_PORT'
DEFAULT_MEMORYLAYER_SERVER_PORT = 8080

# ============================================
# Authorization Service
# ============================================
MEMORYLAYER_AUTHORIZATION_SERVICE = 'MEMORYLAYER_AUTHORIZATION_SERVICE'
DEFAULT_MEMORYLAYER_AUTHORIZATION_SERVICE = 'default'  # Open permissions (allow all)

# ============================================
# LLM Service
# ============================================
MEMORYLAYER_LLM_PROVIDER = 'MEMORYLAYER_LLM_PROVIDER'
DEFAULT_MEMORYLAYER_LLM_PROVIDER = 'noop'  # No LLM by default

MEMORYLAYER_LLM_SERVICE = 'MEMORYLAYER_LLM_SERVICE'
DEFAULT_MEMORYLAYER_LLM_SERVICE = 'default'

# OpenAI-compatible provider settings
MEMORYLAYER_LLM_OPENAI_API_KEY = 'MEMORYLAYER_LLM_OPENAI_API_KEY'
MEMORYLAYER_LLM_OPENAI_BASE_URL = 'MEMORYLAYER_LLM_OPENAI_BASE_URL'
DEFAULT_LLM_OPENAI_BASE_URL = 'https://api.openai.com/v1'
MEMORYLAYER_LLM_OPENAI_MODEL = 'MEMORYLAYER_LLM_OPENAI_MODEL'
DEFAULT_LLM_OPENAI_MODEL = 'gpt-4o-mini'

# ============================================
# Cache Service
# ============================================
MEMORYLAYER_CACHE_SERVICE = 'MEMORYLAYER_CACHE_SERVICE'
DEFAULT_MEMORYLAYER_CACHE_SERVICE = 'default'  # No-op cache (returns None)

# Redis settings (for SaaS implementations)
MEMORYLAYER_CACHE_REDIS_URL = 'MEMORYLAYER_CACHE_REDIS_URL'
DEFAULT_CACHE_REDIS_URL = 'redis://localhost:6379/0'
MEMORYLAYER_CACHE_REDIS_PREFIX = 'MEMORYLAYER_CACHE_REDIS_PREFIX'
DEFAULT_CACHE_REDIS_PREFIX = 'ml:'
