# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from cdpify.client import CDPClient

from .commands import (
    IndexedDBCommand,
    ClearObjectStoreParams,
    DeleteDatabaseParams,
    DeleteObjectStoreEntriesParams,
    GetMetadataParams,
    GetMetadataResult,
    RequestDataParams,
    RequestDataResult,
    RequestDatabaseNamesParams,
    RequestDatabaseNamesResult,
    RequestDatabaseParams,
    RequestDatabaseResult,
)

from .types import (
    KeyRange,
)

if TYPE_CHECKING:
    from cdpify.domains import storage


class IndexedDBClient:
    def __init__(self, client: CDPClient) -> None:
        self._client = client

    async def clear_object_store(
        self,
        *,
        security_origin: str | None = None,
        storage_key: str | None = None,
        storage_bucket: storage.StorageBucket | None = None,
        database_name: str,
        object_store_name: str,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        """
        Clears all entries from an object store.
        """
        params = ClearObjectStoreParams(
            security_origin=security_origin,
            storage_key=storage_key,
            storage_bucket=storage_bucket,
            database_name=database_name,
            object_store_name=object_store_name,
        )

        result = await self._client.send_raw(
            method=IndexedDBCommand.CLEAR_OBJECT_STORE,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def delete_database(
        self,
        *,
        security_origin: str | None = None,
        storage_key: str | None = None,
        storage_bucket: storage.StorageBucket | None = None,
        database_name: str,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        """
        Deletes a database.
        """
        params = DeleteDatabaseParams(
            security_origin=security_origin,
            storage_key=storage_key,
            storage_bucket=storage_bucket,
            database_name=database_name,
        )

        result = await self._client.send_raw(
            method=IndexedDBCommand.DELETE_DATABASE,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def delete_object_store_entries(
        self,
        *,
        security_origin: str | None = None,
        storage_key: str | None = None,
        storage_bucket: storage.StorageBucket | None = None,
        database_name: str,
        object_store_name: str,
        key_range: KeyRange,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        """
        Delete a range of entries from an object store
        """
        params = DeleteObjectStoreEntriesParams(
            security_origin=security_origin,
            storage_key=storage_key,
            storage_bucket=storage_bucket,
            database_name=database_name,
            object_store_name=object_store_name,
            key_range=key_range,
        )

        result = await self._client.send_raw(
            method=IndexedDBCommand.DELETE_OBJECT_STORE_ENTRIES,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def disable(
        self,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        """
        Disables events from backend.
        """
        result = await self._client.send_raw(
            method=IndexedDBCommand.DISABLE,
            params=None,
            session_id=session_id,
        )
        return result

    async def enable(
        self,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        """
        Enables events from backend.
        """
        result = await self._client.send_raw(
            method=IndexedDBCommand.ENABLE,
            params=None,
            session_id=session_id,
        )
        return result

    async def request_data(
        self,
        *,
        security_origin: str | None = None,
        storage_key: str | None = None,
        storage_bucket: storage.StorageBucket | None = None,
        database_name: str,
        object_store_name: str,
        index_name: str | None = None,
        skip_count: int,
        page_size: int,
        key_range: KeyRange | None = None,
        session_id: str | None = None,
    ) -> RequestDataResult:
        """
        Requests data from object store or index.
        """
        params = RequestDataParams(
            security_origin=security_origin,
            storage_key=storage_key,
            storage_bucket=storage_bucket,
            database_name=database_name,
            object_store_name=object_store_name,
            index_name=index_name,
            skip_count=skip_count,
            page_size=page_size,
            key_range=key_range,
        )

        result = await self._client.send_raw(
            method=IndexedDBCommand.REQUEST_DATA,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return RequestDataResult.from_cdp(result)

    async def get_metadata(
        self,
        *,
        security_origin: str | None = None,
        storage_key: str | None = None,
        storage_bucket: storage.StorageBucket | None = None,
        database_name: str,
        object_store_name: str,
        session_id: str | None = None,
    ) -> GetMetadataResult:
        """
        Gets metadata of an object store.
        """
        params = GetMetadataParams(
            security_origin=security_origin,
            storage_key=storage_key,
            storage_bucket=storage_bucket,
            database_name=database_name,
            object_store_name=object_store_name,
        )

        result = await self._client.send_raw(
            method=IndexedDBCommand.GET_METADATA,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return GetMetadataResult.from_cdp(result)

    async def request_database(
        self,
        *,
        security_origin: str | None = None,
        storage_key: str | None = None,
        storage_bucket: storage.StorageBucket | None = None,
        database_name: str,
        session_id: str | None = None,
    ) -> RequestDatabaseResult:
        """
        Requests database with given name in given frame.
        """
        params = RequestDatabaseParams(
            security_origin=security_origin,
            storage_key=storage_key,
            storage_bucket=storage_bucket,
            database_name=database_name,
        )

        result = await self._client.send_raw(
            method=IndexedDBCommand.REQUEST_DATABASE,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return RequestDatabaseResult.from_cdp(result)

    async def request_database_names(
        self,
        *,
        security_origin: str | None = None,
        storage_key: str | None = None,
        storage_bucket: storage.StorageBucket | None = None,
        session_id: str | None = None,
    ) -> RequestDatabaseNamesResult:
        """
        Requests database names for given security origin.
        """
        params = RequestDatabaseNamesParams(
            security_origin=security_origin,
            storage_key=storage_key,
            storage_bucket=storage_bucket,
        )

        result = await self._client.send_raw(
            method=IndexedDBCommand.REQUEST_DATABASE_NAMES,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return RequestDatabaseNamesResult.from_cdp(result)
