"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .chain import Chain
from compass_api_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from compass_api_sdk.utils import FieldMetadata, QueryParamMetadata
from pydantic import model_serializer
from typing_extensions import Annotated, NotRequired, TypedDict


class V2EarnAaveMarketsRequestTypedDict(TypedDict):
    chain: NotRequired[Nullable[Chain]]
    r"""Optional chain filter. If not provided, returns rates for all chains."""


class V2EarnAaveMarketsRequest(BaseModel):
    chain: Annotated[
        OptionalNullable[Chain],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Optional chain filter. If not provided, returns rates for all chains."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["chain"])
        nullable_fields = set(["chain"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
