"""
    COPYRIGHT (c) 2024 by Featuremine Corporation.
    This software has been provided pursuant to a License Agreement
    containing restrictions on its use. This software contains valuable
    trade secrets and proprietary information of Featuremine Corporation
    and is protected by law. It may not be copied or distributed in any
    form or medium, disclosed to third parties, reverse engineered or used
    in any manner not provided for in said License Agreement except with
    the prior written authorization from Featuremine Corporation.
"""

from typing import Tuple, List

class sys:
    def __init__(self) -> None: ...
    def get_paths(self) -> List[str]: ...
    def set_paths(self, paths: List[str]) -> None: ...
    def get_module(self, name: str) -> int: ...
    def get_component_type(self, module: int, name: str) -> int: ...
    def get_module_filepath(self, module: int) -> str: ...
    def get_component_type_spec(self, component_type: int) -> List[Tuple[str, str, bool]]: ...

class reactor:
    def __init__(self) -> None: ...
    def run(self, live: bool, checksignals: bool) -> None: ...
    def run_once(self, now: int) -> bool: ...
    def stop(self) -> None: ...
    def sched(self) -> int: ...

class component:
    def __init__(self, reactor: reactor, component_type: int, inputs: list, config: dict) -> None: ...
    def out_idx(self, name: str) -> int: ...
    def out_sz(self) -> int: ...
