FMD_ITERATIONS = 1867
FMD_BLOCK_SIZE = 16

FMD_ARGON2_T = 1
FMD_ARGON2_P = 4
FMD_ARGON2_M = 131072
FMD_ARGON2_HASH_LENGTH = 32
FMD_ARGON2_SALT_LENGTH = 16

FMD_AES_GCM_IV_SIZE_BYTES = 12
FMD_AES_GCM_KEY_SIZE_BYTES = 32

FMD_RSA_KEY_SIZE_BITS = 3072
FMD_RSA_KEY_SIZE_BYTES = FMD_RSA_KEY_SIZE_BITS // 8

FMD_CONTEXT_PREFIX = 'context:'
FMD_CONTEXT_STRING_LOGIN = f'{FMD_CONTEXT_PREFIX}loginAuthentication'
FMD_CONTEXT_STRING_ASYM_KEY_WRAP = f'{FMD_CONTEXT_PREFIX}asymmetricKeyWrap'

PRIVATE_KEY_PREFIX = '-----BEGIN PRIVATE KEY-----\n'
PRIVATE_KEY_SUFFIX = '\n-----END PRIVATE KEY-----\n'
