import smtplib
from _typeshed import Incomplete
from email import encoders as encoders
from email.mime.base import MIMEBase as MIMEBase
from email.mime.multipart import MIMEMultipart

class CLASS_MailSender:
    CVms_SMTP_Server: Incomplete
    CVmi_Port: Incomplete
    CVms_Account: Incomplete
    CVms_Password: Incomplete
    CVmb_UseSSL: Incomplete
    OnAfterSendSuccess: Callable[[str], None] | None
    OnAfterSendFailure: Callable[[str], None] | None
    CVobj_Server: smtplib.SMTP | None
    def __init__(self, Pms_SMTP_Server: str, Pmi_Port: int, Pms_Account: str, Pms_Password: str, Pmb_UseSSL: bool = True) -> None: ...
    def CUF_Open(self, Pms_Account: str, Pms_PassWD: str, Pmi_TimeOut: int = 10) -> bool: ...
    def CUF_Close(self) -> None: ...
    def CUF_Reconnect(self, Pmi_TimeOut: int = 10) -> bool: ...
    def CUF_CreateMessage(self, Pms_Subject: str, Pms_BodyText: str, Pms_BodyHTML: str | None = None, Pms_From: str | None = None, Pobj_To: list[str] | None = None, Pobj_Cc: list[str] | None = None, Pobj_Bcc: list[str] | None = None, Pobj_Attachments: list[str] | None = None) -> MIMEMultipart: ...
    def CUF_SendMail(self, Pms_Subject: str, Pms_BodyText: str, Pms_BodyHTML: str | None, Pobj_To: list[str], Pms_From: str | None = None, Pobj_Cc: list[str] | None = None, Pobj_Bcc: list[str] | None = None, Pobj_Attachments: list[str] | None = None) -> bool: ...

def GE_OnSendSuccess(Pms_Subject: str): ...
def GE_OnSendFailure(Pms_ErrMsg: str): ...
