"""2025.5.0 ajout deposit invoice

Create Date: 2025-04-14 12:42:22.104708

"""

# revision identifiers, used by Alembic.

# Revision ID:
revision = "88700e5b4360"

# Revises (previous revision or revisions):
down_revision = "0cf0aaec7599"

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql


def update_database_structure():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("invoice", sa.Column("is_deposit", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def migrate_datas():
    from alembic.context import get_bind
    from zope.sqlalchemy import mark_changed

    from caerp.models.base import DBSESSION

    session = DBSESSION()
    conn = get_bind()
    conn.execute("UPDATE invoice SET is_deposit = 0")
    mark_changed(session)
    session.flush()


def upgrade():
    update_database_structure()
    migrate_datas()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("invoice", "is_deposit")
