from typing import Type
from ._base import Action, PendingAction
from .core_status import CoreStatus
from .login import Login
from .logoff import Logoff
from .originate import Originate
from .ping import Ping

from ...operation import NotImplementedOperation

action_map: dict[str, Type[Action] | Type[NotImplementedOperation]] = {
    'AGI': NotImplementedOperation,
    'AOCMessage': NotImplementedOperation,
    'AbsoluteTimeout': NotImplementedOperation,
    'AgentLogoff': NotImplementedOperation,
    'Agents': NotImplementedOperation,
    'Atxfer': NotImplementedOperation,
    'BlindTransfer': NotImplementedOperation,
    'Bridge': NotImplementedOperation,
    'BridgeDestroy': NotImplementedOperation,
    'BridgeInfo': NotImplementedOperation,
    'BridgeKick': NotImplementedOperation,
    'BridgeList': NotImplementedOperation,
    'BridgeTechnologyList': NotImplementedOperation,       
    'BridgeTechnologySuspend': NotImplementedOperation,    
    'BridgeTechnologyUnsuspend': NotImplementedOperation,  
    'CancelAtxfer': NotImplementedOperation,
    'Challenge': NotImplementedOperation,
    'Command': NotImplementedOperation,
    'ConfbridgeKick': NotImplementedOperation,
    'ConfbridgeList': NotImplementedOperation,
    'ConfbridgeListRooms': NotImplementedOperation,        
    'ConfbridgeLock': NotImplementedOperation,
    'ConfbridgeMute': NotImplementedOperation,
    'ConfbridgeSetSingleVideoSrc': NotImplementedOperation,
    'ConfbridgeStartRecord': NotImplementedOperation,      
    'ConfbridgeStopRecord': NotImplementedOperation,       
    'ConfbridgeUnlock': NotImplementedOperation,
    'ConfbridgeUnmute': NotImplementedOperation,
    'ControlPlayback': NotImplementedOperation,
    'CoreSettings': NotImplementedOperation,
    'CoreShowChannelMap': NotImplementedOperation,
    'CoreShowChannels': NotImplementedOperation,
    'CoreStatus': CoreStatus,
    'CreateConfig': NotImplementedOperation,
    'DAHDIDNDoff': NotImplementedOperation,
    'DAHDIDNDon': NotImplementedOperation,
    'DAHDIDialOffhook': NotImplementedOperation,
    'DAHDIHangup': NotImplementedOperation,
    'DAHDIRestart': NotImplementedOperation,
    'DAHDIShowChannels': NotImplementedOperation,
    'DAHDIShowStatus': NotImplementedOperation,
    'DAHDITransfer': NotImplementedOperation,
    'DBDel': NotImplementedOperation,
    'DBDelTree': NotImplementedOperation,
    'DBGet': NotImplementedOperation,
    'DBGetTree': NotImplementedOperation,
    'DBPut': NotImplementedOperation,
    'DeviceStateList': NotImplementedOperation,
    'DialplanExtensionAdd': NotImplementedOperation,
    'DialplanExtensionRemove': NotImplementedOperation,
    'Events': NotImplementedOperation,
    'ExtensionState': NotImplementedOperation,
    'ExtensionStateList': NotImplementedOperation,
    'FAXSession': NotImplementedOperation,
    'FAXSessions': NotImplementedOperation,
    'FAXStats': NotImplementedOperation,
    'Filter': NotImplementedOperation,
    'GetConfig': NotImplementedOperation,
    'GetConfigJSON': NotImplementedOperation,
    'Getvar': NotImplementedOperation,
    'Hangup': NotImplementedOperation,
    'IAXnetstats': NotImplementedOperation,
    'IAXpeerlist': NotImplementedOperation,
    'IAXpeers': NotImplementedOperation,
    'IAXregistry': NotImplementedOperation,
    'JabberSend': NotImplementedOperation,
    'ListCategories': NotImplementedOperation,
    'ListCommands': NotImplementedOperation,
    'LocalOptimizeAway': NotImplementedOperation,
    'LoggerRotate': NotImplementedOperation,
    'Login': Login,
    'Logoff': Logoff,
    'MWIDelete': NotImplementedOperation,
    'MWIGet': NotImplementedOperation,
    'MWIUpdate': NotImplementedOperation,
    'MailboxCount': NotImplementedOperation,
    'MailboxStatus': NotImplementedOperation,
    'MeetmeList': NotImplementedOperation,
    'MeetmeListRooms': NotImplementedOperation,
    'MeetmeMute': NotImplementedOperation,
    'MeetmeUnmute': NotImplementedOperation,
    'MessageSend': NotImplementedOperation,
    'MixMonitor': NotImplementedOperation,
    'MixMonitorMute': NotImplementedOperation,
    'ModuleCheck': NotImplementedOperation,
    'ModuleLoad': NotImplementedOperation,
    'MuteAudio': NotImplementedOperation,
    'Originate': Originate,
    'PJSIPHangup': NotImplementedOperation,
    'PJSIPNotify': NotImplementedOperation,
    'PJSIPQualify': NotImplementedOperation,
    'PJSIPRegister': NotImplementedOperation,
    'PJSIPShowAors': NotImplementedOperation,
    'PJSIPShowAuths': NotImplementedOperation,
    'PJSIPShowContacts': NotImplementedOperation,
    'PJSIPShowEndpoint': NotImplementedOperation,
    'PJSIPShowEndpoints': NotImplementedOperation,
    'PJSIPShowRegistrationInboundContactStatuses': NotImplementedOperation,
    'PJSIPShowRegistrationsInbound': NotImplementedOperation,
    'PJSIPShowRegistrationsOutbound': NotImplementedOperation,
    'PJSIPShowResourceLists': NotImplementedOperation,
    'PJSIPShowSubscriptionsInbound': NotImplementedOperation,
    'PJSIPShowSubscriptionsOutbound': NotImplementedOperation,
    'PJSIPUnregister': NotImplementedOperation,
    'PRIDebugFileSet': NotImplementedOperation,
    'PRIDebugFileUnset': NotImplementedOperation,
    'PRIDebugSet': NotImplementedOperation,
    'PRIShowSpans': NotImplementedOperation,
    'Park': NotImplementedOperation,
    'ParkedCalls': NotImplementedOperation,
    'Parkinglots': NotImplementedOperation,
    'Ping': Ping,
    'PlayDTMF': NotImplementedOperation,
    'PlayMF': NotImplementedOperation,
    'PresenceState': NotImplementedOperation,
    'PresenceStateList': NotImplementedOperation,
    'QueueAdd': NotImplementedOperation,
    'QueueChangePriorityCaller': NotImplementedOperation,
    'QueueLog': NotImplementedOperation,
    'QueueMemberRingInUse': NotImplementedOperation,
    'QueuePause': NotImplementedOperation,
    'QueuePenalty': NotImplementedOperation,
    'QueueReload': NotImplementedOperation,
    'QueueRemove': NotImplementedOperation,
    'QueueReset': NotImplementedOperation,
    'QueueRule': NotImplementedOperation,
    'QueueStatus': NotImplementedOperation,
    'QueueSummary': NotImplementedOperation,
    'QueueWithdrawCaller': NotImplementedOperation,
    'Redirect': NotImplementedOperation,
    'Reload': NotImplementedOperation,
    'SendFlash': NotImplementedOperation,
    'SendText': NotImplementedOperation,
    'Setvar': NotImplementedOperation,
    'ShowDialPlan': NotImplementedOperation,
    'SorceryMemoryCacheExpire': NotImplementedOperation,
    'SorceryMemoryCacheExpireObject': NotImplementedOperation,
    'SorceryMemoryCachePopulate': NotImplementedOperation,
    'SorceryMemoryCacheStale': NotImplementedOperation,
    'SorceryMemoryCacheStaleObject': NotImplementedOperation,
    'Status': NotImplementedOperation,
    'StopMixMonitor': NotImplementedOperation,
    'UpdateConfig': NotImplementedOperation,
    'UserEvent': NotImplementedOperation,
    'VoicemailBoxSummary': NotImplementedOperation,
    'VoicemailForward': NotImplementedOperation,
    'VoicemailMove': NotImplementedOperation,
    'VoicemailRefresh': NotImplementedOperation,
    'VoicemailRemove': NotImplementedOperation,
    'VoicemailUserStatus': NotImplementedOperation,
    'VoicemailUsersList': NotImplementedOperation,
    'WaitEvent': NotImplementedOperation,
}

__all__ = [
    'Action',
    'PendingAction',
    'action_map',
    'CoreStatus',
    'Login',
    'Logoff',
    'Ping',
]