from minjiang_client.com.request import request as request

def set_oss_auth(if_global: bool, auth_text: str, disabled: bool = False, organization_id: int = None): ...
def get_global(): ...
def get_oss_config(organization_id: int): ...
def get_resource_info(resource_id_list: list): ...
def get_plugin_resource_info(plugin_id: int): ...
def get_plugin_version_resource_info(plugin_version_id: int): ...
def add_resource(file_name: str, file_format: str, uri: str, file_type: str, source: str, device_group_id: int = None, device_group_name: str = None, organization_id: int = None): ...
def add_plugin_resource(file_name: str, file_format: str, uri: str, source: str): ...
