from _typeshed import Incomplete

class BaseVectorDistance:
    left: Incomplete
    right: Incomplete
    def __init__(self, left: str | list[float], right: str | list[float]) -> None: ...

class L2Distance(BaseVectorDistance): ...
class CosineDistance(BaseVectorDistance): ...
class InnerProduct(BaseVectorDistance): ...
class L1Distance(BaseVectorDistance): ...
