from typing import Any, Type, Union, overload

from ..core.pandera import PaDataFrame
from .variables import _SCHEMA, _T, DFVar, SVar

@overload
def sconsume(var: Union[_T, SVar[_T]], /) -> _T: ...
@overload
def sconsume(var: DFVar[_SCHEMA], /) -> PaDataFrame[_SCHEMA]: ...
@overload
def sconsume(var: None = ...) -> Any: ...
@overload
def sproduce(var: Union[Type[_T], SVar[_T]], /) -> _T: ...
@overload
def sproduce(var: DFVar[_SCHEMA], /) -> PaDataFrame[_SCHEMA]: ...
@overload
def sproduce(var: None = ...) -> Any: ...
@overload
def stransform(var: Union[Type[_T], SVar[_T]], /) -> _T: ...
@overload
def stransform(var: DFVar[_SCHEMA], /) -> PaDataFrame[_SCHEMA]: ...
@overload
def stransform(var: None = ...) -> Any: ...
