"""Adapter SDK for integrating Baguette with external agent runtimes."""

from .sdk import AdapterContext, AdapterHooks, AdapterPipeline
from .langgraph import (
    LangGraphAdapter,
    LangGraphAdapterError,
    LangGraphContext,
    LANGGRAPH_CONTEXT_KEY,
    LANGGRAPH_CONTEXT_TOKEN_KEY,
    LANGGRAPH_CORRELATION_ID_KEY,
    LANGGRAPH_EDGE_PATH_KEY,
    LANGGRAPH_ERROR_TRACE_DECISION,
    LANGGRAPH_GRAPH_TRACE_DECISION,
    LANGGRAPH_METRIC_MEMORY_STAGED,
    LANGGRAPH_METRIC_TX_COMMITTED,
    LANGGRAPH_METRIC_TX_ROLLED_BACK,
    LANGGRAPH_NODE_TRACE_DECISION,
    MetricsHook,
    merge_context,
    merge_context_token,
)
from .langchain import (
    LangChainAdapter,
    LangChainAdapterError,
    LangChainCallbackHandler,
    LangChainContext,
    LANGCHAIN_CHAIN_TRACE_DECISION,
    LANGCHAIN_CONTEXT_KEY,
    LANGCHAIN_CONTEXT_TOKEN_KEY,
    LANGCHAIN_CORRELATION_ID_KEY,
    LANGCHAIN_ERROR_TRACE_DECISION,
    LANGCHAIN_LLM_TRACE_DECISION,
    LANGCHAIN_TOOL_TRACE_DECISION,
)

__all__ = [
    "AdapterContext",
    "AdapterHooks",
    "AdapterPipeline",
    "LangGraphAdapter",
    "LangGraphAdapterError",
    "LangGraphContext",
    "LANGGRAPH_CONTEXT_KEY",
    "LANGGRAPH_CONTEXT_TOKEN_KEY",
    "LANGGRAPH_CORRELATION_ID_KEY",
    "LANGGRAPH_EDGE_PATH_KEY",
    "LANGGRAPH_ERROR_TRACE_DECISION",
    "LANGGRAPH_GRAPH_TRACE_DECISION",
    "LANGGRAPH_METRIC_MEMORY_STAGED",
    "LANGGRAPH_METRIC_TX_COMMITTED",
    "LANGGRAPH_METRIC_TX_ROLLED_BACK",
    "LANGGRAPH_NODE_TRACE_DECISION",
    "MetricsHook",
    "merge_context",
    "merge_context_token",
    "LangChainAdapter",
    "LangChainAdapterError",
    "LangChainCallbackHandler",
    "LangChainContext",
    "LANGCHAIN_CHAIN_TRACE_DECISION",
    "LANGCHAIN_CONTEXT_KEY",
    "LANGCHAIN_CONTEXT_TOKEN_KEY",
    "LANGCHAIN_CORRELATION_ID_KEY",
    "LANGCHAIN_ERROR_TRACE_DECISION",
    "LANGCHAIN_LLM_TRACE_DECISION",
    "LANGCHAIN_TOOL_TRACE_DECISION",
]
