# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Tethering Domain."""

from .commands import BindParams, TetheringCommand, UnbindParams

from .events import AcceptedEvent, TetheringEvent

from .client import TetheringClient

__all__ = [
    "AcceptedEvent",
    "BindParams",
    "TetheringClient",
    "TetheringCommand",
    "TetheringEvent",
    "UnbindParams",
]
