from _typeshed import Incomplete
from minjiang_client.experiment.experiment import Experiment as Experiment, Result as Result
from minjiang_client.experiment.fitter import Fitter as Fitter
from minjiang_client.group.cloud_group import CloudGroup as CloudGroup
from minjiang_client.utils.json_database import JSONDatatable as JSONDatatable
from tkinter import colorchooser as colorchooser

class FittingViewer:
    root: Incomplete
    fitter: Incomplete
    exp_id: Incomplete
    result: Incomplete
    exp: Incomplete
    kwargs: Incomplete
    img_filename: Incomplete
    json_filename: Incomplete
    image: Incomplete
    tk_image: Incomplete
    image_id: Incomplete
    image_scale: float
    image_position: Incomplete
    drag_start: Incomplete
    def __init__(self, json_filename=None, img_filename=None, fitter=None, exp_id=None, exp=None, result=None, **kwargs) -> None: ...
    loading_window: Incomplete
    def show_loading_screen(self) -> None: ...
    def fitting_thread(self) -> None: ...
    def start_fitting_process(self) -> None: ...
    def finish_loading(self, json_filename, img_filename) -> None: ...
    def show_fitting_error(self, error_msg) -> None: ...
    tab_control: Incomplete
    img_tab: Incomplete
    db_tab: Incomplete
    def initialize_viewer(self) -> None: ...
    def create_main_menu(self) -> None: ...
    db: Incomplete
    current_table: Incomplete
    db_main_frame: Incomplete
    table_frame: Incomplete
    table_combobox: Incomplete
    refresh_btn: Incomplete
    table_view_frame: Incomplete
    db_status_var: Incomplete
    db_status_bar: Incomplete
    tree_container: Incomplete
    tree_scroll_y: Incomplete
    hscroll_frame: Incomplete
    tree_scroll_x: Incomplete
    tree: Incomplete
    def setup_database_viewer(self, filename=None) -> None: ...
    def create_db_menu(self, parent) -> None: ...
    pen_color: str
    pen_size: int
    eraser_on: bool
    last_x: Incomplete
    last_y: Incomplete
    draw: Incomplete
    img_main_frame: Incomplete
    canvas_frame: Incomplete
    hscroll: Incomplete
    vscroll: Incomplete
    canvas: Incomplete
    control_frame: Incomplete
    img_status_var: Incomplete
    img_status_bar: Incomplete
    def setup_image_editor(self, filename=None): ...
    def load_image_file(self, filename) -> None: ...
    def display_image(self) -> None: ...
    def zoom_image(self, factor=None, event=None) -> None: ...
    def fit_to_window(self) -> None: ...
    def reset_zoom(self) -> None: ...
    def start_pan(self, event) -> None: ...
    def do_pan(self, event) -> None: ...
    def end_pan(self, event) -> None: ...
    def update_status(self) -> None: ...
    def open_image(self) -> None: ...
    def new_database(self) -> None: ...
    def open_database(self) -> None: ...
    def save_database(self) -> None: ...
    def refresh_tables(self) -> None: ...
    def clear_table(self) -> None: ...
    def load_table_data(self, event=None) -> None: ...
    def on_treeview_click(self, event) -> None: ...
    def on_treeview_drag(self, event) -> None: ...
    def add_row(self) -> None: ...
    def edit_row(self) -> None: ...
    def delete_row(self) -> None: ...
    def on_row_double_click(self, event) -> None: ...
    def on_close(self) -> None: ...
    def run(self): ...

def run_fitting_viewer(json_filename: str = None, img_filename: str = None, fitter: Fitter = None, exp_id: int = None, exp: Experiment = None, result: Result = None, **kwargs): ...
