from enum import Enum


class TransformType(str, Enum):
    FILESET_QUERY_SEED_GENERATOR = "FILESET_QUERY_SEED_GENERATOR"
    FILESET_SEED_GENERATOR = "FILESET_SEED_GENERATOR"
    FILTER_CRITERIA = "FILTER_CRITERIA"
    FORWARD_LOOKING_QUESTION_GENERATOR = "FORWARD_LOOKING_QUESTION_GENERATOR"
    GDELT_SEED_GENERATOR = "GDELT_SEED_GENERATOR"
    MOCK = "MOCK"
    NEWS_CONTEXT_GENERATOR = "NEWS_CONTEXT_GENERATOR"
    NEWS_SEED_GENERATOR = "NEWS_SEED_GENERATOR"
    PIPELINE = "PIPELINE"
    QUESTION_AND_LABEL_GENERATOR = "QUESTION_AND_LABEL_GENERATOR"
    QUESTION_FILTER = "QUESTION_FILTER"
    QUESTION_GENERATOR = "QUESTION_GENERATOR"
    QUESTION_PIPELINE = "QUESTION_PIPELINE"
    QUESTION_QUALITY_SCORER = "QUESTION_QUALITY_SCORER"
    QUESTION_RENDERER = "QUESTION_RENDERER"
    ROLLOUT_GENERATOR = "ROLLOUT_GENERATOR"
    SCORE_FILTER = "SCORE_FILTER"
    WEB_SEARCH_LABELER = "WEB_SEARCH_LABELER"

    def __str__(self) -> str:
        return str(self.value)
