# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from typing import TYPE_CHECKING
from dataclasses import dataclass
from cdpify.shared.models import CDPModel

if TYPE_CHECKING:
    from cdpify.domains import runtime

"""
Heap snapshot object id.
"""
HeapSnapshotObjectId = str


@dataclass(kw_only=True)
class SamplingHeapProfileNode(CDPModel):
    """
    Sampling Heap Profile node. Holds callsite information, allocation statistics and
    child nodes.
    """

    call_frame: runtime.CallFrame
    self_size: float
    id: int
    children: list[SamplingHeapProfileNode]


@dataclass(kw_only=True)
class SamplingHeapProfileSample(CDPModel):
    """
    A single sample from a sampling profile.
    """

    size: float
    node_id: int
    ordinal: float


@dataclass(kw_only=True)
class SamplingHeapProfile(CDPModel):
    """
    Sampling profile.
    """

    head: SamplingHeapProfileNode
    samples: list[SamplingHeapProfileSample]
