# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .create_upload_response_data_union import CreateUploadResponseDataUnion


class CreateUploadResponseObject(UniversalBaseModel):
    """
    Examples
    --------
    from kard.commons import EmptyObject
    from kard.users.uploads import (
        CreateUploadResponseDataUnion_HistoricalTransactionStart,
        CreateUploadResponseObject,
    )

    CreateUploadResponseObject(
        data=CreateUploadResponseDataUnion_HistoricalTransactionStart(
            id="7e382223-b9a5-4825-91fb-436c8957a2e7",
            attributes=EmptyObject(),
        ),
    )
    """

    data: CreateUploadResponseDataUnion

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
