# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.3.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.


from typing import Union, Iterable



from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _thrustCMEstimation
else:
    import _thrustCMEstimation

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)



from Basilisk.architecture.swig_common_model import *


from Basilisk.architecture.swig_common_model import *


def new_doubleArray(nelements):
    return _thrustCMEstimation.new_doubleArray(nelements)

def delete_doubleArray(ary):
    return _thrustCMEstimation.delete_doubleArray(ary)

def doubleArray_getitem(ary, index):
    return _thrustCMEstimation.doubleArray_getitem(ary, index)

def doubleArray_setitem(ary, index, value):
    return _thrustCMEstimation.doubleArray_setitem(ary, index, value)

def new_longArray(nelements):
    return _thrustCMEstimation.new_longArray(nelements)

def delete_longArray(ary):
    return _thrustCMEstimation.delete_longArray(ary)

def longArray_getitem(ary, index):
    return _thrustCMEstimation.longArray_getitem(ary, index)

def longArray_setitem(ary, index, value):
    return _thrustCMEstimation.longArray_setitem(ary, index, value)

def new_intArray(nelements):
    return _thrustCMEstimation.new_intArray(nelements)

def delete_intArray(ary):
    return _thrustCMEstimation.delete_intArray(ary)

def intArray_getitem(ary, index):
    return _thrustCMEstimation.intArray_getitem(ary, index)

def intArray_setitem(ary, index, value):
    return _thrustCMEstimation.intArray_setitem(ary, index, value)

def new_shortArray(nelements):
    return _thrustCMEstimation.new_shortArray(nelements)

def delete_shortArray(ary):
    return _thrustCMEstimation.delete_shortArray(ary)

def shortArray_getitem(ary, index):
    return _thrustCMEstimation.shortArray_getitem(ary, index)

def shortArray_setitem(ary, index, value):
    return _thrustCMEstimation.shortArray_setitem(ary, index, value)


def getStructSize(self):
    try:
        class_name = repr(self).split(';')[0].split('.')[-1]
        sizeof_variable_name = 'sizeof_' + class_name
        size = globals().get(sizeof_variable_name)

        if size is None:
            raise ValueError(f"{sizeof_variable_name} not found in globals()")
    except (NameError) as e:
        typeString = 'sizeof_' + repr(self).split(';')[0].split('.')[-1]
        raise NameError(e.message + '\nYou tried to get this size macro: ' + typeString +
            '\n It appears to be undefined.  \nYou need to run the SWIG GEN_SIZEOF' +
            ' SWIG macro against the class/struct in your SWIG file if you want to ' +
            ' make this call.\n')


def protectSetAttr(self, name, value):
    if(hasattr(self, name) or name == 'this' or name.find('swig') >= 0):
        object.__setattr__(self, name, value)
    else:
        raise ValueError('You tried to add this variable: ' + name + '\n' +
            'To this class: ' + str(self))

def protectAllClasses(moduleType):
    import inspect

    clsmembers = inspect.getmembers(moduleType, inspect.isclass)
    for member in clsmembers:
        try:
            member[1].__setattr__ = protectSetAttr
            member[1].getStructSize = getStructSize
        except (AttributeError, TypeError) as e:
            pass


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _thrustCMEstimation.delete_SwigPyIterator

    def value(self):
        return _thrustCMEstimation.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _thrustCMEstimation.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _thrustCMEstimation.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _thrustCMEstimation.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _thrustCMEstimation.SwigPyIterator_equal(self, x)

    def copy(self):
        return _thrustCMEstimation.SwigPyIterator_copy(self)

    def next(self):
        return _thrustCMEstimation.SwigPyIterator_next(self)

    def __next__(self):
        return _thrustCMEstimation.SwigPyIterator___next__(self)

    def previous(self):
        return _thrustCMEstimation.SwigPyIterator_previous(self)

    def advance(self, n):
        return _thrustCMEstimation.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _thrustCMEstimation.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _thrustCMEstimation.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _thrustCMEstimation.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _thrustCMEstimation.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _thrustCMEstimation.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _thrustCMEstimation.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _thrustCMEstimation:
_thrustCMEstimation.SwigPyIterator_swigregister(SwigPyIterator)
MAX_LOGGING_LENGTH = _thrustCMEstimation.MAX_LOGGING_LENGTH
BSK_DEBUG = _thrustCMEstimation.BSK_DEBUG
BSK_INFORMATION = _thrustCMEstimation.BSK_INFORMATION
BSK_WARNING = _thrustCMEstimation.BSK_WARNING
BSK_ERROR = _thrustCMEstimation.BSK_ERROR
BSK_SILENT = _thrustCMEstimation.BSK_SILENT

def printDefaultLogLevel():
    return _thrustCMEstimation.printDefaultLogLevel()

def setDefaultLogLevel(logLevel):
    return _thrustCMEstimation.setDefaultLogLevel(logLevel)

def getDefaultLogLevel():
    return _thrustCMEstimation.getDefaultLogLevel()
class BasiliskError(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _thrustCMEstimation.BasiliskError_swiginit(self, _thrustCMEstimation.new_BasiliskError(*args))
    __swig_destroy__ = _thrustCMEstimation.delete_BasiliskError

# Register BasiliskError in _thrustCMEstimation:
_thrustCMEstimation.BasiliskError_swigregister(BasiliskError)
cvar = _thrustCMEstimation.cvar

class BSKLogger(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _thrustCMEstimation.BSKLogger_swiginit(self, _thrustCMEstimation.new_BSKLogger(*args))
    __swig_destroy__ = _thrustCMEstimation.delete_BSKLogger

    def setLogLevel(self, logLevel):
        return _thrustCMEstimation.BSKLogger_setLogLevel(self, logLevel)

    def printLogLevel(self):
        return _thrustCMEstimation.BSKLogger_printLogLevel(self)

    def getLogLevel(self):
        return _thrustCMEstimation.BSKLogger_getLogLevel(self)

    def bskLog(self, targetLevel, info):
        return _thrustCMEstimation.BSKLogger_bskLog(self, targetLevel, info)
    logLevelMap = property(_thrustCMEstimation.BSKLogger_logLevelMap_get, _thrustCMEstimation.BSKLogger_logLevelMap_set)

# Register BSKLogger in _thrustCMEstimation:
_thrustCMEstimation.BSKLogger_swigregister(BSKLogger)

def _BSKLogger():
    return _thrustCMEstimation._BSKLogger()

def _BSKLogger_d(arg1):
    return _thrustCMEstimation._BSKLogger_d(arg1)

def _printLogLevel(arg1):
    return _thrustCMEstimation._printLogLevel(arg1)

def _setLogLevel(arg1, arg2):
    return _thrustCMEstimation._setLogLevel(arg1, arg2)

def _bskLog(arg1, arg2, arg3):
    return _thrustCMEstimation._bskLog(arg1, arg2, arg3)
class SysModel(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _thrustCMEstimation.SysModel_swiginit(self, _thrustCMEstimation.new_SysModel(*args))
    __swig_destroy__ = _thrustCMEstimation.delete_SysModel

    def SelfInit(self):
        return _thrustCMEstimation.SysModel_SelfInit(self)

    def IntegratedInit(self):
        return _thrustCMEstimation.SysModel_IntegratedInit(self)

    def UpdateState(self, CurrentSimNanos):
        return _thrustCMEstimation.SysModel_UpdateState(self, CurrentSimNanos)

    def Reset(self, CurrentSimNanos):
        return _thrustCMEstimation.SysModel_Reset(self, CurrentSimNanos)
    ModelTag = property(_thrustCMEstimation.SysModel_ModelTag_get, _thrustCMEstimation.SysModel_ModelTag_set)
    CallCounts = property(_thrustCMEstimation.SysModel_CallCounts_get, _thrustCMEstimation.SysModel_CallCounts_set)
    RNGSeed = property(_thrustCMEstimation.SysModel_RNGSeed_get, _thrustCMEstimation.SysModel_RNGSeed_set)
    moduleID = property(_thrustCMEstimation.SysModel_moduleID_get, _thrustCMEstimation.SysModel_moduleID_set)

    def logger(self, variableNames: Union[str, Iterable[str]], recordingTime: int = 0):
        """Generate a logger from one or more variables in this model.

        Each variable must be public or private with a standard-named getter.
        For example, if you want to log the variable `foo` from the model
        `mod`, then `mod.foo` or `mod.getFoo()` must be available.

        Args:
            variableNames (Union[str, Iterable[str]]): The name or names
                of the variables to log.
            recordingTime (int, optional): The minimum interval between variable
                recordings. Defaults to 0.
        """
        if isinstance(variableNames, str):
            variableNames = [variableNames]

        loggingFunctions = {}
        for variableName in variableNames:
            if hasattr(self, variableName):
                loggingFunctions[variableName] = lambda _, variableName=variableName: getattr(self, variableName)
                continue

            getterStr = f"get{variableName[0].upper()}{variableName[1:]}"
            getter = getattr(self, getterStr, None)
            if getter is not None:
                loggingFunctions[variableName] = lambda _, getter=getter: getter()
                continue

            raise ValueError(f"Cannot log {variableName} as it is not a "
                f"public variable of {type(self).__name__} and the getter "
                f"{getterStr} does not exist.")

        from Basilisk.utilities import pythonVariableLogger
        return pythonVariableLogger.PythonVariableLogger(loggingFunctions, recordingTime)


# Register SysModel in _thrustCMEstimation:
_thrustCMEstimation.SysModel_swigregister(SysModel)
class ThrustCMEstimation(SysModel):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _thrustCMEstimation.ThrustCMEstimation_swiginit(self, _thrustCMEstimation.new_ThrustCMEstimation())
    __swig_destroy__ = _thrustCMEstimation.delete_ThrustCMEstimation

    def SelfInit(self):
        return _thrustCMEstimation.ThrustCMEstimation_SelfInit(self)

    def Reset(self, CurrentSimNanos):
        return _thrustCMEstimation.ThrustCMEstimation_Reset(self, CurrentSimNanos)

    def UpdateState(self, CurrentSimNanos):
        return _thrustCMEstimation.ThrustCMEstimation_UpdateState(self, CurrentSimNanos)
    attitudeTol = property(_thrustCMEstimation.ThrustCMEstimation_attitudeTol_get, _thrustCMEstimation.ThrustCMEstimation_attitudeTol_set)
    thrusterConfigBInMsg = property(_thrustCMEstimation.ThrustCMEstimation_thrusterConfigBInMsg_get, _thrustCMEstimation.ThrustCMEstimation_thrusterConfigBInMsg_set)
    intFeedbackTorqueInMsg = property(_thrustCMEstimation.ThrustCMEstimation_intFeedbackTorqueInMsg_get, _thrustCMEstimation.ThrustCMEstimation_intFeedbackTorqueInMsg_set)
    attGuidInMsg = property(_thrustCMEstimation.ThrustCMEstimation_attGuidInMsg_get, _thrustCMEstimation.ThrustCMEstimation_attGuidInMsg_set)
    vehConfigInMsg = property(_thrustCMEstimation.ThrustCMEstimation_vehConfigInMsg_get, _thrustCMEstimation.ThrustCMEstimation_vehConfigInMsg_set)
    cmEstDataOutMsg = property(_thrustCMEstimation.ThrustCMEstimation_cmEstDataOutMsg_get, _thrustCMEstimation.ThrustCMEstimation_cmEstDataOutMsg_set)
    vehConfigOutMsg = property(_thrustCMEstimation.ThrustCMEstimation_vehConfigOutMsg_get, _thrustCMEstimation.ThrustCMEstimation_vehConfigOutMsg_set)
    vehConfigOutMsgC = property(_thrustCMEstimation.ThrustCMEstimation_vehConfigOutMsgC_get, _thrustCMEstimation.ThrustCMEstimation_vehConfigOutMsgC_set)
    r_CB_B = property(_thrustCMEstimation.ThrustCMEstimation_r_CB_B_get, _thrustCMEstimation.ThrustCMEstimation_r_CB_B_set)
    P0 = property(_thrustCMEstimation.ThrustCMEstimation_P0_get, _thrustCMEstimation.ThrustCMEstimation_P0_set)
    R0 = property(_thrustCMEstimation.ThrustCMEstimation_R0_get, _thrustCMEstimation.ThrustCMEstimation_R0_set)

# Register ThrustCMEstimation in _thrustCMEstimation:
_thrustCMEstimation.ThrustCMEstimation_swigregister(ThrustCMEstimation)
class THRConfigMsgPayload(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    rThrust_B = property(_thrustCMEstimation.THRConfigMsgPayload_rThrust_B_get, _thrustCMEstimation.THRConfigMsgPayload_rThrust_B_set)
    tHatThrust_B = property(_thrustCMEstimation.THRConfigMsgPayload_tHatThrust_B_get, _thrustCMEstimation.THRConfigMsgPayload_tHatThrust_B_set)
    maxThrust = property(_thrustCMEstimation.THRConfigMsgPayload_maxThrust_get, _thrustCMEstimation.THRConfigMsgPayload_maxThrust_set)
    swirlTorque = property(_thrustCMEstimation.THRConfigMsgPayload_swirlTorque_get, _thrustCMEstimation.THRConfigMsgPayload_swirlTorque_set)

    def __init__(self):
        _thrustCMEstimation.THRConfigMsgPayload_swiginit(self, _thrustCMEstimation.new_THRConfigMsgPayload())
    __swig_destroy__ = _thrustCMEstimation.delete_THRConfigMsgPayload

# Register THRConfigMsgPayload in _thrustCMEstimation:
_thrustCMEstimation.THRConfigMsgPayload_swigregister(THRConfigMsgPayload)
class CmdTorqueBodyMsgPayload(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    torqueRequestBody = property(_thrustCMEstimation.CmdTorqueBodyMsgPayload_torqueRequestBody_get, _thrustCMEstimation.CmdTorqueBodyMsgPayload_torqueRequestBody_set)

    def __init__(self):
        _thrustCMEstimation.CmdTorqueBodyMsgPayload_swiginit(self, _thrustCMEstimation.new_CmdTorqueBodyMsgPayload())
    __swig_destroy__ = _thrustCMEstimation.delete_CmdTorqueBodyMsgPayload

# Register CmdTorqueBodyMsgPayload in _thrustCMEstimation:
_thrustCMEstimation.CmdTorqueBodyMsgPayload_swigregister(CmdTorqueBodyMsgPayload)
class AttGuidMsgPayload(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    sigma_BR = property(_thrustCMEstimation.AttGuidMsgPayload_sigma_BR_get, _thrustCMEstimation.AttGuidMsgPayload_sigma_BR_set)
    omega_BR_B = property(_thrustCMEstimation.AttGuidMsgPayload_omega_BR_B_get, _thrustCMEstimation.AttGuidMsgPayload_omega_BR_B_set)
    omega_RN_B = property(_thrustCMEstimation.AttGuidMsgPayload_omega_RN_B_get, _thrustCMEstimation.AttGuidMsgPayload_omega_RN_B_set)
    domega_RN_B = property(_thrustCMEstimation.AttGuidMsgPayload_domega_RN_B_get, _thrustCMEstimation.AttGuidMsgPayload_domega_RN_B_set)

    def __init__(self):
        _thrustCMEstimation.AttGuidMsgPayload_swiginit(self, _thrustCMEstimation.new_AttGuidMsgPayload())
    __swig_destroy__ = _thrustCMEstimation.delete_AttGuidMsgPayload

# Register AttGuidMsgPayload in _thrustCMEstimation:
_thrustCMEstimation.AttGuidMsgPayload_swigregister(AttGuidMsgPayload)
class VehicleConfigMsgPayload(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    ISCPntB_B = property(_thrustCMEstimation.VehicleConfigMsgPayload_ISCPntB_B_get, _thrustCMEstimation.VehicleConfigMsgPayload_ISCPntB_B_set)
    CoM_B = property(_thrustCMEstimation.VehicleConfigMsgPayload_CoM_B_get, _thrustCMEstimation.VehicleConfigMsgPayload_CoM_B_set)
    massSC = property(_thrustCMEstimation.VehicleConfigMsgPayload_massSC_get, _thrustCMEstimation.VehicleConfigMsgPayload_massSC_set)
    CurrentADCSState = property(_thrustCMEstimation.VehicleConfigMsgPayload_CurrentADCSState_get, _thrustCMEstimation.VehicleConfigMsgPayload_CurrentADCSState_set)

    def __init__(self):
        _thrustCMEstimation.VehicleConfigMsgPayload_swiginit(self, _thrustCMEstimation.new_VehicleConfigMsgPayload())
    __swig_destroy__ = _thrustCMEstimation.delete_VehicleConfigMsgPayload

# Register VehicleConfigMsgPayload in _thrustCMEstimation:
_thrustCMEstimation.VehicleConfigMsgPayload_swigregister(VehicleConfigMsgPayload)
class CMEstDataMsgPayload(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    attError = property(_thrustCMEstimation.CMEstDataMsgPayload_attError_get, _thrustCMEstimation.CMEstDataMsgPayload_attError_set)
    state = property(_thrustCMEstimation.CMEstDataMsgPayload_state_get, _thrustCMEstimation.CMEstDataMsgPayload_state_set)
    stateError = property(_thrustCMEstimation.CMEstDataMsgPayload_stateError_get, _thrustCMEstimation.CMEstDataMsgPayload_stateError_set)
    covariance = property(_thrustCMEstimation.CMEstDataMsgPayload_covariance_get, _thrustCMEstimation.CMEstDataMsgPayload_covariance_set)
    preFitRes = property(_thrustCMEstimation.CMEstDataMsgPayload_preFitRes_get, _thrustCMEstimation.CMEstDataMsgPayload_preFitRes_set)
    postFitRes = property(_thrustCMEstimation.CMEstDataMsgPayload_postFitRes_get, _thrustCMEstimation.CMEstDataMsgPayload_postFitRes_set)

    def __init__(self):
        _thrustCMEstimation.CMEstDataMsgPayload_swiginit(self, _thrustCMEstimation.new_CMEstDataMsgPayload())
    __swig_destroy__ = _thrustCMEstimation.delete_CMEstDataMsgPayload

# Register CMEstDataMsgPayload in _thrustCMEstimation:
_thrustCMEstimation.CMEstDataMsgPayload_swigregister(CMEstDataMsgPayload)

import sys
protectAllClasses(sys.modules[__name__])


