import threading
from _typeshed import Incomplete

PSUTIL_AVAILABLE: bool
IS_WINDOWS: Incomplete

class ParentProcessMonitor:
    check_interval: Incomplete
    parent_pid: int | None
    monitor_thread: threading.Thread | None
    running: bool
    def __init__(self, check_interval: float = 5.0) -> None: ...
    def get_parent_pid(self) -> int | None: ...
    def is_process_running(self, pid: int) -> bool: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...

def setup_parent_process_monitor(app, check_interval: float = 5.0, enabled: bool = True): ...
