class PluginObject:
    name: str
    def __init__(self) -> None: ...
    def on_install(self) -> None: ...
    def on_uninstall(self) -> None: ...
    def on_load(self) -> None: ...
    def on_unload(self) -> None: ...
