# coding: utf-8

"""
    Neurograph Core

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neurograph.v1.models.personas_instance_delete_many_request import PersonasInstanceDeleteManyRequest

class TestPersonasInstanceDeleteManyRequest(unittest.TestCase):
    """PersonasInstanceDeleteManyRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PersonasInstanceDeleteManyRequest:
        """Test PersonasInstanceDeleteManyRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PersonasInstanceDeleteManyRequest`
        """
        model = PersonasInstanceDeleteManyRequest()
        if include_optional:
            return PersonasInstanceDeleteManyRequest(
                persona_instance_ids = [
                    ''
                    ]
            )
        else:
            return PersonasInstanceDeleteManyRequest(
        )
        """

    def testPersonasInstanceDeleteManyRequest(self):
        """Test PersonasInstanceDeleteManyRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
