# coding: utf-8

"""
    Neurograph Core

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neurograph.v1.models.signal_client_info import SignalClientInfo

class TestSignalClientInfo(unittest.TestCase):
    """SignalClientInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SignalClientInfo:
        """Test SignalClientInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SignalClientInfo`
        """
        model = SignalClientInfo()
        if include_optional:
            return SignalClientInfo(
                client_uid = '',
                domain = '',
                org_uid = ''
            )
        else:
            return SignalClientInfo(
        )
        """

    def testSignalClientInfo(self):
        """Test SignalClientInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
