from .caerp_admin import admin_entry_point
from .caerp_anonymize import anonymize_entry_point
from .caerp_cache import cache_entry_point
from .caerp_celery import celery_command_entry_point
from .caerp_clean import clean_entry_point
from .caerp_company_export import company_export_entry_point
from .caerp_export import export_entry_point
from .caerp_load_demo_data import load_demo_data_entry_point
from .caerp_migrate import migrate_entry_point
