from _typeshed import Incomplete
from matplotlib import cm as cm
from mpl_toolkits.mplot3d import Axes3D as Axes3D

I: Incomplete
X: Incomplete
Y: Incomplete
Z: Incomplete
paulis: Incomplete
pauli_labels: Incomplete

def density_matrix_from_bloch(bloch): ...
def bloch_vector_from_density_matrix(rho): ...
def plot_density_matrix(rho, title: str = '', ax=None) -> None: ...
def plot_chi_matrix(chi, title: str = '', ax=None) -> None: ...
def depolarizing_channel(rho, p): ...
def amplitude_damping_channel(rho, gamma): ...
def visualize_qpt(input_states, output_states, chi) -> None: ...
