from typing import Protocol

from PyQt6.QtCore import pyqtBoundSignal, pyqtSlot


class BatchProcessingProtocol(Protocol):
    """The interface for the batch processing widget."""

    sig_batch_process: pyqtBoundSignal

    @property
    def current_directory(self) -> str: ...
    @current_directory.setter
    def current_directory(self, value: str): ...
    @property
    def prefix(self) -> str: ...
    @prefix.setter
    def prefix(self, value: str) -> str: ...
    @pyqtSlot()
    def get_files_to_process(self): ...
    def move_to_done(self, file: str): ...
    def disable_buttons(self): ...
    def enable_buttons(self): ...
