from _typeshed import Incomplete

__MINJIANG_SERVER_ADDR__: Incomplete
__MINJIANG_SOCKET_ADDR__: Incomplete
__MINJIANG_TEMP_TOKEN__: Incomplete
__MINJIANG_LANGUAGE__: str

def get_default_config_dir(): ...
def get_plugin_dir(): ...
def create_cache_dir(group_name: str): ...
def get_fit_cache_dir(group_name: str, create_timestamp: int, exp_id: int = None): ...
def set_cache_dir(cache_dir): ...
def get_cache_dir(): ...
def get_default_config(): ...
def get_user_token(): ...
def set_user_token(token: str): ...
def get_user_temp_token(): ...
def set_user_temp_token(token: str): ...
def remove_user_temp_token() -> None: ...
def set_default_language(language: str): ...
def get_default_language(): ...
def set_server_addr(addr: str): ...
def get_server_addr(): ...
def get_socket_addr(): ...
def set_gui_addr(addr: str, port: int): ...
def get_gui_addr(): ...
