"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import ansys.api.discovery.v1.commands.application_pb2
import grpc

class ApplicationStub:
    def __init__(self, channel: grpc.Channel) -> None: ...
    IsStarted: grpc.UnaryUnaryMultiCallable[
        ansys.api.discovery.v1.commands.application_pb2.ApplicationStartedRequest,
        ansys.api.discovery.v1.commands.application_pb2.ApplicationStartedResponse] = ...

    Close: grpc.UnaryUnaryMultiCallable[
        ansys.api.discovery.v1.commands.application_pb2.CloseApplicationRequest,
        ansys.api.discovery.v1.commands.application_pb2.CloseApplicationResponse] = ...

    DisposeTracker: grpc.UnaryUnaryMultiCallable[
        ansys.api.discovery.v1.commands.application_pb2.DisposeTrackerRequest,
        ansys.api.discovery.v1.commands.application_pb2.DisposeTrackerResponse] = ...

    GetMonikersCompressionMethod: grpc.UnaryUnaryMultiCallable[
        ansys.api.discovery.v1.commands.application_pb2.GetMonikerCompressionMethodRequest,
        ansys.api.discovery.v1.commands.application_pb2.GetMonikerCompressionMethodResponse] = ...

    GetTracker: grpc.UnaryUnaryMultiCallable[
        ansys.api.discovery.v1.commands.application_pb2.GetTrackerRequest,
        ansys.api.discovery.v1.commands.application_pb2.GetTrackerResponse] = ...

    GetTrackerChanges: grpc.UnaryUnaryMultiCallable[
        ansys.api.discovery.v1.commands.application_pb2.GetTrackerChangesRequest,
        ansys.api.discovery.v1.commands.application_pb2.GetTrackerChangesResponse] = ...

    SetAutomaticTrackingState: grpc.UnaryUnaryMultiCallable[
        ansys.api.discovery.v1.commands.application_pb2.SetAutomaticTrackingStateRequest,
        ansys.api.discovery.v1.commands.application_pb2.SetAutomaticTrackingStateResponse] = ...

    SetMonikersCompressionMethod: grpc.UnaryUnaryMultiCallable[
        ansys.api.discovery.v1.commands.application_pb2.SetMonikerCompressionMethodRequest,
        ansys.api.discovery.v1.commands.application_pb2.SetMonikerCompressionMethodResponse] = ...

    SetTitle: grpc.UnaryUnaryMultiCallable[
        ansys.api.discovery.v1.commands.application_pb2.SetApplicationTitleRequest,
        ansys.api.discovery.v1.commands.application_pb2.SetApplicationTitleResponse] = ...

    GetBackend: grpc.UnaryUnaryMultiCallable[
        ansys.api.discovery.v1.commands.application_pb2.GetBackendRequest,
        ansys.api.discovery.v1.commands.application_pb2.GetBackendResponse] = ...


class ApplicationServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def IsStarted(self,
        request: ansys.api.discovery.v1.commands.application_pb2.ApplicationStartedRequest,
        context: grpc.ServicerContext,
    ) -> ansys.api.discovery.v1.commands.application_pb2.ApplicationStartedResponse: ...

    @abc.abstractmethod
    def Close(self,
        request: ansys.api.discovery.v1.commands.application_pb2.CloseApplicationRequest,
        context: grpc.ServicerContext,
    ) -> ansys.api.discovery.v1.commands.application_pb2.CloseApplicationResponse: ...

    @abc.abstractmethod
    def DisposeTracker(self,
        request: ansys.api.discovery.v1.commands.application_pb2.DisposeTrackerRequest,
        context: grpc.ServicerContext,
    ) -> ansys.api.discovery.v1.commands.application_pb2.DisposeTrackerResponse: ...

    @abc.abstractmethod
    def GetMonikersCompressionMethod(self,
        request: ansys.api.discovery.v1.commands.application_pb2.GetMonikerCompressionMethodRequest,
        context: grpc.ServicerContext,
    ) -> ansys.api.discovery.v1.commands.application_pb2.GetMonikerCompressionMethodResponse: ...

    @abc.abstractmethod
    def GetTracker(self,
        request: ansys.api.discovery.v1.commands.application_pb2.GetTrackerRequest,
        context: grpc.ServicerContext,
    ) -> ansys.api.discovery.v1.commands.application_pb2.GetTrackerResponse: ...

    @abc.abstractmethod
    def GetTrackerChanges(self,
        request: ansys.api.discovery.v1.commands.application_pb2.GetTrackerChangesRequest,
        context: grpc.ServicerContext,
    ) -> ansys.api.discovery.v1.commands.application_pb2.GetTrackerChangesResponse: ...

    @abc.abstractmethod
    def SetAutomaticTrackingState(self,
        request: ansys.api.discovery.v1.commands.application_pb2.SetAutomaticTrackingStateRequest,
        context: grpc.ServicerContext,
    ) -> ansys.api.discovery.v1.commands.application_pb2.SetAutomaticTrackingStateResponse: ...

    @abc.abstractmethod
    def SetMonikersCompressionMethod(self,
        request: ansys.api.discovery.v1.commands.application_pb2.SetMonikerCompressionMethodRequest,
        context: grpc.ServicerContext,
    ) -> ansys.api.discovery.v1.commands.application_pb2.SetMonikerCompressionMethodResponse: ...

    @abc.abstractmethod
    def SetTitle(self,
        request: ansys.api.discovery.v1.commands.application_pb2.SetApplicationTitleRequest,
        context: grpc.ServicerContext,
    ) -> ansys.api.discovery.v1.commands.application_pb2.SetApplicationTitleResponse: ...

    @abc.abstractmethod
    def GetBackend(self,
        request: ansys.api.discovery.v1.commands.application_pb2.GetBackendRequest,
        context: grpc.ServicerContext,
    ) -> ansys.api.discovery.v1.commands.application_pb2.GetBackendResponse: ...


def add_ApplicationServicer_to_server(servicer: ApplicationServicer, server: grpc.Server) -> None: ...
