from __future__ import annotations

nodes = {
    "document": {
        "render": "article",
        "children": [
            "heading",
            "paragraph",
            "image",
            "table",
            "tag",
            "fence",
            "blockquote",
            "comment",
            "list",
            "hr",
        ],
        "attributes": {"frontmatter": {"render": False}},
    },
    "heading": {
        "render": "h{level}",
        "children": ["inline"],
        "attributes": {"level": {"type": int, "render": False, "required": True}},
    },
    "paragraph": {"render": "p", "children": ["inline"]},
    "image": {
        "render": "img",
        "self_closing": True,
        "attributes": {"src": {"type": str, "required": True}, "alt": {"type": str}, "title": {"type": str}},
    },
    "fence": {
        "render": "pre",
        "attributes": {
            "content": {"type": str, "render": False, "required": True},
            "language": {"type": str, "render": "data-language"},
            "process": {"type": bool, "render": False, "default": True},
        },
    },
    "blockquote": {
        "render": "blockquote",
        "children": [
            "heading",
            "paragraph",
            "image",
            "table",
            "tag",
            "fence",
            "blockquote",
            "list",
            "hr",
        ],
    },
    "item": {
        "render": "li",
        "children": [
            "inline",
            "heading",
            "paragraph",
            "image",
            "table",
            "tag",
            "fence",
            "blockquote",
            "list",
            "hr",
        ],
    },
    "list": {
        "render": None,
        "children": ["item"],
        "attributes": {"ordered": {"type": bool, "render": False, "required": True}, "start": {"type": int}, "marker": {"type": str, "render": False}},
    },
    "hr": {"render": "hr", "self_closing": True},
    "table": {"render": "table"},
    "td": {
        "render": "td",
        "children": [
            "inline",
            "heading",
            "paragraph",
            "image",
            "table",
            "tag",
            "fence",
            "blockquote",
            "list",
            "hr",
        ],
        "attributes": {"align": {"type": str}, "colspan": {"type": int, "render": "colSpan"}, "rowspan": {"type": int, "render": "rowSpan"}},
    },
    "th": {
        "render": "th",
        "attributes": {"width": {"type": str}, "align": {"type": str}, "colspan": {"type": int, "render": "colSpan"}, "rowspan": {"type": int, "render": "rowSpan"}},
    },
    "tr": {"render": "tr", "children": ["th", "td"]},
    "tbody": {"render": "tbody", "children": ["tr", "tag"]},
    "thead": {"render": "thead", "children": ["tr"]},
    "strong": {"render": "strong", "children": ["em", "s", "link", "code_inline", "text", "tag"], "attributes": {"marker": {"type": str, "render": False}}},
    "em": {"render": "em", "children": ["strong", "s", "link", "code_inline", "text", "tag"], "attributes": {"marker": {"type": str, "render": False}}},
    "s": {"render": "s", "children": ["strong", "em", "link", "code_inline", "text", "tag"]},
    "inline": {
        "children": [
            "strong",
            "em",
            "s",
            "code_inline",
            "text",
            "tag",
            "link",
            "image",
            "hardbreak",
            "softbreak",
            "comment",
        ],
    },
    "link": {"render": "a", "children": ["strong", "em", "s", "code_inline", "text", "tag"], "attributes": {"href": {"type": str, "required": True}, "title": {"type": str}}},
    "code_inline": {"render": "code", "attributes": {"content": {"type": str, "render": False, "required": True}}},
    "text": {"attributes": {"content": {"type": str, "required": True}}},
    "hardbreak": {"render": "br", "self_closing": True},
    "softbreak": {"render": None},
    "comment": {"attributes": {"content": {"type": str, "required": True}}},
    "error": {},
    "node": {},
    "code": {"render": "pre"},
}
