# coding: utf-8

"""
    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class NewScaCore(str, Enum):
    """
    `newScaCore` displays the version of the SCA available for upgrade. For a list of supported versions, refer to the developer documentation.
    """

    """
    allowed enum values
    """
    CIRCLE_6900_SINGLEOWNER_V2 = 'circle_6900_singleowner_v2'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of NewScaCore from a JSON string"""
        return cls(json.loads(json_str))


