# SPDX-FileCopyrightText: Copyright (c) 2021-2026 NVIDIA CORPORATION & AFFILIATES.
# All rights reserved.
# SPDX-License-Identifier: Apache-2.0

from ..data.physical_array import PhysicalArray
from ..data.scalar import Scalar
from ..mapping.machine import Machine
from ..utilities.typedefs import Domain, DomainPoint, GlobalTaskID, VariantCode
from ..utilities.unconstructable import Unconstructable

class TaskContext(Unconstructable):
    def get_task_id(self) -> GlobalTaskID: ...
    def get_variant_kind(self) -> VariantCode: ...
    @property
    def inputs(self) -> tuple[PhysicalArray, ...]: ...
    @property
    def outputs(self) -> tuple[PhysicalArray, ...]: ...
    @property
    def reductions(self) -> tuple[PhysicalArray, ...]: ...
    @property
    def scalars(self) -> tuple[Scalar, ...]: ...
    def is_single_task(self) -> bool: ...
    @property
    def task_index(self) -> DomainPoint: ...
    @property
    def launch_domain(self) -> Domain: ...
    @property
    def machine(self) -> Machine: ...
    @property
    def provenance(self) -> str: ...
    @property
    def task_stream(self) -> int | None: ...
    def set_exception(self, excn: Exception) -> None: ...
    def can_raise_exception(self) -> bool: ...
