from _typeshed import Incomplete
from minjiang_client.com.minio import get_minio_client as get_minio_client
from minjiang_client.com.oss import add_resource as add_resource, get_resource_info as get_resource_info
from minjiang_client.com.request import request as request
from minjiang_client.utils.file_type_utils import FileTypeUtils as FileTypeUtils

MAX_FILE_SIZE: Incomplete

def create_directory(organization_id: int, parent_dir_id: int = None, dir_name: str = None, description: str = None): ...
def get_directory_content(organization_id: int, parent_dir_id: int = None): ...
def move_directory(dir_id: int, new_parent_dir_id: int = None): ...
def create_file(organization_id: int, dir_id: int = None, file_name: str = None, resource_id: int = None, file_size: int = None, description: str = None, tags: list = None): ...
def upload_file_version(file_id: int, resource_id: int, file_size: int = None, version_name: str = None, change_log: str = None): ...
def get_file_versions(file_id: int, page: int = 1, per_page: int = 10): ...
def get_file_version_info(version_id: int, file_id: int): ...
def copy_file(file_id: int, target_dir_id: int = None, new_name: str = None): ...
def move_file(file_id: int, target_dir_id: int = None, new_name: str = None): ...
def delete_file(file_id: int): ...
def get_file_info(file_id: int): ...
def delete_directory(dir_id: int) -> dict: ...
def get_file_by_path(file_path: str): ...
def download_file_to_local(script_manager_path: str, local_path: str, file_name: str = None): ...
def create_file_with_upload(organization_id: int, file_path_or_content: str | bytes, dir_id: int | None = None, file_name: str | None = None, description: str | None = None, tags: str | list[str] | None = None): ...
def upload_file_version_with_upload(file_id: int, file_path_or_content: str | bytes, version_name: str | None = None, change_log: str | None = None): ...
