from typing import Any

class Pos:
    line: int
    column: int
    def __init__(self, line: int, column: int) -> None: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
