# coding: utf-8

"""
    BioT Device Service

    APIs document (version: 8.9.1)

    The version of the OpenAPI document: 8.9.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biotmed_device_sdk.models.delete_orphan_sessions_response import DeleteOrphanSessionsResponse

class TestDeleteOrphanSessionsResponse(unittest.TestCase):
    """DeleteOrphanSessionsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeleteOrphanSessionsResponse:
        """Test DeleteOrphanSessionsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeleteOrphanSessionsResponse`
        """
        model = DeleteOrphanSessionsResponse()
        if include_optional:
            return DeleteOrphanSessionsResponse(
                deleted_sessions = [
                    biotmed_device_sdk.models.session_response_v2.SessionResponseV2(
                        _id = '3fa85f64-5717-4562-b3fc-2c963f66afa6', 
                        _patient = null, 
                        _device = null, 
                        _owner_organization = null, 
                        _start_time = '2007-12-20T10:15:30Z', 
                        _end_time = '2007-12-20T10:15:30Z', 
                        _state = 'ACTIVE', 
                        _initiator = 'EXTERNAL', 
                        _required_measurement_interval_milliseconds = 1000, 
                        _template = biotmed_device_sdk.models.basic_template_data.BasicTemplateData(
                            name = '', 
                            display_name = '', 
                            parent_template = null, 
                            id = '', ), 
                        _referencers = {
                            'key' : biotmed_device_sdk.models.referenced_side_attribute_information.ReferencedSideAttributeInformation(
                                name = '', 
                                display_name = '', 
                                count = 56, 
                                attribute_id = '', 
                                template_id = '', 
                                template = null, 
                                referrer = null, )
                            }, 
                        _configuration = {
                            'key' : null
                            }, 
                        _summary = biotmed_device_sdk.models.session_summary.SessionSummary(
                            _stop_reason = 'Manual Stop', 
                            _stop_reason_code = 'COMPLETION', ), 
                        _last_modified_time = '2007-12-20T10:15:30Z', 
                        _creation_time = '2007-12-20T10:15:30Z', 
                        _name = '0', 
                        _session_context = '', 
                        _caption = '', )
                    ]
            )
        else:
            return DeleteOrphanSessionsResponse(
                deleted_sessions = [
                    biotmed_device_sdk.models.session_response_v2.SessionResponseV2(
                        _id = '3fa85f64-5717-4562-b3fc-2c963f66afa6', 
                        _patient = null, 
                        _device = null, 
                        _owner_organization = null, 
                        _start_time = '2007-12-20T10:15:30Z', 
                        _end_time = '2007-12-20T10:15:30Z', 
                        _state = 'ACTIVE', 
                        _initiator = 'EXTERNAL', 
                        _required_measurement_interval_milliseconds = 1000, 
                        _template = biotmed_device_sdk.models.basic_template_data.BasicTemplateData(
                            name = '', 
                            display_name = '', 
                            parent_template = null, 
                            id = '', ), 
                        _referencers = {
                            'key' : biotmed_device_sdk.models.referenced_side_attribute_information.ReferencedSideAttributeInformation(
                                name = '', 
                                display_name = '', 
                                count = 56, 
                                attribute_id = '', 
                                template_id = '', 
                                template = null, 
                                referrer = null, )
                            }, 
                        _configuration = {
                            'key' : null
                            }, 
                        _summary = biotmed_device_sdk.models.session_summary.SessionSummary(
                            _stop_reason = 'Manual Stop', 
                            _stop_reason_code = 'COMPLETION', ), 
                        _last_modified_time = '2007-12-20T10:15:30Z', 
                        _creation_time = '2007-12-20T10:15:30Z', 
                        _name = '0', 
                        _session_context = '', 
                        _caption = '', )
                    ],
        )
        """

    def testDeleteOrphanSessionsResponse(self):
        """Test DeleteOrphanSessionsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
