# coding: utf-8

"""
    iparapheur

    iparapheur v5.x main core application.  The main link between every sub-services, integrating business code logic. 

    The version of the OpenAPI document: DEVELOP
    Contact: iparapheur@libriciel.coop
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iparapheur_provisioning.models.external_signature_provider import ExternalSignatureProvider

class TestExternalSignatureProvider(unittest.TestCase):
    """ExternalSignatureProvider unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExternalSignatureProvider(self):
        """Test ExternalSignatureProvider"""
        # inst = ExternalSignatureProvider()

if __name__ == '__main__':
    unittest.main()
