# coding: utf-8

"""
    Arthur Scope

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from arthur_client.api_bindings.api.models_v1_api import ModelsV1Api


class TestModelsV1Api(unittest.TestCase):
    """ModelsV1Api unit test stubs"""

    def setUp(self) -> None:
        self.api = ModelsV1Api()

    def tearDown(self) -> None:
        pass

    def test_delete_model(self) -> None:
        """Test case for delete_model

        Delete Model By Id
        """
        pass

    def test_delete_model_metrics_schedule(self) -> None:
        """Test case for delete_model_metrics_schedule

        Delete Model Metrics Schedule
        """
        pass

    def test_generate_metrics_spec(self) -> None:
        """Test case for generate_metrics_spec

        Generates A Metrics Spec.
        """
        pass

    def test_get_model(self) -> None:
        """Test case for get_model

        Get Model By Id
        """
        pass

    def test_get_models(self) -> None:
        """Test case for get_models

        List Models
        """
        pass

    def test_get_models_in_workspace(self) -> None:
        """Test case for get_models_in_workspace

        Get Workspace Models.
        """
        pass

    def test_patch_model(self) -> None:
        """Test case for patch_model

        Update Model
        """
        pass

    def test_post_model(self) -> None:
        """Test case for post_model

        Create Model
        """
        pass

    def test_put_model_metric_config(self) -> None:
        """Test case for put_model_metric_config

        Update Model Metric Configuration By Model Id
        """
        pass

    def test_put_model_metrics_schedule(self) -> None:
        """Test case for put_model_metrics_schedule

        Update Model Metrics Schedule
        """
        pass


if __name__ == '__main__':
    unittest.main()
