# coding: utf-8

"""
    Fastify Template API

    API documentation using Swagger

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from keplar_api.models.attribute_filter_group_schema_inner import AttributeFilterGroupSchemaInner

class TestAttributeFilterGroupSchemaInner(unittest.TestCase):
    """AttributeFilterGroupSchemaInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AttributeFilterGroupSchemaInner:
        """Test AttributeFilterGroupSchemaInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AttributeFilterGroupSchemaInner`
        """
        model = AttributeFilterGroupSchemaInner()
        if include_optional:
            return AttributeFilterGroupSchemaInner(
                kind = 'single',
                id = '',
                min = 1.337,
                max = 1.337,
                values = [
                    ''
                    ]
            )
        else:
            return AttributeFilterGroupSchemaInner(
                kind = 'single',
                id = '',
                values = [
                    ''
                    ],
        )
        """

    def testAttributeFilterGroupSchemaInner(self):
        """Test AttributeFilterGroupSchemaInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
