from _typeshed import Incomplete
from s3cd.operations import S3Operations as S3Operations

cli: Incomplete

def version_callback(value: bool): ...
def callback(version: bool = ...): ...
def upload_command(source_dir: str = ..., verbose: bool = ...): ...
