# weegit
WEEGIT_FOLDER_SUFFIX = "_weegit"
LFP_SUBFOLDER = "data"
LFP_EXTENSION = ".ch"
HEADER_FILENAME = "header.json"
SESSION_EXTENSION = ".json"
OTHER_SESSIONS_FOLDER = "sessions"
MAX_UNDO_HISTORY_SIZE = 30

# EEG
MIN_VISIBLE_CHANNELS = 1
MAX_VISIBLE_CHANNELS = 32
MIN_DURATION = 1
MAX_DURATION = 1000 * 1000 * 60 * 30
MIN_TIME_STEP = 1
MAX_TIME_STEP = 1000 * 1000 * 60  # 1 min
MIN_SCALE = 0.001
MAX_SCALE = 1000.0
MAX_START_POINT = 2_147_483_647  # max 32-bit integer
EEG_VOLTAGE_SCALE = 0.1
MIN_NUMBER_OF_DOTS_TO_DISPLAY = 1_000
MAX_NUMBER_OF_DOTS_TO_DISPLAY = 100_000
EEG_DEFAULT_NUMBER_OF_DOTS_TO_DISPLAY = 10_000
ANALOGUE_PANEL_HEIGHT = 120
DEFAULT_SPIKES_THRESHOLD = 5.0
CHANNELS_MAPPING_IMG_DEFAULT_WIDTH = 100
AUTO_SCROLL_STEP_INTERVAL_MS = 500

# global storage
APP_NAME = "weegit"
GLOBAL_STORAGE_FILENAME = "weegit.json"
RECENT_EXPERIMENTS_LIST_MAX_LENGTH = 8

# Documentation
DOCUMENTATION_LINK = "https://weegit.github.io/weegit/"

# Logging
MAX_LOG_ITEMS = 60

# Development
DEBUG = True
