from .price_study import get_price_study_add_edit_schema
from .chapter import get_chapter_add_edit_schema
from .work_item import get_work_item_add_edit_schema
from .product import get_product_add_schema, get_product_edit_schema
from .discount import get_discount_add_edit_schema
