"""
Minimal type stub for lumyn_sdk.util
"""
from typing import Any


class CircularBuffer:
    def __init__(self, capacity: int) -> None: ...
    def push(self, data: bytes) -> None: ...
    def pop(self) -> int: ...
    def front(self) -> int: ...
    def size(self) -> int: ...
    def capacity(self) -> int: ...


class hashing:
    class MD5:
        @staticmethod
        def hash(data: bytes) -> bytes: ...

    class IDCreator:
        @staticmethod
        def createId(input: str) -> int: ...


def createId(input: str) -> int: ...
