def pgrg_ordered(protected_groups: list[str], reference_groups: list[str], group_categories: list[str] | None = None) -> list[str] | list[list[str]]: ...
def compare_pandas_objects(obj1, obj2) -> bool: ...
