JAVA_NAN_STR = "NaN"
JAVA_POSITIVE_INFINITY_STR = "Infinity"
JAVA_NEGATIVE_INFINITY_STR = f"-{JAVA_POSITIVE_INFINITY_STR}"

JAVA_MIN_LOCAL_DATE_STR = "-999999999-01-01"
JAVA_MAX_LOCAL_DATE_STR = "+999999999-12-31"

JAVA_MIN_LOCAL_DATE_TIME_STR = f"{JAVA_MIN_LOCAL_DATE_STR}T00:00"
JAVA_MAX_LOCAL_DATE_TIME_STR = f"{JAVA_MAX_LOCAL_DATE_STR}T23:59:59.999999999"

JAVA_MIN_UTC_ZONED_DATE_TIME_STR = f"{JAVA_MIN_LOCAL_DATE_TIME_STR}Z[UTC]"
JAVA_MAX_UTC_ZONED_DATE_TIME_STR = f"{JAVA_MAX_LOCAL_DATE_TIME_STR}Z[UTC]"
