#  -*- coding: utf-8 -*-
"""
Author: Rafael R. L. Benevides
"""

from numpy.typing import NDArray

def tai_from_tt(jd12_tt: NDArray) -> NDArray: ...

def tt_from_tai(jd12_tai: NDArray) -> NDArray: ...

def utc_from_tai(jd12_tai: NDArray) -> NDArray: ...

def tai_from_utc(jd12_utc: NDArray) -> NDArray: ...

def ut1_from_utc(jd12_utc: NDArray) -> NDArray: ...

def utc_from_ut1(jd12_ut1: NDArray) -> NDArray: ...