message(STATUS "Using compiler: $ENV{PORTAL_C_COMPILER}")
set(CMAKE_C_COMPILER $ENV{PORTAL_C_COMPILER} CACHE FILEPATH "C compiler")
set(CMAKE_CXX_COMPILER $ENV{PORTAL_CPP_COMPILER} CACHE FILEPATH "C++ compiler")
