from typing import (
	Any,
	List,
	Tuple,
	Union
)


__all__ = [
	"NOISE_TYPEHINT",
	"NUMBER_TYPEHINT",
	"RANDOM_NOISE_TYPEHINT",
	"RANDOM_NUMBER_TYPEHINT",
	"RANDOM_VALUE_TYPEHINT"
]

NUMBER_TYPEHINT = Union[int, float]
RANDOM_NUMBER_TYPEHINT = Tuple[NUMBER_TYPEHINT, NUMBER_TYPEHINT]
NOISE_TYPEHINT = Union[NUMBER_TYPEHINT]

RANDOM_NOISE_TYPEHINT = Union[List[NOISE_TYPEHINT], RANDOM_NUMBER_TYPEHINT]
RANDOM_VALUE_TYPEHINT = Union[List[Any], RANDOM_NUMBER_TYPEHINT]
