"""Timeback server SDK."""

from .adapters.fastapi import to_fastapi_router
from .handlers import IdentityOnlyHandlers, InvalidSensorUrlError, MissingSyncedCourseIdError
from .handlers.activity import ActivityCourseResolutionError, resolve_activity_course
from .lib.resolve import (
    TimebackUserResolutionError,
    lookup_timeback_id_by_email,
    resolve_status_for_user_resolution_error,
    resolve_timeback_user_by_email,
)
from .timeback import (
    AppConfig,
    ConfigValidationError,
    CourseEnvOverrides,
    CourseOverrides,
    IdentityOnlyInstance,
    TimebackInstance,
    create_identity_only_server,
    create_server,
)
from .types import (
    ActivityBeforeSendData,
    ApiCredentials,
    BuildStateContext,
    CallbackErrorContext,
    CallbackSuccessContext,
    CustomIdentityConfig,
    IdentityConfig,
    IdentityOnlyCallbackSuccessContext,
    IdentityOnlyConfig,
    IdentityOnlySsoConfig,
    IdpData,
    OIDCTokens,
    OIDCUserInfo,
    SsoIdentityConfig,
    TimebackConfig,
    TimebackHooks,
)

__all__ = [
    "ActivityBeforeSendData",
    "ActivityCourseResolutionError",
    "ApiCredentials",
    "AppConfig",
    "BuildStateContext",
    "CallbackErrorContext",
    "CallbackSuccessContext",
    "ConfigValidationError",
    "CourseEnvOverrides",
    "CourseOverrides",
    "CustomIdentityConfig",
    "IdentityConfig",
    "IdentityOnlyCallbackSuccessContext",
    "IdentityOnlyConfig",
    "IdentityOnlyHandlers",
    "IdentityOnlyInstance",
    "IdentityOnlySsoConfig",
    "IdpData",
    "InvalidSensorUrlError",
    "MissingSyncedCourseIdError",
    "OIDCTokens",
    "OIDCUserInfo",
    "SsoIdentityConfig",
    "TimebackConfig",
    "TimebackHooks",
    "TimebackInstance",
    "TimebackUserResolutionError",
    "create_identity_only_server",
    "create_server",
    "lookup_timeback_id_by_email",
    "resolve_activity_course",
    "resolve_status_for_user_resolution_error",
    "resolve_timeback_user_by_email",
    "to_fastapi_router",
]
