set(CPACK_PROJECT_CONFIG_FILE "${CMAKE_CURRENT_LIST_DIR}/cpack.cmake")

include(${CMAKE_CURRENT_LIST_DIR}/base.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/wix.cmake)

set(CPACK_NSIS_MODIFY_PATH ON)

set(CPACK_DEB_COMPONENT_INSTALL ON)
set(CPACK_DEBIAN_APPS_PACKAGE_DEPENDS libgcc-s1)
set(CPACK_DEBIAN_DEVEL_PACKAGE_DEPENDS)

set(CPACK_ARCHIVE_COMPONENT_INSTALL ON)
