# SPDX-License-Identifier: Apache-2.0
# Copyright © 2025 Bijan Mousavi

"""Defines shared constants for CLI commands."""

from __future__ import annotations

from bijux_cli.core.enums import ColorMode, LogLevel, OutputFormat

OPT_QUIET = ("-q", "--quiet")
OPT_FORMAT = ("-f", "--format")
OPT_LOG_LEVEL = ("--log-level",)
OPT_COLOR = ("--color",)
OPT_PRETTY = "--pretty/--no-pretty"
OPT_HELP = ("-h", "--help")
PRETTY_FLAGS = ("--pretty", "--no-pretty")

ENV_CONFIG = "BIJUXCLI_CONFIG"
ENV_LOG_LEVEL = "BIJUXCLI_LOG_LEVEL"
ENV_COLOR = "BIJUXCLI_COLOR"
ENV_DISABLE_HISTORY = "BIJUXCLI_DISABLE_HISTORY"
ENV_TEST_MODE = "BIJUXCLI_TEST_MODE"
ENV_PREFIX = "BIJUXCLI_"
ENV_COMMAND_TIMEOUT = "BIJUXCLI_COMMAND_TIMEOUT"
ENV_DI_LIMIT = "BIJUXCLI_DI_LIMIT"
ENV_DOCS_OUT = "BIJUXCLI_DOCS_OUT"
ENV_TEST_IO_FAIL = "BIJUXCLI_TEST_IO_FAIL"
ENV_TEST_FORCE_SERIALIZE_FAIL = "BIJUXCLI_TEST_FORCE_SERIALIZE_FAIL"
ENV_TEST_FORCE_UNHEALTHY = "BIJUXCLI_TEST_FORCE_UNHEALTHY"
ENV_DEV_MODE = "BIJUXCLI_DEV_MODE"
ENV_VERSION = "BIJUXCLI_VERSION"
ENV_HISTORY_FILE = "BIJUXCLI_HISTORY_FILE"
ENV_BIN = "BIJUXCLI_BIN"
ENV_NO_COLOR = "NO_COLOR"

DEFAULT_LOG_LEVEL = LogLevel.INFO
DEFAULT_COLOR = ColorMode.AUTO
DEFAULT_FORMAT = OutputFormat.JSON
DEFAULT_PRETTY = True
DEFAULT_QUIET = False

DEFAULT_COMMAND_TIMEOUT = 30.0

__all__ = [
    "OPT_QUIET",
    "OPT_FORMAT",
    "OPT_LOG_LEVEL",
    "OPT_COLOR",
    "OPT_PRETTY",
    "OPT_HELP",
    "PRETTY_FLAGS",
    "ENV_CONFIG",
    "ENV_LOG_LEVEL",
    "ENV_COLOR",
    "ENV_DISABLE_HISTORY",
    "ENV_TEST_MODE",
    "ENV_PREFIX",
    "ENV_COMMAND_TIMEOUT",
    "ENV_DI_LIMIT",
    "ENV_DOCS_OUT",
    "ENV_TEST_IO_FAIL",
    "ENV_TEST_FORCE_SERIALIZE_FAIL",
    "ENV_TEST_FORCE_UNHEALTHY",
    "ENV_DEV_MODE",
    "ENV_VERSION",
    "ENV_HISTORY_FILE",
    "ENV_BIN",
    "ENV_NO_COLOR",
    "DEFAULT_LOG_LEVEL",
    "DEFAULT_COLOR",
    "DEFAULT_FORMAT",
    "DEFAULT_PRETTY",
    "DEFAULT_QUIET",
    "DEFAULT_COMMAND_TIMEOUT",
]
