class PLUGIN_SIGNATURES:
  """
  This class is used to store the plugin signatures for the different plugins.
  It is complementary to the PLUGIN_TYPES class.
  """
  NET_MON_01 = 'NET_MON_01'
  VIEW_SCENE_01 = 'VIEW_SCENE_01'
  CUSTOM_WEBAPI_01 = 'CUSTOM_CODE_FASTAPI_01'
  GENERIC_WEB_APP = 'GENERIC_WEB_APP'
  GENERIC_HTTP_SERVER = 'GENERIC_HTTP_SERVER'
  CUSTOM_EXEC_01 = 'CUSTOM_EXEC_01'
  CHAIN_DIST_CUSTOM_JOB_01 = 'PROCESS_REAL_TIME_COLLECTED_DATA_CUSTOM_EXEC_CHAIN_DIST'
  TELEGRAM_BASIC_BOT_01 = 'TELEGRAM_BASIC_BOT_01'  
  TELEGRAM_CONVERSATIONAL_BOT_01 = 'TELEGRAM_CONVERSATIONAL_BOT_01'
  NET_CONFIG_MONITOR = 'NET_CONFIG_MONITOR'
  CONTAINER_APP_RUNNER = 'CONTAINER_APP_RUNNER'
  WORKER_APP_RUNNER = 'WORKER_APP_RUNNER'
  # INSERT_NEW_PLUGIN_HERE
  
  
class DEFAULT_PIPELINES:
  ADMIN_PIPELINE = 'admin_pipeline'