"""
Prism theme configurations - minimalist with transparent backgrounds.
"""

# One Dark Pro inspired colors
THEMES = {
    "default": {
        "name": "One Dark",
        # All backgrounds transparent to use terminal's native background
        "screen_bg": "transparent",
        "chat_border": "#3e4452",
        "chat_bg": "transparent",
        "input_bg": "transparent",
        "input_focus_bg": "transparent",
        "status_bg": "transparent",
        "header_bg": "transparent",
        "footer_bg": "transparent",
        "scrollbar_color": "#4b5263",
        "scrollbar_bg": "transparent",
        # One Dark Pro palette
        "user_color": "#e5c07b",        # Yellow/gold for user
        "assistant_color": "#61afef",    # Blue for assistant
        "text_color": "#abb2bf",         # Default text
        "dim_color": "#5c6370",          # Comments/dim
        "accent_color": "#c678dd",       # Purple accent
        "tool_color": "#56b6c2",         # Cyan for tools
        "success_color": "#98c379",      # Green
        "warning_color": "#e5c07b",      # Yellow
        "error_color": "#e06c75",        # Red
        "code_theme": "one-dark",
        "remove_bg": "transparent",
        "add_bg": "transparent"
    },
    "github-dark": {
        "name": "GitHub Dark",
        "screen_bg": "transparent",
        "chat_border": "#30363d",
        "chat_bg": "transparent",
        "input_bg": "transparent",
        "input_focus_bg": "transparent",
        "status_bg": "transparent",
        "header_bg": "transparent",
        "footer_bg": "transparent",
        "scrollbar_color": "#484f58",
        "scrollbar_bg": "transparent",
        "user_color": "#f0883e",
        "assistant_color": "#58a6ff",
        "text_color": "#e6edf3",
        "dim_color": "#7d8590",
        "accent_color": "#1f6feb",
        "tool_color": "#a5a5ff",
        "success_color": "#3fb950",
        "warning_color": "#d29922",
        "error_color": "#f85149",
        "code_theme": "github-dark",
        "remove_bg": "transparent",
        "add_bg": "transparent"
    },
    "dracula": {
        "name": "Dracula",
        "screen_bg": "transparent",
        "chat_border": "#44475a",
        "chat_bg": "transparent",
        "input_bg": "transparent",
        "input_focus_bg": "transparent",
        "status_bg": "transparent",
        "header_bg": "transparent",
        "footer_bg": "transparent",
        "scrollbar_color": "#bd93f9",
        "scrollbar_bg": "transparent",
        "user_color": "#ffb86c",
        "assistant_color": "#8be9fd",
        "text_color": "#f8f8f2",
        "dim_color": "#6272a4",
        "accent_color": "#bd93f9",
        "tool_color": "#ff79c6",
        "success_color": "#50fa7b",
        "warning_color": "#f1fa8c",
        "error_color": "#ff5555",
        "code_theme": "dracula",
        "remove_bg": "transparent",
        "add_bg": "transparent"
    },
    "nord": {
        "name": "Nord",
        "screen_bg": "transparent",
        "chat_border": "#4c566a",
        "chat_bg": "transparent",
        "input_bg": "transparent",
        "input_focus_bg": "transparent",
        "status_bg": "transparent",
        "header_bg": "transparent",
        "footer_bg": "transparent",
        "scrollbar_color": "#5e81ac",
        "scrollbar_bg": "transparent",
        "user_color": "#d08770",
        "assistant_color": "#88c0d0",
        "text_color": "#eceff4",
        "dim_color": "#4c566a",
        "accent_color": "#81a1c1",
        "tool_color": "#b48ead",
        "success_color": "#a3be8c",
        "warning_color": "#ebcb8b",
        "error_color": "#bf616a",
        "code_theme": "nord",
        "remove_bg": "transparent",
        "add_bg": "transparent"
    },
    "monokai": {
        "name": "Monokai",
        "screen_bg": "transparent",
        "chat_border": "#49483e",
        "chat_bg": "transparent",
        "input_bg": "transparent",
        "input_focus_bg": "transparent",
        "status_bg": "transparent",
        "header_bg": "transparent",
        "footer_bg": "transparent",
        "scrollbar_color": "#ae81ff",
        "scrollbar_bg": "transparent",
        "user_color": "#fd971f",
        "assistant_color": "#f92672",
        "text_color": "#f8f8f2",
        "dim_color": "#75715e",
        "accent_color": "#66d9ef",
        "tool_color": "#ae81ff",
        "success_color": "#a6e22e",
        "warning_color": "#e6db74",
        "error_color": "#f92672",
        "code_theme": "monokai",
        "remove_bg": "transparent",
        "add_bg": "transparent"
    },
    "gruvbox": {
        "name": "Gruvbox",
        "screen_bg": "transparent",
        "chat_border": "#504945",
        "chat_bg": "transparent",
        "input_bg": "transparent",
        "input_focus_bg": "transparent",
        "status_bg": "transparent",
        "header_bg": "transparent",
        "footer_bg": "transparent",
        "scrollbar_color": "#83a598",
        "scrollbar_bg": "transparent",
        "user_color": "#fe8019",
        "assistant_color": "#83a598",
        "text_color": "#ebdbb2",
        "dim_color": "#928374",
        "accent_color": "#d3869b",
        "tool_color": "#b16286",
        "success_color": "#b8bb26",
        "warning_color": "#fabd2f",
        "error_color": "#fb4934",
        "code_theme": "gruvbox-dark",
        "remove_bg": "transparent",
        "add_bg": "transparent"
    },
    "tokyo-night": {
        "name": "Tokyo Night",
        "screen_bg": "transparent",
        "chat_border": "#414868",
        "chat_bg": "transparent",
        "input_bg": "transparent",
        "input_focus_bg": "transparent",
        "status_bg": "transparent",
        "header_bg": "transparent",
        "footer_bg": "transparent",
        "scrollbar_color": "#7aa2f7",
        "scrollbar_bg": "transparent",
        "user_color": "#ff9e64",
        "assistant_color": "#7aa2f7",
        "text_color": "#c0caf5",
        "dim_color": "#565f89",
        "accent_color": "#bb9af7",
        "tool_color": "#9d7cd8",
        "success_color": "#9ece6a",
        "warning_color": "#e0af68",
        "error_color": "#f7768e",
        "code_theme": "monokai",
        "remove_bg": "transparent",
        "add_bg": "transparent"
    },
    "catppuccin": {
        "name": "Catppuccin",
        "screen_bg": "transparent",
        "chat_border": "#45475a",
        "chat_bg": "transparent",
        "input_bg": "transparent",
        "input_focus_bg": "transparent",
        "status_bg": "transparent",
        "header_bg": "transparent",
        "footer_bg": "transparent",
        "scrollbar_color": "#cba6f7",
        "scrollbar_bg": "transparent",
        "user_color": "#f9e2af",
        "assistant_color": "#89b4fa",
        "text_color": "#cdd6f4",
        "dim_color": "#6c7086",
        "accent_color": "#cba6f7",
        "tool_color": "#f5c2e7",
        "success_color": "#a6e3a1",
        "warning_color": "#fab387",
        "error_color": "#f38ba8",
        "code_theme": "monokai",
        "remove_bg": "transparent",
        "add_bg": "transparent"
    },
    "minimal": {
        "name": "Minimal",
        "screen_bg": "transparent",
        "chat_border": "#444444",
        "chat_bg": "transparent",
        "input_bg": "transparent",
        "input_focus_bg": "transparent",
        "status_bg": "transparent",
        "header_bg": "transparent",
        "footer_bg": "transparent",
        "scrollbar_color": "#666666",
        "scrollbar_bg": "transparent",
        "user_color": "#ffffff",
        "assistant_color": "#aaaaaa",
        "text_color": "#cccccc",
        "dim_color": "#666666",
        "accent_color": "#888888",
        "tool_color": "#999999",
        "success_color": "#88ff88",
        "warning_color": "#ffff88",
        "error_color": "#ff8888",
        "code_theme": "monokai",
        "remove_bg": "transparent",
        "add_bg": "transparent"
    }
}
