from __future__ import annotations

from datetime import datetime, timedelta
from typing import Any, Callable


class UUID4:
    def __init__(self) -> None: ...
    @property
    def value(self) -> str: ...
    @staticmethod
    def from_str(value: str) -> UUID4: ...


class TraderId:
    def __init__(self, value: str) -> None: ...
    @property
    def value(self) -> str: ...
    def get_tag(self) -> str: ...


class TimeEvent:
    def __init__(self, name: str, event_id: UUID4, ts_event: int, ts_init: int) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def id(self) -> UUID4: ...
    @property
    def ts_event(self) -> int: ...
    @property
    def ts_init(self) -> int: ...


class LiveClock:
    def __init__(self) -> None: ...
    @property
    def timer_names(self) -> list[str]: ...
    @property
    def timer_count(self) -> int: ...
    def timestamp(self) -> float: ...
    def timestamp_ms(self) -> int: ...
    def timestamp_us(self) -> int: ...
    def timestamp_ns(self) -> int: ...
    def utc_now(self) -> datetime: ...
    def local_now(self, tz: Any) -> datetime: ...
    def register_default_handler(self, callback: Callable[[TimeEvent], Any]) -> None: ...
    def set_time_alert(
        self,
        name: str,
        alert_time: datetime,
        callback: Callable[[TimeEvent], Any] | None = ...,
        allow_past: bool = ...,
    ) -> None: ...
    def set_time_alert_ns(
        self,
        name: str,
        alert_time_ns: int,
        callback: Callable[[TimeEvent], Any] | None = ...,
        allow_past: bool = ...,
    ) -> None: ...
    def set_timer(
        self,
        name: str,
        interval: timedelta,
        start_time: datetime | None = ...,
        stop_time: datetime | None = ...,
        callback: Callable[[TimeEvent], Any] | None = ...,
        allow_past: bool = ...,
        fire_immediately: bool = ...,
    ) -> None: ...
    def set_timer_ns(
        self,
        name: str,
        interval_ns: int,
        start_time_ns: int,
        stop_time_ns: int,
        callback: Callable[[TimeEvent], Any] | None = ...,
        allow_past: bool = ...,
        fire_immediately: bool = ...,
    ) -> None: ...
    def next_time_ns(self, name: str) -> int: ...
    def cancel_timer(self, name: str) -> None: ...
    def cancel_timers(self) -> None: ...


class TestClock:
    def __init__(self) -> None: ...
    @property
    def timer_names(self) -> list[str]: ...
    @property
    def timer_count(self) -> int: ...
    def timestamp(self) -> float: ...
    def timestamp_ms(self) -> int: ...
    def timestamp_us(self) -> int: ...
    def timestamp_ns(self) -> int: ...
    def utc_now(self) -> datetime: ...
    def local_now(self, tz: Any) -> datetime: ...
    def register_default_handler(self, callback: Callable[[TimeEvent], Any]) -> None: ...
    def set_time_alert(
        self,
        name: str,
        alert_time: datetime,
        callback: Callable[[TimeEvent], Any] | None = ...,
        allow_past: bool = ...,
    ) -> None: ...
    def set_time_alert_ns(
        self,
        name: str,
        alert_time_ns: int,
        callback: Callable[[TimeEvent], Any] | None = ...,
        allow_past: bool = ...,
    ) -> None: ...
    def set_timer(
        self,
        name: str,
        interval: timedelta,
        start_time: datetime | None = ...,
        stop_time: datetime | None = ...,
        callback: Callable[[TimeEvent], Any] | None = ...,
        allow_past: bool = ...,
        fire_immediately: bool = ...,
    ) -> None: ...
    def set_timer_ns(
        self,
        name: str,
        interval_ns: int,
        start_time_ns: int,
        stop_time_ns: int,
        callback: Callable[[TimeEvent], Any] | None = ...,
        allow_past: bool = ...,
        fire_immediately: bool = ...,
    ) -> None: ...
    def next_time_ns(self, name: str) -> int: ...
    def cancel_timer(self, name: str) -> None: ...
    def cancel_timers(self) -> None: ...
    def advance_time(self, to_time_ns: int, set_time: bool = ...) -> list[TimeEvent]: ...


class Subscription:
    def __init__(self, topic: str, handler: Callable[..., Any], priority: int = ...) -> None: ...
    @property
    def topic(self) -> str: ...
    @property
    def handler(self) -> Callable[..., Any]: ...
    @property
    def priority(self) -> int: ...


class MessageBus:
    def __init__(
        self,
        trader_id: TraderId,
        clock: Any,
        instance_id: UUID4 | None = ...,
        name: str | None = ...,
        serializer: Any | None = ...,
        database: Any | None = ...,
        config: Any | None = ...,
    ) -> None: ...
    @property
    def trader_id(self) -> TraderId: ...
    @property
    def instance_id(self) -> UUID4: ...
    @property
    def name(self) -> str: ...
    @property
    def has_backing(self) -> bool: ...
    @property
    def sent_count(self) -> int: ...
    @sent_count.setter
    def sent_count(self, value: int) -> None: ...
    @property
    def req_count(self) -> int: ...
    @req_count.setter
    def req_count(self, value: int) -> None: ...
    @property
    def res_count(self) -> int: ...
    @res_count.setter
    def res_count(self, value: int) -> None: ...
    @property
    def pub_count(self) -> int: ...
    @pub_count.setter
    def pub_count(self, value: int) -> None: ...
    @property
    def serializer(self) -> Any | None: ...
    @serializer.setter
    def serializer(self, value: Any | None) -> None: ...
    def endpoints(self) -> list[str]: ...
    def topics(self) -> list[str]: ...
    def subscriptions(self, pattern: str | None = ...) -> list[Subscription]: ...
    def streaming_types(self) -> set[type[Any]]: ...
    def has_subscribers(self, pattern: str | None = ...) -> bool: ...
    def is_subscribed(self, topic: str, handler: Callable[..., Any]) -> bool: ...
    def is_pending_request(self, request_id: Any) -> bool: ...
    def is_streaming_type(self, cls: Any) -> bool: ...
    def dispose(self) -> None: ...
    def register(self, endpoint: str, handler: Callable[..., Any]) -> None: ...
    def deregister(self, endpoint: str, handler: Callable[..., Any]) -> None: ...
    def add_streaming_type(self, cls: Any) -> None: ...
    def add_listener(self, listener: Any) -> None: ...
    def send(self, endpoint: str, msg: Any) -> None: ...
    def request(self, endpoint: str, request: Any) -> None: ...
    def response(self, response: Any) -> None: ...
    def subscribe(self, topic: str, handler: Callable[..., Any], priority: int = ...) -> None: ...
    def unsubscribe(self, topic: str, handler: Callable[..., Any]) -> None: ...
    def publish(self, topic: str, msg: Any, external_pub: bool = ...) -> None: ...


def hmac_signature(secret: str, data: str) -> str: ...
def rsa_signature(private_key_pem: str, data: str) -> str: ...
def ed25519_signature(private_key: bytes, data: str) -> str: ...
def is_matching_py(topic: str, pattern: str) -> bool: ...
