from .client_pb2 import *
from typing import Any

class MsgType:
    ping: int
    pong: int
    not_login: int
    error_msg: int
    login_req: int
    login_rsp: int
    strategy_crtl_req: int
    strategy_crtl_rsp: int
    update_strategy_param_req: int
    update_strategy_param_rsp: int
    update_strategy_param_event: int
    update_strategy_global_param_req: int
    update_strategy_global_param_rsp: int
    update_strategy_global_param_event: int
    signal_control_req: int
    signal_control_rsp: int
    qry_strategy_stat_req: int
    qry_strategy_stat_rsp: int
    strategy_stat_event: int
    strategy_log_event: int
    save_strategy_params_to_default_req: int
    save_strategy_params_to_default_rsp: int
    apply_default_strategy_params_req: int
    apply_default_strategy_params_rsp: int
    update_default_strategy_params_event: int
    subscribe_req: int
    subscribe_rsp: int
    qry_quote_req: int
    qry_quote_rsp: int
    qry_fund_req: int
    qry_fund_rsp: int
    qry_posi_req: int
    qry_posi_rsp: int
    qry_order_req: int
    qry_order_rsp: int
    qry_trade_req: int
    qry_trade_rsp: int
    qry_strategy_position_req: int
    qry_strategy_position_rsp: int
    qry_sbl_list_req: int
    qry_sbl_list_rsp: int
    lock_sbl_req: int
    lock_sbl_rsp: int
    qry_lock_record_req: int
    qry_lock_record_rsp: int
    qry_lock_position_req: int
    qry_lock_position_rsp: int
    md_snapshot: int
    etf_quote_snapshot: int
    signal_snapshot: int
    bar_matrix: int
    order_event: int
    place_order: int
    place_order_confirm: int
    place_order_reject: int
    place_order_pending_confirm: int
    cancel_order: int
    cancel_all_order: int
    trade_confirm: int
    cancel_order_confirm: int
    cancel_order_reject: int
    cancel_order_pending_confirm: int
    update_risk_param_req: int
    update_risk_param_rsp: int
    update_risk_market_params_req: int
    update_risk_market_params_rsp: int
    book_trade_req: int
    book_trade_rsp: int
    book_event: int
    qry_book_req: int
    qry_book_rsp: int
    update_signal_params_req: int
    update_signal_params_rsp: int
    signal_params_event: int
    new_signal_params_req: int
    new_signal_params_rsp: int
    place_basket_order: int
    place_basket_order_rsp: int
    basket_order_event: int
    qry_basket_order_req: int
    qry_basket_order_rsp: int
    qry_basket_order_stat_req: int
    qry_basket_order_stat_rsp: int
    qry_basket_info_req: int
    qry_basket_info_rsp: int
    cancel_basket_order: int
    cancel_basket_order_rsp: int
    append_basket_order: int
    append_basket_order_rsp: int
    new_basket_template: int
    new_basket_template_rsp: int
    update_basket_template: int
    update_basket_template_rsp: int
    place_arbitrage_order: int
    place_arbitrage_order_rsp: int
    qry_arbitrage_order_req: int
    qry_arbitrage_order_rsp: int
    arbitrage_order_event: int
    cancel_arbitrage_order: int
    cancel_arbitrage_order_rsp: int
    place_batch_order: int
    place_batch_order_rsp: int
    qry_broker_position_req: int
    qry_broker_position_rsp: int
    qry_broker_fund_req: int
    qry_broker_fund_rsp: int
    qry_strategy_log_req: int
    qry_strategy_log_rsp: int
    qry_instrument_req: int
    qry_instrument_rsp: int
    qry_strategy_info_req: int
    qry_strategy_info_rsp: int
    qry_signal_info_req: int
    qry_signal_info_rsp: int
    qry_node_req: int
    qry_node_rsp: int
    qry_risk_item_req: int
    qry_risk_itme_rsp: int
    qry_risk_market_params_req: int
    qry_risk_market_params_rsp: int
    qry_quote_instance_req: int
    qry_quote_instance_rsp: int
    manager_sync_req: int
    manager_sync_rsp: int

MSG_TYPE_MAP: dict[int, type[Any]]

def serialize(proto_message: Any) -> bytes: ...
def parse_proto_message(message_type: int, raw_message: bytes) -> Any: ...
def deserialize(raw_response: bytes, message_type: int | None = None) -> Any: ...
