from _typeshed import Incomplete
from minjiang_host_client.utils.request import request as request

class WorkerMonitor:
    worker_name: Incomplete
    worker_type: Incomplete
    start_time: Incomplete
    last_activity: Incomplete
    task_count: int
    error_count: int
    status: str
    direct_link_server: Incomplete
    direct_link_port: Incomplete
    status_report_thread: Incomplete
    current_tasks: Incomplete
    task_history: Incomplete
    queue_info: Incomplete
    resource_usage: Incomplete
    performance_metrics: Incomplete
    experiment_progress: Incomplete
    experiment_lifecycle: Incomplete
    debug_info: Incomplete
    def __init__(self, worker_name: str, worker_type: str, direct_link_server: str = 'localhost', direct_link_port: int = 6887) -> None: ...
    def update_activity(self) -> None: ...
    def increment_step_count(self, exp_id: int = None, direct_exp_id: int = None): ...
    def increment_error_count(self, exp_id: int = None, direct_exp_id: int = None): ...
    def add_current_task(self, space_id: str, task_type: str, exp_id: int = None, direct_exp_id: int = None): ...
    def remove_current_task(self, space_id: str): ...
    def update_queue_info(self, queue_name: str, size: int, details: dict = None): ...
    def update_resource_usage(self, cpu_percent: float, memory_mb: float, disk_usage_mb: float = 0.0): ...
    def update_performance_metrics(self, avg_duration: float, max_duration: float, throughput: float): ...
    def update_experiment_progress(self, exp_id: int = None, direct_exp_id: int = None, steps: int = None, total_steps: int = None, percentage: float = None, progress: str = None): ...
    def get_experiment_progress(self, exp_id: int = None, direct_exp_id: int = None): ...
    def get_all_experiment_progress(self): ...
    def send_experiment_info(self, transfer: dict): ...
