class Encoder:
    def __init__(self) -> None: ...
    def set_bit_rate(self, bitrate_kbps: int) -> None: ...
    def set_in_sample_rate(self, sample_rate: int) -> None: ...
    def set_channels(self, channels: int) -> None: ...
    def set_quality(self, quality: int) -> None: ...
    def encode(self, pcm_bytes: bytes) -> bytes: ...
    def flush(self) -> bytes: ...
