from minjiang_client.group.group import Group as Group
from typing import Any

class LocalGroup(Group):
    def __init__(self, group_name: str, space_id: int = None, space_version: int = None, space_parameters: dict[str, Any] = None, temporary_parameters: dict[str, Any] = None) -> None: ...
    @property
    def space_id(self) -> int: ...
    def check_key_format(self, key: str) -> bool: ...
    def get_device_parameter(self, key: str | list[str]): ...
    def submit_space_parameter(self) -> None: ...
    def set_temporary_parameter(self, key: str, value: Any): ...
