"""Type stubs for varps module."""

from typing import Any

def extract_bits(value: int, start_bit: int, end_bit: int) -> int: ...
def get_varbit_info(varbit_id: int) -> dict[str, Any] | None: ...
def get_varp_by_name(name: str) -> int | None: ...
def get_varp_by_index(varp_id: int) -> int | None: ...
def get_varbit_by_index(varbit_id: int) -> int | None: ...
def get_varbit_by_name(name: str) -> int | None: ...
def list_varps(filter_name: str | None = None) -> dict[int, dict[str, Any]]: ...
def list_varbits(filter_name: str | None = None) -> dict[int, dict[str, Any]]: ...
def get_varc_value(varc_id: int) -> Any | None: ...
def get_varc_name(varc_id: int) -> str | None: ...

# Setter functions for cache_manager
def set_varps_data(data: dict[int, dict[str, Any]]) -> None: ...
def set_varbits_data(data: dict[int, dict[str, Any]]) -> None: ...
def get_varps_data_count() -> int: ...
def get_varbits_data_count() -> int: ...
