from minjiang_host_client.direct_group import DirectLinkWorkerClient as DirectLinkWorkerClient
from minjiang_host_client.utils.local import get_cache_dir as get_cache_dir

def write_terminate_signal(exp_id: int | None, direct_exp_id: int | None, terminate_type: str, message: str = '') -> None: ...
def check_terminate_signal(exp_id: int = None, direct_exp_id: int = None, upload_status: bool = False, direct_client: DirectLinkWorkerClient | None = None) -> bool: ...
def upload_cancel_status(cancel_id: int, terminate_type: str, exp_type: str, message: str, direct_client: DirectLinkWorkerClient | None = None) -> bool: ...
def cleanup_old_ts_files() -> None: ...
def list_terminate_signal(): ...
def get_terminate_signal(exp_id: int): ...
def remove_terminate_signal(exp_id: int): ...
