from _typeshed import Incomplete
from minjiang_host_client.utils.request import request as request

class WorkerRegistrar:
    direct_link_server_url: Incomplete
    registered: bool
    registration_thread: Incomplete
    def __init__(self) -> None: ...
    def register_worker(self, worker_name: str, worker_type: str, monitor_server: str, monitor_port: int, worker_port: int): ...
    def unregister_worker(self, worker_name: str): ...
    def start_auto_register(self, worker_name: str, worker_type: str, monitor_server: str, monitor_port: int, worker_port: int): ...

def get_global_registrar() -> WorkerRegistrar: ...
def register_worker(worker_name: str, worker_type: str, monitor_server: str, monitor_port: int, worker_port: int): ...
def unregister_worker(worker_name: str): ...
