from _typeshed import Incomplete

class FileTypeUtils:
    MIME_TYPE_MAPPING: Incomplete
    FILE_TYPE_MAPPING: Incomplete
    @staticmethod
    def get_file_type(file_extension: str) -> str: ...
    @staticmethod
    def get_mime_type(file_name: str) -> str | None: ...
    @staticmethod
    def get_file_info(file_name: str) -> tuple[str, str, str | None]: ...
    @staticmethod
    def is_code_file(file_extension: str) -> bool: ...
    @staticmethod
    def is_text_file(file_extension: str) -> bool: ...
    @staticmethod
    def is_image_file(file_extension: str) -> bool: ...
    @staticmethod
    def is_document_file(file_extension: str) -> bool: ...
    @staticmethod
    def is_archive_file(file_extension: str) -> bool: ...
    @staticmethod
    def get_supported_extensions() -> dict[str, list]: ...
