class PipeWriter:
    def __init__(self, name: str): ...
    def open(self): ...
    async def write(self): ...
    async def read(self): ...
    async def wait_for_connect(self, timeout=0): ...
    def close(self): ...

    def __del__(self):
        self.close()
