from _typeshed import Incomplete
from minjiang_client.utils.json_database import Column as Column, JSONDatatable as JSONDatatable

class Database:
    db_path: Incomplete
    conn: Incomplete
    lock: Incomplete
    def __init__(self) -> None: ...
    def add_device(self, device: dict) -> bool: ...
    def delete_device(self, sn: str, group_name: str) -> bool: ...
    def update_device(self, sn: str, update_data: dict) -> bool: ...
    def get_devices_by_group(self, group_name: str) -> list[dict]: ...
    def create_group_table(self, group_name: str, sn_list: list[str]) -> bool: ...
    def get_device(self, sn: str) -> dict | None: ...
    def get_all_devices(self) -> list[dict]: ...
    def close(self) -> None: ...
