from _typeshed import Incomplete
from s3cd.settings import S3Settings as S3Settings

class S3ClientError(Exception): ...

class S3Client:
    settings: Incomplete
    def __init__(self, settings: S3Settings) -> None: ...
    @property
    def client(self): ...
    def get_content_type(self, file_path: str) -> str: ...
    def upload_file(self, file_path: str, bucket: str, key: str) -> None: ...
    def put_object(self, bucket: str, key: str, body: bytes, content_type: str = 'application/json') -> None: ...
