
from typing import Optional, Any, Union
from enum import Enum

def init(path: Optional[str] = None) -> None: ...
def shutdown() -> None: ...
def get_dll_path() -> str: ...

class DistanceModel(Enum):
    NONE: int
    INVERSE: int
    INVERSE_CLAMPED: int
    LINEAR: int
    LINEAR_CLAMPED: int
    EXPONENT: int
    EXPONENT_CLAMPED: int

class Device:
    def __init__(self, name: str = "") -> None: ...

class Context:
    def __init__(self, device: Device) -> None: ...

class AudioData:
    def __init__(self, path: str, surround: bool = False) -> None: ...
    
    @property
    def sample_rate(self) -> int: ...
    @property
    def channels(self) -> int: ...
    @property
    def bits_per_sample(self) -> int: ...
    @property
    def bytes_per_sample(self) -> int: ...
    @property
    def frames(self) -> int: ...
    @property
    def samples(self) -> int: ...
    @property
    def duration(self) -> float: ...
    @property
    def path(self) -> str: ...
    @property
    def surround(self) -> bool: ...
    
    def decode(self) -> bytes: ...

class Buffer:
    def __init__(self, data: AudioData) -> None: ...

class Source:
    def __init__(self) -> None: ...
    
    def play(self) -> None: ...
    def pause(self) -> None: ...
    def stop(self) -> None: ...
    def set_buffer(self, buffer: Buffer) -> None: ...
    
    @property
    def playing(self) -> bool: ...
    @property
    def paused(self) -> bool: ...
    @property
    def stopped(self) -> bool: ...
    
    @property
    def gain(self) -> float: ...
    @gain.setter
    def gain(self, value: float) -> None: ...
    
    @property
    def pitch(self) -> float: ...
    @pitch.setter
    def pitch(self, value: float) -> None: ...
    
    @property
    def offset(self) -> float: ...
    @offset.setter
    def offset(self, value: float) -> None: ...
    
    @property
    def looping(self) -> bool: ...
    @looping.setter
    def looping(self, value: bool) -> None: ...
    
    @property
    def relative(self) -> bool: ...
    @relative.setter
    def relative(self, value: bool) -> None: ...
    
    @property
    def reference_distance(self) -> float: ...
    @reference_distance.setter
    def reference_distance(self, value: float) -> None: ...
    
    @property
    def rolloff_factor(self) -> float: ...
    @rolloff_factor.setter
    def rolloff_factor(self, value: float) -> None: ...
    
    @property
    def max_distance(self) -> float: ...
    @max_distance.setter
    def max_distance(self, value: float) -> None: ...
    
    def set_position(self, x: float, y: float, z: float) -> None: ...
    def set_velocity(self, x: float, y: float, z: float) -> None: ...

class Listener:
    @property
    @staticmethod
    def gain() -> float: ...
    @gain.setter
    @staticmethod
    def gain(value: float) -> None: ...
    
    @property
    @staticmethod
    def distance_model() -> DistanceModel: ...
    @distance_model.setter
    @staticmethod
    def distance_model(model: DistanceModel) -> None: ...
    
    @staticmethod
    def set_position(x: float, y: float, z: float) -> None: ...
    @staticmethod
    def set_velocity(x: float, y: float, z: float) -> None: ...
    @staticmethod
    def set_orientation(fx: float, fy: float, fz: float, ux: float, uy: float, uz: float) -> None: ...
    @staticmethod
    def reset() -> None: ...

class Stream:
    def __init__(self, path: str, buffer_size: int = 65536) -> None: ...
    
    def update(self) -> None: ...
    def play(self) -> None: ...
    def pause(self) -> None: ...
    def stop(self) -> None: ...
    
    @property
    def gain(self) -> float: ...
    @gain.setter
    def gain(self, value: float) -> None: ...
    
    @property
    def pitch(self) -> float: ...
    @pitch.setter
    def pitch(self, value: float) -> None: ...
    
    @property
    def offset(self) -> float: ...
    @offset.setter
    def offset(self, value: float) -> None: ...
    
    @property
    def looping(self) -> bool: ...
    @looping.setter
    def looping(self, value: bool) -> None: ...
    
    @property
    def surround(self) -> bool: ...
    @surround.setter
    def surround(self, value: bool) -> None: ...
    
    def set_position(self, x: float, y: float, z: float) -> None: ...
    def set_velocity(self, x: float, y: float, z: float) -> None: ...
    
    @property
    def duration(self) -> float: ...
    @property
    def progress(self) -> float: ...