# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['SdwanPathQualityProfileArgs', 'SdwanPathQualityProfile']

@pulumi.input_type
class SdwanPathQualityProfileArgs:
    def __init__(__self__, *,
                 metric: pulumi.Input['SdwanPathQualityProfileMetricArgs'],
                 device: Optional[pulumi.Input[_builtins.str]] = None,
                 folder: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 snippet: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a SdwanPathQualityProfile resource.
        :param pulumi.Input['SdwanPathQualityProfileMetricArgs'] metric: Metric
        :param pulumi.Input[_builtins.str] device: The device in which the resource is defined
        :param pulumi.Input[_builtins.str] folder: The folder in which the resource is defined
               
               > ℹ️ **Note:** You must specify exactly one of `device`, `folder`, and `snippet`.
        :param pulumi.Input[_builtins.str] name: Profile name
        :param pulumi.Input[_builtins.str] snippet: The snippet in which the resource is defined
               
               > ℹ️ **Note:** You must specify exactly one of `device`, `folder`, and `snippet`.
        """
        pulumi.set(__self__, "metric", metric)
        if device is not None:
            pulumi.set(__self__, "device", device)
        if folder is not None:
            pulumi.set(__self__, "folder", folder)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if snippet is not None:
            pulumi.set(__self__, "snippet", snippet)

    @_builtins.property
    @pulumi.getter
    def metric(self) -> pulumi.Input['SdwanPathQualityProfileMetricArgs']:
        """
        Metric
        """
        return pulumi.get(self, "metric")

    @metric.setter
    def metric(self, value: pulumi.Input['SdwanPathQualityProfileMetricArgs']):
        pulumi.set(self, "metric", value)

    @_builtins.property
    @pulumi.getter
    def device(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The device in which the resource is defined
        """
        return pulumi.get(self, "device")

    @device.setter
    def device(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "device", value)

    @_builtins.property
    @pulumi.getter
    def folder(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The folder in which the resource is defined

        > ℹ️ **Note:** You must specify exactly one of `device`, `folder`, and `snippet`.
        """
        return pulumi.get(self, "folder")

    @folder.setter
    def folder(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "folder", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Profile name
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def snippet(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The snippet in which the resource is defined

        > ℹ️ **Note:** You must specify exactly one of `device`, `folder`, and `snippet`.
        """
        return pulumi.get(self, "snippet")

    @snippet.setter
    def snippet(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "snippet", value)


@pulumi.input_type
class _SdwanPathQualityProfileState:
    def __init__(__self__, *,
                 device: Optional[pulumi.Input[_builtins.str]] = None,
                 folder: Optional[pulumi.Input[_builtins.str]] = None,
                 metric: Optional[pulumi.Input['SdwanPathQualityProfileMetricArgs']] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 snippet: Optional[pulumi.Input[_builtins.str]] = None,
                 tfid: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering SdwanPathQualityProfile resources.
        :param pulumi.Input[_builtins.str] device: The device in which the resource is defined
        :param pulumi.Input[_builtins.str] folder: The folder in which the resource is defined
               
               > ℹ️ **Note:** You must specify exactly one of `device`, `folder`, and `snippet`.
        :param pulumi.Input['SdwanPathQualityProfileMetricArgs'] metric: Metric
        :param pulumi.Input[_builtins.str] name: Profile name
        :param pulumi.Input[_builtins.str] snippet: The snippet in which the resource is defined
               
               > ℹ️ **Note:** You must specify exactly one of `device`, `folder`, and `snippet`.
        """
        if device is not None:
            pulumi.set(__self__, "device", device)
        if folder is not None:
            pulumi.set(__self__, "folder", folder)
        if metric is not None:
            pulumi.set(__self__, "metric", metric)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if snippet is not None:
            pulumi.set(__self__, "snippet", snippet)
        if tfid is not None:
            pulumi.set(__self__, "tfid", tfid)

    @_builtins.property
    @pulumi.getter
    def device(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The device in which the resource is defined
        """
        return pulumi.get(self, "device")

    @device.setter
    def device(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "device", value)

    @_builtins.property
    @pulumi.getter
    def folder(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The folder in which the resource is defined

        > ℹ️ **Note:** You must specify exactly one of `device`, `folder`, and `snippet`.
        """
        return pulumi.get(self, "folder")

    @folder.setter
    def folder(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "folder", value)

    @_builtins.property
    @pulumi.getter
    def metric(self) -> Optional[pulumi.Input['SdwanPathQualityProfileMetricArgs']]:
        """
        Metric
        """
        return pulumi.get(self, "metric")

    @metric.setter
    def metric(self, value: Optional[pulumi.Input['SdwanPathQualityProfileMetricArgs']]):
        pulumi.set(self, "metric", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Profile name
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def snippet(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The snippet in which the resource is defined

        > ℹ️ **Note:** You must specify exactly one of `device`, `folder`, and `snippet`.
        """
        return pulumi.get(self, "snippet")

    @snippet.setter
    def snippet(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "snippet", value)

    @_builtins.property
    @pulumi.getter
    def tfid(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "tfid")

    @tfid.setter
    def tfid(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "tfid", value)


@pulumi.type_token("scm:index/sdwanPathQualityProfile:SdwanPathQualityProfile")
class SdwanPathQualityProfile(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 device: Optional[pulumi.Input[_builtins.str]] = None,
                 folder: Optional[pulumi.Input[_builtins.str]] = None,
                 metric: Optional[pulumi.Input[Union['SdwanPathQualityProfileMetricArgs', 'SdwanPathQualityProfileMetricArgsDict']]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 snippet: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        SdwanPathQualityProfile resource

        ## Import

        The following command can be used to import a resource not managed by Terraform:

        bash

        ```sh
        $ pulumi import scm:index/sdwanPathQualityProfile:SdwanPathQualityProfile example folder:::id
        ```

        or

        bash

        ```sh
        $ pulumi import scm:index/sdwanPathQualityProfile:SdwanPathQualityProfile example :snippet::id
        ```

        or

        bash

        ```sh
        $ pulumi import scm:index/sdwanPathQualityProfile:SdwanPathQualityProfile example ::device:id
        ```

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] device: The device in which the resource is defined
        :param pulumi.Input[_builtins.str] folder: The folder in which the resource is defined
               
               > ℹ️ **Note:** You must specify exactly one of `device`, `folder`, and `snippet`.
        :param pulumi.Input[Union['SdwanPathQualityProfileMetricArgs', 'SdwanPathQualityProfileMetricArgsDict']] metric: Metric
        :param pulumi.Input[_builtins.str] name: Profile name
        :param pulumi.Input[_builtins.str] snippet: The snippet in which the resource is defined
               
               > ℹ️ **Note:** You must specify exactly one of `device`, `folder`, and `snippet`.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: SdwanPathQualityProfileArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        SdwanPathQualityProfile resource

        ## Import

        The following command can be used to import a resource not managed by Terraform:

        bash

        ```sh
        $ pulumi import scm:index/sdwanPathQualityProfile:SdwanPathQualityProfile example folder:::id
        ```

        or

        bash

        ```sh
        $ pulumi import scm:index/sdwanPathQualityProfile:SdwanPathQualityProfile example :snippet::id
        ```

        or

        bash

        ```sh
        $ pulumi import scm:index/sdwanPathQualityProfile:SdwanPathQualityProfile example ::device:id
        ```

        :param str resource_name: The name of the resource.
        :param SdwanPathQualityProfileArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(SdwanPathQualityProfileArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 device: Optional[pulumi.Input[_builtins.str]] = None,
                 folder: Optional[pulumi.Input[_builtins.str]] = None,
                 metric: Optional[pulumi.Input[Union['SdwanPathQualityProfileMetricArgs', 'SdwanPathQualityProfileMetricArgsDict']]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 snippet: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = SdwanPathQualityProfileArgs.__new__(SdwanPathQualityProfileArgs)

            __props__.__dict__["device"] = device
            __props__.__dict__["folder"] = folder
            if metric is None and not opts.urn:
                raise TypeError("Missing required property 'metric'")
            __props__.__dict__["metric"] = metric
            __props__.__dict__["name"] = name
            __props__.__dict__["snippet"] = snippet
            __props__.__dict__["tfid"] = None
        super(SdwanPathQualityProfile, __self__).__init__(
            'scm:index/sdwanPathQualityProfile:SdwanPathQualityProfile',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            device: Optional[pulumi.Input[_builtins.str]] = None,
            folder: Optional[pulumi.Input[_builtins.str]] = None,
            metric: Optional[pulumi.Input[Union['SdwanPathQualityProfileMetricArgs', 'SdwanPathQualityProfileMetricArgsDict']]] = None,
            name: Optional[pulumi.Input[_builtins.str]] = None,
            snippet: Optional[pulumi.Input[_builtins.str]] = None,
            tfid: Optional[pulumi.Input[_builtins.str]] = None) -> 'SdwanPathQualityProfile':
        """
        Get an existing SdwanPathQualityProfile resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] device: The device in which the resource is defined
        :param pulumi.Input[_builtins.str] folder: The folder in which the resource is defined
               
               > ℹ️ **Note:** You must specify exactly one of `device`, `folder`, and `snippet`.
        :param pulumi.Input[Union['SdwanPathQualityProfileMetricArgs', 'SdwanPathQualityProfileMetricArgsDict']] metric: Metric
        :param pulumi.Input[_builtins.str] name: Profile name
        :param pulumi.Input[_builtins.str] snippet: The snippet in which the resource is defined
               
               > ℹ️ **Note:** You must specify exactly one of `device`, `folder`, and `snippet`.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _SdwanPathQualityProfileState.__new__(_SdwanPathQualityProfileState)

        __props__.__dict__["device"] = device
        __props__.__dict__["folder"] = folder
        __props__.__dict__["metric"] = metric
        __props__.__dict__["name"] = name
        __props__.__dict__["snippet"] = snippet
        __props__.__dict__["tfid"] = tfid
        return SdwanPathQualityProfile(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def device(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The device in which the resource is defined
        """
        return pulumi.get(self, "device")

    @_builtins.property
    @pulumi.getter
    def folder(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The folder in which the resource is defined

        > ℹ️ **Note:** You must specify exactly one of `device`, `folder`, and `snippet`.
        """
        return pulumi.get(self, "folder")

    @_builtins.property
    @pulumi.getter
    def metric(self) -> pulumi.Output['outputs.SdwanPathQualityProfileMetric']:
        """
        Metric
        """
        return pulumi.get(self, "metric")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Profile name
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def snippet(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The snippet in which the resource is defined

        > ℹ️ **Note:** You must specify exactly one of `device`, `folder`, and `snippet`.
        """
        return pulumi.get(self, "snippet")

    @_builtins.property
    @pulumi.getter
    def tfid(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "tfid")

