__title__ = "ConvertEcritures"
__description__ = "Convertisseur d'écritures comptables d'un format à un autre format."
__version__ = "1.2.0"
__author__ = "Michaël AUGUSTE"
__license__ = "MIT"
__url__ = "https://github.com/Atem83/ConvertEcritures"