# generated by datamodel-codegen:
#   filename:  core/frequency_cap.json
#   timestamp: 2026-01-25T21:17:54+00:00

from __future__ import annotations

from typing import Annotated

from adcp.types.base import AdCPBaseModel
from pydantic import ConfigDict, Field


class FrequencyCap(AdCPBaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    suppress_minutes: Annotated[
        float, Field(description='Minutes to suppress after impression', ge=0.0)
    ]
