from minjiang_client.qc.gates import H as H, S as S
from minjiang_client.qc.qc_utils.quantum_gate import FixedGate as FixedGate

def measure_in_basis(tomo_gate, basis): ...
def state_tomography(prob0_x, prob0_y, prob0_z): ...
def get_ideal_rho(gates: FixedGate | list[FixedGate]): ...
