from dataclasses import dataclass

@dataclass
class PipelineParams:
    """Parameters for model prediction pipelines across detection and pose models."""
    iou: float | None = ...
    conf: float | None = ...
    fuse_model: bool = ...
    skip_image_resizing: bool = ...
    nms_top_k: int | None = ...
    max_predictions: int | None = ...
    multi_label_per_box: bool | None = ...
    class_agnostic_nms: bool | None = ...
    pre_nms_max_predictions: int | None = ...
    post_nms_max_predictions: int | None = ...
    fp16: bool = ...
