#  -*- coding: utf-8 -*-
"""
Author: Rafael R. L. Benevides
"""

from numpy.typing import NDArray


def int64_from_datetime64(datetime64: NDArray) -> NDArray: ...

def datetime64_from_int64(int64: NDArray) -> NDArray: ...

def dtf_from_datetime64(datetime64: NDArray) -> NDArray: ...

def int64_from_dtf(dtf: NDArray) -> NDArray: ...

def jd12_from_dtf(dtf: NDArray) -> NDArray: ...

def dtf_from_jd12(jd12: NDArray) -> NDArray: ...

def jd_from_jd12(jd12: NDArray) -> NDArray: ...

def jd12_from_jd(jd: NDArray) -> NDArray: ...

def mjd_from_jd(jd: NDArray) -> NDArray: ...

def jd_from_mjd(mjd: NDArray) -> NDArray: ...

def byear_from_jd12(jd12: NDArray) -> NDArray: ...

def jd12_from_byear(byear: NDArray) -> NDArray: ...

def jyear_from_jd12(jd12: NDArray) -> NDArray: ...

def jd12_from_jyear(jyear: NDArray) -> NDArray: ...

