"""OCSF v1.1.0 Pydantic models."""

from ocsf.v1_1_0.enums import (
    ActivityId,
    AlgorithmId,
    AuthProtocolId,
    AuthTypeId,
    BoundaryId,
    CategoryIds,
    ClassificationIds,
    ConfidenceId,
    ConfidentialityId,
    Depth,
    DirectionId,
    FlagIds,
    HttpMethod,
    ImpactId,
    InjectionTypeId,
    IntegrityId,
    LoadTypeId,
    LogonTypeId,
    OpcodeId,
    PhaseId,
    PrevSecurityLevelId,
    PriorityId,
    ProtocolVerId,
    RcodeId,
    RiskLevelId,
    RunStateId,
    ScoreId,
    SecurityLevelId,
    SeverityId,
    ShareTypeId,
    StateId,
    StatusId,
    StratumId,
    TypeId,
    VerdictId,
)
from ocsf.v1_1_0.events import (
    AccountChange,
    ApiActivity,
    ApplicationLifecycle,
    Authentication,
    AuthorizeSession,
    ComplianceFinding,
    ConfigState,
    DatastoreActivity,
    DetectionFinding,
    DeviceConfigStateChange,
    DhcpActivity,
    DnsActivity,
    EmailActivity,
    EmailFileActivity,
    EmailUrlActivity,
    EntityManagement,
    FileActivity,
    FileHosting,
    FtpActivity,
    GroupManagement,
    HttpActivity,
    IncidentFinding,
    InventoryInfo,
    KernelActivity,
    KernelExtension,
    MemoryActivity,
    ModuleActivity,
    NetworkActivity,
    NetworkFileActivity,
    NtpActivity,
    PatchState,
    ProcessActivity,
    RdpActivity,
    ScanActivity,
    ScheduledJobActivity,
    SecurityFinding,
    SmbActivity,
    SshActivity,
    UserAccess,
    UserInventory,
    VulnerabilityFinding,
    WebResourceAccessActivity,
    WebResourcesActivity,
)
from ocsf.v1_1_0.objects import (
    Account,
    Actor,
    AffectedCode,
    AffectedPackage,
    Analytic,
    Api,
    Attack,
    Authorization,
    Certificate,
    CisBenchmark,
    CisBenchmarkResult,
    CisControl,
    CisCsc,
    Cloud,
    Compliance,
    Container,
    Cve,
    Cvss,
    Cwe,
    Database,
    Databucket,
    DceRpc,
    Device,
    DeviceHwInfo,
    DigitalSignature,
    Display,
    Dns,
    DnsAnswer,
    DnsQuery,
    Email,
    EmailAuth,
    Endpoint,
    EndpointConnection,
    Enrichment,
    Entity,
    Epss,
    Evidences,
    Extension,
    Feature,
    File,
    Finding,
    FindingInfo,
    Fingerprint,
    FirewallRule,
    Group,
    Hassh,
    HttpCookie,
    HttpHeader,
    HttpRequest,
    HttpResponse,
    Idp,
    Image,
    Job,
    KbArticle,
    Kernel,
    KernelDriver,
    KeyboardInfo,
    KillChainPhase,
    LdapPerson,
    LoadBalancer,
    Location,
    Logger,
    Malware,
    ManagedEntity,
    Metadata,
    Metric,
    Module,
    NetworkConnectionInfo,
    NetworkEndpoint,
    NetworkInterface,
    NetworkProxy,
    NetworkTraffic,
    Object,
    Observable,
    Organization,
    Os,
    Package,
    PeripheralDevice,
    Policy,
    Process,
    Product,
    QueryInfo,
    RelatedEvent,
    Remediation,
    Reputation,
    Request,
    Resource,
    ResourceDetails,
    Response,
    RpcInterface,
    Rule,
    San,
    Scan,
    SecurityState,
    Service,
    Session,
    SubTechnique,
    Table,
    Tactic,
    Technique,
    Tls,
    TlsExtension,
    Url,
    User,
    Vulnerability,
    WebResource,
)

__all__ = [
    "Account",
    "AccountChange",
    "ActivityId",
    "Actor",
    "AffectedCode",
    "AffectedPackage",
    "AlgorithmId",
    "Analytic",
    "Api",
    "ApiActivity",
    "ApplicationLifecycle",
    "Attack",
    "AuthProtocolId",
    "AuthTypeId",
    "Authentication",
    "Authorization",
    "AuthorizeSession",
    "BoundaryId",
    "CategoryIds",
    "Certificate",
    "CisBenchmark",
    "CisBenchmarkResult",
    "CisControl",
    "CisCsc",
    "ClassificationIds",
    "Cloud",
    "Compliance",
    "ComplianceFinding",
    "ConfidenceId",
    "ConfidentialityId",
    "ConfigState",
    "Container",
    "Cve",
    "Cvss",
    "Cwe",
    "Database",
    "Databucket",
    "DatastoreActivity",
    "DceRpc",
    "Depth",
    "DetectionFinding",
    "Device",
    "DeviceConfigStateChange",
    "DeviceHwInfo",
    "DhcpActivity",
    "DigitalSignature",
    "DirectionId",
    "Display",
    "Dns",
    "DnsActivity",
    "DnsAnswer",
    "DnsQuery",
    "Email",
    "EmailActivity",
    "EmailAuth",
    "EmailFileActivity",
    "EmailUrlActivity",
    "Endpoint",
    "EndpointConnection",
    "Enrichment",
    "Entity",
    "EntityManagement",
    "Epss",
    "Evidences",
    "Extension",
    "Feature",
    "File",
    "FileActivity",
    "FileHosting",
    "Finding",
    "FindingInfo",
    "Fingerprint",
    "FirewallRule",
    "FlagIds",
    "FtpActivity",
    "Group",
    "GroupManagement",
    "Hassh",
    "HttpActivity",
    "HttpCookie",
    "HttpHeader",
    "HttpMethod",
    "HttpRequest",
    "HttpResponse",
    "Idp",
    "Image",
    "ImpactId",
    "IncidentFinding",
    "InjectionTypeId",
    "IntegrityId",
    "InventoryInfo",
    "Job",
    "KbArticle",
    "Kernel",
    "KernelActivity",
    "KernelDriver",
    "KernelExtension",
    "KeyboardInfo",
    "KillChainPhase",
    "LdapPerson",
    "LoadBalancer",
    "LoadTypeId",
    "Location",
    "Logger",
    "LogonTypeId",
    "Malware",
    "ManagedEntity",
    "MemoryActivity",
    "Metadata",
    "Metric",
    "Module",
    "ModuleActivity",
    "NetworkActivity",
    "NetworkConnectionInfo",
    "NetworkEndpoint",
    "NetworkFileActivity",
    "NetworkInterface",
    "NetworkProxy",
    "NetworkTraffic",
    "NtpActivity",
    "Object",
    "Observable",
    "OpcodeId",
    "Organization",
    "Os",
    "Package",
    "PatchState",
    "PeripheralDevice",
    "PhaseId",
    "Policy",
    "PrevSecurityLevelId",
    "PriorityId",
    "Process",
    "ProcessActivity",
    "Product",
    "ProtocolVerId",
    "QueryInfo",
    "RcodeId",
    "RdpActivity",
    "RelatedEvent",
    "Remediation",
    "Reputation",
    "Request",
    "Resource",
    "ResourceDetails",
    "Response",
    "RiskLevelId",
    "RpcInterface",
    "Rule",
    "RunStateId",
    "San",
    "Scan",
    "ScanActivity",
    "ScheduledJobActivity",
    "ScoreId",
    "SecurityFinding",
    "SecurityLevelId",
    "SecurityState",
    "Service",
    "Session",
    "SeverityId",
    "ShareTypeId",
    "SmbActivity",
    "SshActivity",
    "StateId",
    "StatusId",
    "StratumId",
    "SubTechnique",
    "Table",
    "Tactic",
    "Technique",
    "Tls",
    "TlsExtension",
    "TypeId",
    "Url",
    "User",
    "UserAccess",
    "UserInventory",
    "VerdictId",
    "Vulnerability",
    "VulnerabilityFinding",
    "WebResource",
    "WebResourceAccessActivity",
    "WebResourcesActivity",
]


# Rebuild models to resolve forward references
def _rebuild_models() -> None:
    """Rebuild all models to resolve forward references after all imports are complete."""
    import sys

    # Pass the current module's globals so Pydantic can find all imported types
    _globals = sys.modules[__name__].__dict__
    Dns.model_rebuild(_types_namespace=_globals)
    Entity.model_rebuild(_types_namespace=_globals)
    Resource.model_rebuild(_types_namespace=_globals)
    Account.model_rebuild(_types_namespace=_globals)
    Actor.model_rebuild(_types_namespace=_globals)
    AffectedCode.model_rebuild(_types_namespace=_globals)
    AffectedPackage.model_rebuild(_types_namespace=_globals)
    Analytic.model_rebuild(_types_namespace=_globals)
    Api.model_rebuild(_types_namespace=_globals)
    Attack.model_rebuild(_types_namespace=_globals)
    Authorization.model_rebuild(_types_namespace=_globals)
    Certificate.model_rebuild(_types_namespace=_globals)
    CisBenchmark.model_rebuild(_types_namespace=_globals)
    CisBenchmarkResult.model_rebuild(_types_namespace=_globals)
    CisControl.model_rebuild(_types_namespace=_globals)
    CisCsc.model_rebuild(_types_namespace=_globals)
    Cloud.model_rebuild(_types_namespace=_globals)
    Compliance.model_rebuild(_types_namespace=_globals)
    Container.model_rebuild(_types_namespace=_globals)
    Cve.model_rebuild(_types_namespace=_globals)
    Cvss.model_rebuild(_types_namespace=_globals)
    Cwe.model_rebuild(_types_namespace=_globals)
    Database.model_rebuild(_types_namespace=_globals)
    Databucket.model_rebuild(_types_namespace=_globals)
    DceRpc.model_rebuild(_types_namespace=_globals)
    Device.model_rebuild(_types_namespace=_globals)
    DeviceHwInfo.model_rebuild(_types_namespace=_globals)
    DigitalSignature.model_rebuild(_types_namespace=_globals)
    Display.model_rebuild(_types_namespace=_globals)
    DnsAnswer.model_rebuild(_types_namespace=_globals)
    DnsQuery.model_rebuild(_types_namespace=_globals)
    Email.model_rebuild(_types_namespace=_globals)
    EmailAuth.model_rebuild(_types_namespace=_globals)
    Endpoint.model_rebuild(_types_namespace=_globals)
    EndpointConnection.model_rebuild(_types_namespace=_globals)
    Enrichment.model_rebuild(_types_namespace=_globals)
    Epss.model_rebuild(_types_namespace=_globals)
    Evidences.model_rebuild(_types_namespace=_globals)
    Extension.model_rebuild(_types_namespace=_globals)
    Feature.model_rebuild(_types_namespace=_globals)
    File.model_rebuild(_types_namespace=_globals)
    Finding.model_rebuild(_types_namespace=_globals)
    FindingInfo.model_rebuild(_types_namespace=_globals)
    Fingerprint.model_rebuild(_types_namespace=_globals)
    FirewallRule.model_rebuild(_types_namespace=_globals)
    Group.model_rebuild(_types_namespace=_globals)
    Hassh.model_rebuild(_types_namespace=_globals)
    HttpCookie.model_rebuild(_types_namespace=_globals)
    HttpHeader.model_rebuild(_types_namespace=_globals)
    HttpRequest.model_rebuild(_types_namespace=_globals)
    HttpResponse.model_rebuild(_types_namespace=_globals)
    Idp.model_rebuild(_types_namespace=_globals)
    Image.model_rebuild(_types_namespace=_globals)
    Job.model_rebuild(_types_namespace=_globals)
    KbArticle.model_rebuild(_types_namespace=_globals)
    Kernel.model_rebuild(_types_namespace=_globals)
    KernelDriver.model_rebuild(_types_namespace=_globals)
    KeyboardInfo.model_rebuild(_types_namespace=_globals)
    KillChainPhase.model_rebuild(_types_namespace=_globals)
    LdapPerson.model_rebuild(_types_namespace=_globals)
    LoadBalancer.model_rebuild(_types_namespace=_globals)
    Location.model_rebuild(_types_namespace=_globals)
    Logger.model_rebuild(_types_namespace=_globals)
    Malware.model_rebuild(_types_namespace=_globals)
    ManagedEntity.model_rebuild(_types_namespace=_globals)
    Metadata.model_rebuild(_types_namespace=_globals)
    Metric.model_rebuild(_types_namespace=_globals)
    Module.model_rebuild(_types_namespace=_globals)
    NetworkConnectionInfo.model_rebuild(_types_namespace=_globals)
    NetworkEndpoint.model_rebuild(_types_namespace=_globals)
    NetworkInterface.model_rebuild(_types_namespace=_globals)
    NetworkProxy.model_rebuild(_types_namespace=_globals)
    NetworkTraffic.model_rebuild(_types_namespace=_globals)
    Object.model_rebuild(_types_namespace=_globals)
    Observable.model_rebuild(_types_namespace=_globals)
    Organization.model_rebuild(_types_namespace=_globals)
    Os.model_rebuild(_types_namespace=_globals)
    Package.model_rebuild(_types_namespace=_globals)
    PeripheralDevice.model_rebuild(_types_namespace=_globals)
    Policy.model_rebuild(_types_namespace=_globals)
    Process.model_rebuild(_types_namespace=_globals)
    Product.model_rebuild(_types_namespace=_globals)
    QueryInfo.model_rebuild(_types_namespace=_globals)
    RelatedEvent.model_rebuild(_types_namespace=_globals)
    Remediation.model_rebuild(_types_namespace=_globals)
    Reputation.model_rebuild(_types_namespace=_globals)
    Request.model_rebuild(_types_namespace=_globals)
    ResourceDetails.model_rebuild(_types_namespace=_globals)
    Response.model_rebuild(_types_namespace=_globals)
    RpcInterface.model_rebuild(_types_namespace=_globals)
    Rule.model_rebuild(_types_namespace=_globals)
    San.model_rebuild(_types_namespace=_globals)
    Scan.model_rebuild(_types_namespace=_globals)
    SecurityState.model_rebuild(_types_namespace=_globals)
    Service.model_rebuild(_types_namespace=_globals)
    Session.model_rebuild(_types_namespace=_globals)
    SubTechnique.model_rebuild(_types_namespace=_globals)
    Table.model_rebuild(_types_namespace=_globals)
    Tactic.model_rebuild(_types_namespace=_globals)
    Technique.model_rebuild(_types_namespace=_globals)
    Tls.model_rebuild(_types_namespace=_globals)
    TlsExtension.model_rebuild(_types_namespace=_globals)
    Url.model_rebuild(_types_namespace=_globals)
    User.model_rebuild(_types_namespace=_globals)
    Vulnerability.model_rebuild(_types_namespace=_globals)
    WebResource.model_rebuild(_types_namespace=_globals)
    ApiActivity.model_rebuild(_types_namespace=_globals)
    ApplicationLifecycle.model_rebuild(_types_namespace=_globals)
    DatastoreActivity.model_rebuild(_types_namespace=_globals)
    FileHosting.model_rebuild(_types_namespace=_globals)
    ScanActivity.model_rebuild(_types_namespace=_globals)
    WebResourceAccessActivity.model_rebuild(_types_namespace=_globals)
    WebResourcesActivity.model_rebuild(_types_namespace=_globals)
    ConfigState.model_rebuild(_types_namespace=_globals)
    DeviceConfigStateChange.model_rebuild(_types_namespace=_globals)
    InventoryInfo.model_rebuild(_types_namespace=_globals)
    PatchState.model_rebuild(_types_namespace=_globals)
    UserInventory.model_rebuild(_types_namespace=_globals)
    ComplianceFinding.model_rebuild(_types_namespace=_globals)
    DetectionFinding.model_rebuild(_types_namespace=_globals)
    IncidentFinding.model_rebuild(_types_namespace=_globals)
    SecurityFinding.model_rebuild(_types_namespace=_globals)
    VulnerabilityFinding.model_rebuild(_types_namespace=_globals)
    AccountChange.model_rebuild(_types_namespace=_globals)
    Authentication.model_rebuild(_types_namespace=_globals)
    AuthorizeSession.model_rebuild(_types_namespace=_globals)
    EntityManagement.model_rebuild(_types_namespace=_globals)
    GroupManagement.model_rebuild(_types_namespace=_globals)
    UserAccess.model_rebuild(_types_namespace=_globals)
    DhcpActivity.model_rebuild(_types_namespace=_globals)
    DnsActivity.model_rebuild(_types_namespace=_globals)
    EmailActivity.model_rebuild(_types_namespace=_globals)
    EmailFileActivity.model_rebuild(_types_namespace=_globals)
    EmailUrlActivity.model_rebuild(_types_namespace=_globals)
    NetworkFileActivity.model_rebuild(_types_namespace=_globals)
    FtpActivity.model_rebuild(_types_namespace=_globals)
    HttpActivity.model_rebuild(_types_namespace=_globals)
    NetworkActivity.model_rebuild(_types_namespace=_globals)
    NtpActivity.model_rebuild(_types_namespace=_globals)
    RdpActivity.model_rebuild(_types_namespace=_globals)
    SmbActivity.model_rebuild(_types_namespace=_globals)
    SshActivity.model_rebuild(_types_namespace=_globals)
    FileActivity.model_rebuild(_types_namespace=_globals)
    KernelActivity.model_rebuild(_types_namespace=_globals)
    KernelExtension.model_rebuild(_types_namespace=_globals)
    MemoryActivity.model_rebuild(_types_namespace=_globals)
    ModuleActivity.model_rebuild(_types_namespace=_globals)
    ProcessActivity.model_rebuild(_types_namespace=_globals)
    ScheduledJobActivity.model_rebuild(_types_namespace=_globals)


# Only rebuild if this is the first import (not during circular imports)
if __name__ != "__main__":
    _rebuild_models()
