# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2025.12.2
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_client.models.enrollment_token_request import EnrollmentTokenRequest

class TestEnrollmentTokenRequest(unittest.TestCase):
    """EnrollmentTokenRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EnrollmentTokenRequest:
        """Test EnrollmentTokenRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EnrollmentTokenRequest`
        """
        model = EnrollmentTokenRequest()
        if include_optional:
            return EnrollmentTokenRequest(
                device_group = '',
                connector = '',
                name = '0',
                expiring = True,
                expires = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return EnrollmentTokenRequest(
                connector = '',
                name = '0',
        )
        """

    def testEnrollmentTokenRequest(self):
        """Test EnrollmentTokenRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
