# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2025.12.2
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_client.models.password_stage_request import PasswordStageRequest

class TestPasswordStageRequest(unittest.TestCase):
    """PasswordStageRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PasswordStageRequest:
        """Test PasswordStageRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PasswordStageRequest`
        """
        model = PasswordStageRequest()
        if include_optional:
            return PasswordStageRequest(
                name = '0',
                backends = [
                    'authentik.core.auth.InbuiltBackend'
                    ],
                configure_flow = '',
                failed_attempts_before_cancel = -2147483648,
                allow_show_password = True
            )
        else:
            return PasswordStageRequest(
                name = '0',
                backends = [
                    'authentik.core.auth.InbuiltBackend'
                    ],
        )
        """

    def testPasswordStageRequest(self):
        """Test PasswordStageRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
