"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import ansys.api.discovery.v0.conditions.displacement_pb2
import ansys.api.discovery.v0.discoverymodels_pb2
import grpc

class DisplacementStub:
    def __init__(self, channel: grpc.Channel) -> None: ...
    CreateDisplacementTranslation: grpc.UnaryUnaryMultiCallable[
        ansys.api.discovery.v0.conditions.displacement_pb2.DisplacementTranslationCreationRequest,
        ansys.api.discovery.v0.conditions.displacement_pb2.DisplacementCreationResponse] = ...
    """Displacement condition methods"""

    CreateDisplacementRotation: grpc.UnaryUnaryMultiCallable[
        ansys.api.discovery.v0.conditions.displacement_pb2.DisplacementRotationCreationRequest,
        ansys.api.discovery.v0.conditions.displacement_pb2.DisplacementCreationResponse] = ...

    CreateDisplacementCombined: grpc.UnaryUnaryMultiCallable[
        ansys.api.discovery.v0.conditions.displacement_pb2.DisplacementCombinedCreationRequest,
        ansys.api.discovery.v0.conditions.displacement_pb2.DisplacementCreationResponse] = ...

    ChangeDisplacementLocation: grpc.UnaryUnaryMultiCallable[
        ansys.api.discovery.v0.discoverymodels_pb2.ChangeLocationRequest,
        ansys.api.discovery.v0.discoverymodels_pb2.ChangeResponse] = ...

    ChangeDisplacementSpecification: grpc.UnaryUnaryMultiCallable[
        ansys.api.discovery.v0.conditions.displacement_pb2.ChangeDisplacementSpecificationRequest,
        ansys.api.discovery.v0.discoverymodels_pb2.ChangeResponse] = ...

    ChangeDisplacementOrientation: grpc.UnaryUnaryMultiCallable[
        ansys.api.discovery.v0.discoverymodels_pb2.ChangeDirectionRequest,
        ansys.api.discovery.v0.discoverymodels_pb2.ChangeResponse] = ...

    ChangeDisplacementDX: grpc.UnaryUnaryMultiCallable[
        ansys.api.discovery.v0.discoverymodels_pb2.ChangeQuantityRequest,
        ansys.api.discovery.v0.discoverymodels_pb2.ChangeResponse] = ...

    ChangeDisplacementDY: grpc.UnaryUnaryMultiCallable[
        ansys.api.discovery.v0.discoverymodels_pb2.ChangeQuantityRequest,
        ansys.api.discovery.v0.discoverymodels_pb2.ChangeResponse] = ...

    ChangeDisplacementDZ: grpc.UnaryUnaryMultiCallable[
        ansys.api.discovery.v0.discoverymodels_pb2.ChangeQuantityRequest,
        ansys.api.discovery.v0.discoverymodels_pb2.ChangeResponse] = ...

    ChangeDisplacementTranslationalMagnitude: grpc.UnaryUnaryMultiCallable[
        ansys.api.discovery.v0.discoverymodels_pb2.ChangeQuantityRequest,
        ansys.api.discovery.v0.discoverymodels_pb2.ChangeResponse] = ...

    ChangeDisplacementRX: grpc.UnaryUnaryMultiCallable[
        ansys.api.discovery.v0.discoverymodels_pb2.ChangeQuantityRequest,
        ansys.api.discovery.v0.discoverymodels_pb2.ChangeResponse] = ...

    ChangeDisplacementRY: grpc.UnaryUnaryMultiCallable[
        ansys.api.discovery.v0.discoverymodels_pb2.ChangeQuantityRequest,
        ansys.api.discovery.v0.discoverymodels_pb2.ChangeResponse] = ...

    ChangeDisplacementRZ: grpc.UnaryUnaryMultiCallable[
        ansys.api.discovery.v0.discoverymodels_pb2.ChangeQuantityRequest,
        ansys.api.discovery.v0.discoverymodels_pb2.ChangeResponse] = ...

    ChangeDisplacementRotationalMagnitude: grpc.UnaryUnaryMultiCallable[
        ansys.api.discovery.v0.discoverymodels_pb2.ChangeQuantityRequest,
        ansys.api.discovery.v0.discoverymodels_pb2.ChangeResponse] = ...

    ChangeDisplacementIsFixedDX: grpc.UnaryUnaryMultiCallable[
        ansys.api.discovery.v0.discoverymodels_pb2.ChangeBooleanRequest,
        ansys.api.discovery.v0.discoverymodels_pb2.ChangeResponse] = ...

    ChangeDisplacementIsFixedDY: grpc.UnaryUnaryMultiCallable[
        ansys.api.discovery.v0.discoverymodels_pb2.ChangeBooleanRequest,
        ansys.api.discovery.v0.discoverymodels_pb2.ChangeResponse] = ...

    ChangeDisplacementIsFixedDZ: grpc.UnaryUnaryMultiCallable[
        ansys.api.discovery.v0.discoverymodels_pb2.ChangeBooleanRequest,
        ansys.api.discovery.v0.discoverymodels_pb2.ChangeResponse] = ...

    ChangeDisplacementIsFixedRX: grpc.UnaryUnaryMultiCallable[
        ansys.api.discovery.v0.discoverymodels_pb2.ChangeBooleanRequest,
        ansys.api.discovery.v0.discoverymodels_pb2.ChangeResponse] = ...

    ChangeDisplacementIsFixedRY: grpc.UnaryUnaryMultiCallable[
        ansys.api.discovery.v0.discoverymodels_pb2.ChangeBooleanRequest,
        ansys.api.discovery.v0.discoverymodels_pb2.ChangeResponse] = ...

    ChangeDisplacementIsFixedRZ: grpc.UnaryUnaryMultiCallable[
        ansys.api.discovery.v0.discoverymodels_pb2.ChangeBooleanRequest,
        ansys.api.discovery.v0.discoverymodels_pb2.ChangeResponse] = ...

    ChangeDisplacementUseRemotePointEnabled: grpc.UnaryUnaryMultiCallable[
        ansys.api.discovery.v0.discoverymodels_pb2.ChangeBooleanRequest,
        ansys.api.discovery.v0.discoverymodels_pb2.ChangeResponse] = ...

    ChangeDisplacementDistributedRemotePositionX: grpc.UnaryUnaryMultiCallable[
        ansys.api.discovery.v0.discoverymodels_pb2.ChangeQuantityRequest,
        ansys.api.discovery.v0.discoverymodels_pb2.ChangeResponse] = ...

    ChangeDisplacementDistributedRemotePositionY: grpc.UnaryUnaryMultiCallable[
        ansys.api.discovery.v0.discoverymodels_pb2.ChangeQuantityRequest,
        ansys.api.discovery.v0.discoverymodels_pb2.ChangeResponse] = ...

    ChangeDisplacementDistributedRemotePositionZ: grpc.UnaryUnaryMultiCallable[
        ansys.api.discovery.v0.discoverymodels_pb2.ChangeQuantityRequest,
        ansys.api.discovery.v0.discoverymodels_pb2.ChangeResponse] = ...


class DisplacementServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def CreateDisplacementTranslation(self,
        request: ansys.api.discovery.v0.conditions.displacement_pb2.DisplacementTranslationCreationRequest,
        context: grpc.ServicerContext,
    ) -> ansys.api.discovery.v0.conditions.displacement_pb2.DisplacementCreationResponse:
        """Displacement condition methods"""
        pass

    @abc.abstractmethod
    def CreateDisplacementRotation(self,
        request: ansys.api.discovery.v0.conditions.displacement_pb2.DisplacementRotationCreationRequest,
        context: grpc.ServicerContext,
    ) -> ansys.api.discovery.v0.conditions.displacement_pb2.DisplacementCreationResponse: ...

    @abc.abstractmethod
    def CreateDisplacementCombined(self,
        request: ansys.api.discovery.v0.conditions.displacement_pb2.DisplacementCombinedCreationRequest,
        context: grpc.ServicerContext,
    ) -> ansys.api.discovery.v0.conditions.displacement_pb2.DisplacementCreationResponse: ...

    @abc.abstractmethod
    def ChangeDisplacementLocation(self,
        request: ansys.api.discovery.v0.discoverymodels_pb2.ChangeLocationRequest,
        context: grpc.ServicerContext,
    ) -> ansys.api.discovery.v0.discoverymodels_pb2.ChangeResponse: ...

    @abc.abstractmethod
    def ChangeDisplacementSpecification(self,
        request: ansys.api.discovery.v0.conditions.displacement_pb2.ChangeDisplacementSpecificationRequest,
        context: grpc.ServicerContext,
    ) -> ansys.api.discovery.v0.discoverymodels_pb2.ChangeResponse: ...

    @abc.abstractmethod
    def ChangeDisplacementOrientation(self,
        request: ansys.api.discovery.v0.discoverymodels_pb2.ChangeDirectionRequest,
        context: grpc.ServicerContext,
    ) -> ansys.api.discovery.v0.discoverymodels_pb2.ChangeResponse: ...

    @abc.abstractmethod
    def ChangeDisplacementDX(self,
        request: ansys.api.discovery.v0.discoverymodels_pb2.ChangeQuantityRequest,
        context: grpc.ServicerContext,
    ) -> ansys.api.discovery.v0.discoverymodels_pb2.ChangeResponse: ...

    @abc.abstractmethod
    def ChangeDisplacementDY(self,
        request: ansys.api.discovery.v0.discoverymodels_pb2.ChangeQuantityRequest,
        context: grpc.ServicerContext,
    ) -> ansys.api.discovery.v0.discoverymodels_pb2.ChangeResponse: ...

    @abc.abstractmethod
    def ChangeDisplacementDZ(self,
        request: ansys.api.discovery.v0.discoverymodels_pb2.ChangeQuantityRequest,
        context: grpc.ServicerContext,
    ) -> ansys.api.discovery.v0.discoverymodels_pb2.ChangeResponse: ...

    @abc.abstractmethod
    def ChangeDisplacementTranslationalMagnitude(self,
        request: ansys.api.discovery.v0.discoverymodels_pb2.ChangeQuantityRequest,
        context: grpc.ServicerContext,
    ) -> ansys.api.discovery.v0.discoverymodels_pb2.ChangeResponse: ...

    @abc.abstractmethod
    def ChangeDisplacementRX(self,
        request: ansys.api.discovery.v0.discoverymodels_pb2.ChangeQuantityRequest,
        context: grpc.ServicerContext,
    ) -> ansys.api.discovery.v0.discoverymodels_pb2.ChangeResponse: ...

    @abc.abstractmethod
    def ChangeDisplacementRY(self,
        request: ansys.api.discovery.v0.discoverymodels_pb2.ChangeQuantityRequest,
        context: grpc.ServicerContext,
    ) -> ansys.api.discovery.v0.discoverymodels_pb2.ChangeResponse: ...

    @abc.abstractmethod
    def ChangeDisplacementRZ(self,
        request: ansys.api.discovery.v0.discoverymodels_pb2.ChangeQuantityRequest,
        context: grpc.ServicerContext,
    ) -> ansys.api.discovery.v0.discoverymodels_pb2.ChangeResponse: ...

    @abc.abstractmethod
    def ChangeDisplacementRotationalMagnitude(self,
        request: ansys.api.discovery.v0.discoverymodels_pb2.ChangeQuantityRequest,
        context: grpc.ServicerContext,
    ) -> ansys.api.discovery.v0.discoverymodels_pb2.ChangeResponse: ...

    @abc.abstractmethod
    def ChangeDisplacementIsFixedDX(self,
        request: ansys.api.discovery.v0.discoverymodels_pb2.ChangeBooleanRequest,
        context: grpc.ServicerContext,
    ) -> ansys.api.discovery.v0.discoverymodels_pb2.ChangeResponse: ...

    @abc.abstractmethod
    def ChangeDisplacementIsFixedDY(self,
        request: ansys.api.discovery.v0.discoverymodels_pb2.ChangeBooleanRequest,
        context: grpc.ServicerContext,
    ) -> ansys.api.discovery.v0.discoverymodels_pb2.ChangeResponse: ...

    @abc.abstractmethod
    def ChangeDisplacementIsFixedDZ(self,
        request: ansys.api.discovery.v0.discoverymodels_pb2.ChangeBooleanRequest,
        context: grpc.ServicerContext,
    ) -> ansys.api.discovery.v0.discoverymodels_pb2.ChangeResponse: ...

    @abc.abstractmethod
    def ChangeDisplacementIsFixedRX(self,
        request: ansys.api.discovery.v0.discoverymodels_pb2.ChangeBooleanRequest,
        context: grpc.ServicerContext,
    ) -> ansys.api.discovery.v0.discoverymodels_pb2.ChangeResponse: ...

    @abc.abstractmethod
    def ChangeDisplacementIsFixedRY(self,
        request: ansys.api.discovery.v0.discoverymodels_pb2.ChangeBooleanRequest,
        context: grpc.ServicerContext,
    ) -> ansys.api.discovery.v0.discoverymodels_pb2.ChangeResponse: ...

    @abc.abstractmethod
    def ChangeDisplacementIsFixedRZ(self,
        request: ansys.api.discovery.v0.discoverymodels_pb2.ChangeBooleanRequest,
        context: grpc.ServicerContext,
    ) -> ansys.api.discovery.v0.discoverymodels_pb2.ChangeResponse: ...

    @abc.abstractmethod
    def ChangeDisplacementUseRemotePointEnabled(self,
        request: ansys.api.discovery.v0.discoverymodels_pb2.ChangeBooleanRequest,
        context: grpc.ServicerContext,
    ) -> ansys.api.discovery.v0.discoverymodels_pb2.ChangeResponse: ...

    @abc.abstractmethod
    def ChangeDisplacementDistributedRemotePositionX(self,
        request: ansys.api.discovery.v0.discoverymodels_pb2.ChangeQuantityRequest,
        context: grpc.ServicerContext,
    ) -> ansys.api.discovery.v0.discoverymodels_pb2.ChangeResponse: ...

    @abc.abstractmethod
    def ChangeDisplacementDistributedRemotePositionY(self,
        request: ansys.api.discovery.v0.discoverymodels_pb2.ChangeQuantityRequest,
        context: grpc.ServicerContext,
    ) -> ansys.api.discovery.v0.discoverymodels_pb2.ChangeResponse: ...

    @abc.abstractmethod
    def ChangeDisplacementDistributedRemotePositionZ(self,
        request: ansys.api.discovery.v0.discoverymodels_pb2.ChangeQuantityRequest,
        context: grpc.ServicerContext,
    ) -> ansys.api.discovery.v0.discoverymodels_pb2.ChangeResponse: ...


def add_DisplacementServicer_to_server(servicer: DisplacementServicer, server: grpc.Server) -> None: ...
