"""
    HW Mux Reservation System

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.22.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import hwmux_client
from hwmux_client.model.location_serializer_write_only import LocationSerializerWriteOnly


class TestLocationSerializerWriteOnly(unittest.TestCase):
    """LocationSerializerWriteOnly unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLocationSerializerWriteOnly(self):
        """Test LocationSerializerWriteOnly"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LocationSerializerWriteOnly()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
